#!/usr/bin/env python3
"""
fix_blog_index_links.py — Patch blog/index.html float filename links

Fixes stale blog index that has links like week-0.0.html / week-2.0.html
(generated by an older version of the chronicle lambda) replacing them with
the correct zero-padded format week-00.html / week-02.html.

Usage: python3 patches/fix_blog_index_links.py
"""

import re
import boto3

REGION    = "us-west-2"
S3_BUCKET = "matthew-life-platform"
INDEX_KEY = "blog/index.html"

s3 = boto3.client("s3", region_name=REGION)

# Download
print(f"Downloading s3://{S3_BUCKET}/{INDEX_KEY} ...")
resp = s3.get_object(Bucket=S3_BUCKET, Key=INDEX_KEY)
html = resp["Body"].read().decode("utf-8")

# Show current links
print("\nLinks found before patch:")
for m in re.findall(r'href="(week-[^"]+\.html)"', html):
    print(f"  {m}")

# Fix: replace week-N.0.html → week-NN.html (handles any float-formatted week number)
def fix_float_week(m):
    raw = m.group(1)         # e.g. "0.0" or "2.0"
    try:
        n = int(float(raw))
        return f'href="week-{n:02d}.html"'
    except Exception:
        return m.group(0)

patched = re.sub(r'href="week-([\d.]+)\.html"', fix_float_week, html)

# Show what changed
print("\nLinks found after patch:")
for m in re.findall(r'href="(week-[^"]+\.html)"', patched):
    print(f"  {m}")

if patched == html:
    print("\nNo changes needed — index is already correct.")
else:
    # Upload
    s3.put_object(
        Bucket=S3_BUCKET,
        Key=INDEX_KEY,
        Body=patched.encode("utf-8"),
        ContentType="text/html",
        CacheControl="max-age=300",
    )
    print(f"\nPatched index uploaded to s3://{S3_BUCKET}/{INDEX_KEY}")

    # Invalidate CloudFront cache
    import subprocess
    result = subprocess.run([
        "aws", "cloudfront", "create-invalidation",
        "--distribution-id", "E1JOC1V6E6DDYI",
        "--paths", "/index.html",
        "--region", "us-east-1"
    ], capture_output=True, text=True)
    if result.returncode == 0:
        print("CloudFront invalidation created for /index.html")
    else:
        print(f"CloudFront invalidation failed (run manually): {result.stderr.strip()}")
        print("  aws cloudfront create-invalidation --distribution-id E1JOC1V6E6DDYI --paths '/index.html'")
