"""tests/derived_artifact_registry.py — the derived-artifact registry (epic #2986).

WHY THIS EXISTS
---------------
A derived artifact needs four things: a **generator**, a **writer** that can self-heal it,
a **guard**, and that guard placed in a **lane the artifact's inputs trigger**. Discovery
below finds **28 scripts** writing a git-tracked artifact and, until this file, nothing
declared which of the four each one has. So the gaps were found one incident at a time, and each one cost
a misattributed main-red or weeks of silent drift:

  * `incident_log_patterns` (#2975) — guard ✓, but in a lane a `docs/**` change cannot
    trigger. Every wrap adds incident rows by design, so the red landed on whichever later
    commit happened to touch `tests/**`, and whoever debugged it started from an unrelated
    diff. Structural, not bad luck.
  * `generate_platform_model` — guard ✓ and in the right workflow, but OUTSIDE the
    `premerge` marker, so a `lambdas/**` PR that stales the model reds `main` rather than
    the PR that did it.
  * `generate_mcp_tool_catalog` — has a `--check` wired into NOTHING: no workflow step, no
    pytest, no `run_generators()`. Measured 2026-08-22: stale, and stale **behind a fresh
    timestamp** — the reconcile bot touches the file daily because `sync_doc_metadata`
    rewrites its `Total tools:` literal, while the generated body had not been re-run since
    2026-07-25. The doc contradicted itself two lines apart: `Total tools: 76` above
    `## All 72 Tools`.

Three artifacts, three genuinely different broken triples. That is a class, and a class
gets a registry (`docs/CHARTER.md` primitive 1) with a derivation guard over it (primitive
2), not three more one-off fixes.

HOW IT'S GUARDED (guard the SET, not the instance)
--------------------------------------------------
`discover_generators()` reads the tree for every script that writes a path under a
committed artifact root. `ARTIFACTS` records one decision per discovered generator.
`tests/test_derived_artifact_registry_2986.py` asserts BOTH directions:

  * every discovered generator has an entry → a NEW generator writing a committed artifact
    fails the build until someone classifies it as DERIVED, BUILDER or EXCLUDED;
  * every entry still resolves to a real discovered generator → the registry cannot rot
    into a hand-list describing scripts that no longer exist.

and, for every `DERIVED` entry, that its declared guard command really appears in its
declared lane, and that **the lane's trigger paths cover the artifact's inputs** — the
#2975 rule, generalized. That last assertion is the one the three incidents above all
failed, each in a different place.

WHY A DECLARED LANE AND NOT "THERE IS A TEST"
---------------------------------------------
"Is there a guard?" was already answerable and already answered YES for two of the three.
The question that separated a working guard from a misattributing one was *which lane*, and
that is not derivable from the guard alone — it is a fact about the workflow's path filter.
So the lane is declared and then CHECKED against the workflow file, rather than inferred.
"""

from __future__ import annotations

import ast
import fnmatch
import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(_HERE)

# Trees whose contents are committed build output — a script writing here is producing an
# artifact a reader or another gate will trust. `handovers/` and `qa-screenshots/` are
# deliberately absent: the first is session scratch (#1650), the second is gitignored.
ARTIFACT_ROOTS = ("docs", "site", "model", "config")

# Directories that hold scripts capable of producing one.
GENERATOR_DIRS = ("scripts", "deploy")

# ── Lanes ─────────────────────────────────────────────────────────────────────
# A lane is a (workflow, trigger-path-source) pair. The guard's placement only matters
# relative to what the lane RUNS ON, so that is what a lane resolves to.
LANE_DOCS_CI = "docs-ci"  # .github/workflows/docs-ci.yml — the docs/** lane
LANE_CI_CD = "ci-cd"  # .github/workflows/ci-cd.yml — the code lane

_LANE_WORKFLOW = {
    LANE_DOCS_CI: ".github/workflows/docs-ci.yml",
    LANE_CI_CD: ".github/workflows/ci-cd.yml",
}

# ── Decisions ─────────────────────────────────────────────────────────────────
#
# The distinction that matters is NOT "generated vs hand-written" — nearly everything here
# is generated. It is **who is responsible for noticing staleness**. A DERIVED artifact's
# answer is "CI, on the commit that staled it"; a BUILDER's is "the person who runs the
# build step", and that is a legitimate answer as long as the step is named.
DERIVED = "DERIVED"  # continuously derived from repo state — needs writer + guard + lane
BUILDER = "BUILDER"  # regenerated by a named build/deploy step; no drift contract
EXCLUDED = "EXCLUDED"  # discovery names the path but this script does not own it
VALID_DECISIONS = frozenset({DERIVED, BUILDER, EXCLUDED})


def _derived(generator, outputs, writer, guard, guard_lane, inputs, reconciled, reason):
    return {
        "decision": DERIVED,
        "generator": generator,
        "outputs": tuple(outputs),
        "writer": writer,
        "guard": guard,
        "guard_lane": guard_lane,
        # The paths whose change can stale this artifact. The lane must trigger on them,
        # or the guard reds somebody else's commit.
        "inputs": tuple(inputs),
        "reconciled": reconciled,  # in ci-cd.yml's run_generators()
        "reason": reason,
    }


def _builder(generator, step, reason):
    """A builder must name the STEP that runs it. 'someone runs it' is how an artifact
    goes a month stale behind a fresh timestamp — the #2986 catalog finding."""
    return {"decision": BUILDER, "generator": generator, "step": step, "reason": reason}


def _excluded(generator, reason):
    return {"decision": EXCLUDED, "generator": generator, "reason": reason}


# Every entry carries a reason SPECIFIC to it. A registry whose reasons are all one
# sentence records that nobody looked (the #2056 lesson, restated in privacy_tier_wiring).
ARTIFACTS: dict[str, dict] = {
    "deploy/sync_doc_metadata.py": _derived(
        generator="deploy/sync_doc_metadata.py",
        outputs=("docs/*.md", "CLAUDE.md", "lambdas/web/platform_counts.py"),
        writer="python3 deploy/sync_doc_metadata.py --apply",
        guard="deploy/sync_doc_metadata.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=(
            "docs/**",
            "lambdas/**",
            "mcp/**",
            "cdk/**",
            # #3000: the gate_census_count fact (docs/PROPORTIONALITY.md's row) is
            # derived from scripts/gate_census.py's build_census(), which walks
            # .github/workflows/** directly — a workflow-only change could stale the
            # row with nothing in the OLD input list able to trigger a re-check.
            ".github/workflows/**",
            "scripts/gate_census.py",
            "scripts/gate_census_precision.py",
        ),
        reconciled=True,
        reason=(
            "The literal sweep — test/tool/lambda/ADR counts across the wiki. Its inputs are "
            "both halves of the doc↔source coupling (#1908), which is why docs-ci.yml carries "
            "the code paths as well as docs/**. #3101 moved the counter literals out of "
            "lambdas/web/site_api_common.py (a hand-merged module) into lambdas/web/"
            "platform_counts.py, a file whose ENTIRE content is generator output — which is "
            "what a derived artifact is supposed to look like, and what makes the "
            "'never commit it on a branch' rule enforceable instead of advisory."
            "The literal sweep — test/tool/lambda/ADR/gate-census counts across the wiki. Its "
            "inputs are both halves of the doc↔source coupling (#1908), which is why docs-ci.yml "
            "carries the code paths as well as docs/**. #3000 added the gate_census_count fact "
            "(docs/PROPORTIONALITY.md's row, epic #2578) and the two workflow-side inputs that "
            "can stale it — HONEST LIMIT: scripts/** and deploy/** stay narrow (named files, not "
            "the full glob) so a brand-new guard script elsewhere under scripts/ or deploy/ does "
            "not retrigger this lane until a later docs/lambdas/mcp/cdk/tests/.github-workflows "
            "touch reconciles it — the same best-effort convention test_count already runs under "
            "(#2982's own reasoning, restated for a different fact)."
        ),
    ),
    "scripts/generate_adr_index.py": _derived(
        generator="scripts/generate_adr_index.py",
        outputs=("docs/DECISIONS.md",),
        writer="python3 scripts/generate_adr_index.py --apply",
        guard="scripts/generate_adr_index.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=("docs/**",),
        reconciled=True,
        reason="The ADR index table. Staled only by editing DECISIONS.md itself — a docs/** change.",
    ),
    "scripts/incident_log_patterns.py": _derived(
        generator="scripts/incident_log_patterns.py",
        outputs=("docs/INCIDENT_LOG.md",),
        writer="python3 scripts/incident_log_patterns.py --apply",
        guard="scripts/incident_log_patterns.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=("docs/**",),
        reconciled=True,
        reason=(
            "The derived Patterns blocks. #2975 moved the check here from CI/CD's Unit Tests: "
            "a wrap adds rows, touches docs/** only, and so cannot trigger CI/CD at all — the "
            "red always landed on a later, innocent commit. The originating incident for this "
            "whole registry."
        ),
    ),
    "scripts/generate_mcp_tool_catalog.py": _derived(
        generator="scripts/generate_mcp_tool_catalog.py",
        outputs=("docs/MCP_TOOL_CATALOG.md",),
        writer="python3 scripts/generate_mcp_tool_catalog.py",
        guard="scripts/generate_mcp_tool_catalog.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=("mcp/**",),
        reconciled=True,
        reason=(
            "The tool catalog, derived from mcp/registry.py. Had a --check wired into NOTHING "
            "until #2986, and drifted a month behind a timestamp the reconcile bot refreshed "
            "daily (sync_doc_metadata owns its `Total tools:` literal, not its body) — so it "
            "read `Total tools: 76` two lines above `## All 72 Tools`."
        ),
    ),
    "scripts/generate_platform_model.py": _derived(
        generator="scripts/generate_platform_model.py",
        outputs=("model/platform_model.json", "docs/DEPENDENCY_GRAPH.md"),
        writer="python3 scripts/generate_platform_model.py",
        guard="scripts/generate_platform_model.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=(
            "lambdas/**",
            "cdk/**",
            "mcp/**",
            # #3374 R1 — the cost_surface plane AST-reads two registries outside the
            # code trees: the EMF-namespace ledger and the KNOWN_SECRETS set.
            "deploy/emf_namespace_ledger.py",
            "tests/test_secret_references.py",
        ),
        reconciled=True,
        reason=(
            "The #2845 system model. Its only guard was tests/test_platform_model_drift.py, "
            "which sits OUTSIDE the `premerge` marker (measured: `no tests collected (5 "
            "deselected)`) and therefore ran post-merge only — so a lambdas/** PR that staled "
            "the model redded main rather than the PR. Docs CI is the lane: it already triggers "
            "on lambdas/**, cdk/** and mcp/**, and unlike CI/CD's Unit Tests it runs pre-merge "
            "on a pull_request. The pytest stays as the in-suite drift detector."
        ),
    ),
    "scripts/operating_calendar.py": _derived(
        generator="scripts/operating_calendar.py",
        outputs=("docs/OPERATING_CALENDAR.md",),
        writer="python3 scripts/operating_calendar.py --apply",
        guard="scripts/operating_calendar.py --check",
        guard_lane=LANE_DOCS_CI,
        inputs=("scripts/operating_calendar.py",),
        reconciled=False,
        reason=(
            "The #2832 operating-calendar doc, derived from the CALENDAR registry in the "
            "script itself — its ONLY input is its own source, so the docs-ci --check on the "
            "PR that edits the registry forces regeneration in that same PR; there is nothing "
            "left for the post-merge reconcile to heal (reconciled=False is the honest claim). "
            "The time-based dead-man (--due) deliberately lives in the SCHEDULED "
            "operating-calendar.yml workflow, not this lane: an overdue ritual must red the "
            "schedule, never an innocent PR (the #2975 misattribution class)."
        ),
    ),
    # ── Builders: regenerated by a NAMED step, not drift-gated ────────────────
    # Re-running these is a content or deploy decision, not a reconciliation. A drift
    # guard would red on deliberate editorial state. Each entry names the step, because
    # "someone runs it" is exactly how the MCP catalog above went a month stale.
    "scripts/v4_build_game_explained.py": _builder(
        "scripts/v4_build_game_explained.py",
        step="ci-cd.yml run_generators()",
        reason=(
            "Renders /method/game-explained/ from config/character_sheet.json — repo state, so "
            "reconciling every merge is safe and IS the guard. No separate --check needed: the "
            "reconcile job's own dirty-tree assertion catches drift."
        ),
    ),
    "scripts/v4_build_data_sources.py": _builder(
        "scripts/v4_build_data_sources.py",
        step="ci-cd.yml run_generators()",
        reason="Derives site/data/data_sources.json from source_registry.py. Same reconcile-is-the-guard shape.",
    ),
    "scripts/v4_apply_chrome.py": _builder(
        "scripts/v4_apply_chrome.py",
        step="ci-cd.yml run_generators()",
        reason=(
            "Re-flattens shared nav/footer chrome across every v4 page from v4_chrome.py (#1009). "
            "Idempotent over the page set; reconciled every merge."
        ),
    ),
    "scripts/v4_build_methods.py": _builder(
        "scripts/v4_build_methods.py",
        step="deploy/sync_site_to_s3.sh",
        reason=(
            "Renders /method/registry/ from lambdas/experiment/methods_registry.py (#544). Run at "
            "site-deploy time, and additionally exercised end-to-end by tests/test_methods_registry.py "
            "against a fixture — so the generator itself is guarded even though its output is not "
            "drift-compared. NB the deploy step swallows failure with `|| echo skipped`, which keeps "
            "a stale page rather than failing the deploy."
        ),
    ),
    "scripts/v4_build_tone.py": _builder(
        "scripts/v4_build_tone.py",
        step="deploy/sync_site_to_s3.sh / design-sync",
        reason=(
            "Renders /method/tone/ from lambdas/coach/coach_register.py (#1390). tests/qa_manifest.py "
            "marks the page GENERATED so the QA sweep knows not to treat hand edits as authoritative."
        ),
    ),
    "scripts/v4_build_rss.py": _builder(
        "scripts/v4_build_rss.py",
        step="deploy/sync_site_to_s3.sh",
        reason=(
            "Generates site/rss.xml + feed.xml from the live chronicle posts.json. Its input is LIVE "
            "DATA, not repo state, so a repo-tree drift guard could not evaluate it — regenerating at "
            "publish time is the only correct moment."
        ),
    ),
    "scripts/v4_build_cockpit_proof.py": _builder(
        "scripts/v4_build_cockpit_proof.py",
        step="deploy/sync_site_to_s3.sh",
        reason="Bakes the cockpit's static proof block into /cockpit/ (#788) from live data. Same live-input reason as RSS.",
    ),
    "scripts/v4_build_home_proof.py": _builder(
        "scripts/v4_build_home_proof.py",
        step="deploy/sync_site_to_s3.sh",
        reason="Bakes Home's static core + data-driven OG (#1395) from live data. Same live-input reason.",
    ),
    "scripts/v4_build_horizons.py": _builder(
        "scripts/v4_build_horizons.py",
        step="deploy/sync_site_to_s3.sh",
        reason="Generates the Horizons feed page (#1707) from the live horizons partition. Live input.",
    ),
    "scripts/v4_build_evidence.py": _builder(
        "scripts/v4_build_evidence.py",
        step="deploy/sync_site_to_s3.sh",
        reason="Generates the /data/ archive pillars from live records. Live input.",
    ),
    "scripts/v4_build_eyeball.py": _builder(
        "scripts/v4_build_eyeball.py",
        step="manual, per captured round",
        reason="Builds the eyeball-estimate page from a captured round of guesses. The captured round IS the content; re-deriving it later would rewrite the record.",
    ),
    "scripts/v4_build_grade_your_coach.py": _builder(
        "scripts/v4_build_grade_your_coach.py",
        step="manual, per captured round",
        reason="Same captured-round shape as the eyeball page, over a captured set of coach outputs.",
    ),
    "scripts/v4_build_agent_review.py": _builder(
        "scripts/v4_build_agent_review.py",
        step="manual, per review",
        reason="Builds a dated /story/build/ page recording one remediation-agent review. A dated record is by definition not re-derivable.",
    ),
    "scripts/v4_build_mirror.py": _builder(
        "scripts/v4_build_mirror.py",
        step="manual, with gen_mirror_vectors / gen_mirror_distributions",
        reason="Builds the mirror page and its distribution data from a generated vector set. Regenerated with the vectors, not per merge.",
    ),
    "scripts/v4_build_theme_river.py": _builder(
        "scripts/v4_build_theme_river.py",
        step="manual, per corpus pass",
        reason="Builds theme-river data from a corpus analysis run — a deliberate act with a cost, not a reconciliation.",
    ),
    "scripts/v4_build_stack_manifest.py": _builder(
        "scripts/v4_build_stack_manifest.py",
        step="manual, when pricing changes",
        reason=(
            "Builds the stack manifest + config/cost_of_ownership.json. Inputs include hand-priced "
            "judgement fields (ADR-103/144 rent), so a reconcile pass would overwrite human numbers."
        ),
    ),
    "scripts/v4_build_journal.py": _builder(
        "scripts/v4_build_journal.py",
        step="manual, on publish",
        reason="Renders journal posts. Editorial: a post is published when the author runs it, not when a merge happens.",
    ),
    "scripts/v4_vendor_fonts.py": _builder(
        "scripts/v4_vendor_fonts.py",
        step="manual, when the typeface set changes",
        reason="Self-hosts the v4 fonts CSP-safely. Its output is vendored binaries + a css shim; regenerating per merge would churn binaries for nothing.",
    ),
    "scripts/build_brand_assets.py": _builder(
        "scripts/build_brand_assets.py",
        step="manual, when the brand changes",
        reason="Renders logo/OG brand assets into site/assets. A brand change is a design decision (ADR-106 posture), and the output is binary.",
    ),
    "scripts/design_sync_bundle.py": _builder(
        "scripts/design_sync_bundle.py",
        step="the /design-sync skill",
        reason="Exports the v5 design system as a self-contained bundle. Its committed touchpoints (tokens.css, icons.svg) are the design system's own source, edited deliberately.",
    ),
    "scripts/file_backlog_from_manifest.py": _builder(
        "scripts/file_backlog_from_manifest.py",
        step="manual, per review filing run",
        reason="Writes a dated docs/reviews/*_MANIFEST_*.json as the record of one filing run. Dated record, not re-derivable.",
    ),
    "deploy/restart_pipeline.py": _builder(
        "deploy/restart_pipeline.py",
        step="deploy/restart_pipeline.py --apply (an experiment reset)",
        reason=(
            "The ADR-058/077 reset driver. It rewrites config/ and docs/restart/ as part of "
            "re-anchoring the experiment — an event that happens on purpose, a few times a year. "
            "A drift guard here would red continuously between resets by construction."
        ),
    ),
    "deploy/restart_docs_update.py": _builder(
        "deploy/restart_docs_update.py",
        step="deploy/restart_pipeline.py",
        reason="A restart_pipeline stage: regenerates the docs that quote experiment dates. Same reset cadence as its driver.",
    ),
    "deploy/restart_site_copy_sync.py": _builder(
        "deploy/restart_site_copy_sync.py",
        step="deploy/restart_pipeline.py",
        reason="A restart_pipeline stage: regenerates site copy from the current genesis. Same reset cadence.",
    ),
    "deploy/seed_genesis_preregistration.py": _builder(
        "deploy/seed_genesis_preregistration.py",
        step="deploy/restart_pipeline.py",
        reason="Seeds config/user_goals.json pre-registration at genesis (#976). Reset-time, once per cycle.",
    ),
    # ── Excluded: discovery names the path, the script does not own it ────────
    "deploy/build_bundle.py": _excluded(
        "deploy/build_bundle.py",
        reason=(
            "The #781 bundle stager. It READS config/personas.json and friends to stage them into "
            "the zip and WRITES only the zip, which is not a committed artifact. Discovery sees it "
            "because it names committed config paths in a module that also writes."
        ),
    ),
    "deploy/doc_alarm_inventory.py": _excluded(
        "deploy/doc_alarm_inventory.py",
        reason=(
            "Not a standalone generator — a #2649 extraction imported BY sync_doc_metadata.py, "
            "which owns docs/MONITORING.md and carries the DERIVED entry above. Registering it "
            "separately would claim two owners for one artifact."
        ),
    ),
    "deploy/sync_constants_from_config.py": _excluded(
        "deploy/sync_constants_from_config.py",
        reason=(
            "Regenerates lambdas/common/constants.py, which is NOT under an artifact root. It only "
            "READS config/user_goals.json. Discovery sees the read because the module also writes."
        ),
    ),
}


# ── The scanner's blind spot, stated ──────────────────────────────────────────
#
# These five ARE real generators and ARE registered above, but `discover_generators()`
# cannot find them — every one writes through a **computed** output path
# (`(out_dir / "index.html").write_text(...)`, or a loop over globbed files), so no
# committed literal appears anywhere in the module.
#
# That is one coherent limitation, and it is written down rather than papered over,
# because it bounds what the discovery half of this guard can promise: a new generator
# that computes its output path will NOT be caught. The registry half still catches it the
# moment anyone declares it. Closing the gap needs interprocedural resolution of `out_dir`,
# which is a real piece of work and is scoped as its own story rather than faked here.
#
# The set is shrink-only in spirit: an entry leaves when discovery learns to see it.
DISCOVERY_BLIND: dict[str, str] = {
    "scripts/v4_apply_chrome.py": "writes `open(path, 'w')` in a loop over globbed site/*.html — no literal target",
    "scripts/v4_build_methods.py": "writes `(out_dir / 'index.html')`; out_dir is a function-local",
    "scripts/v4_build_tone.py": "writes `(out_dir / 'index.html')`; out_dir is a function-local",
    "scripts/v4_build_agent_review.py": "writes `(out_dir / 'index.html')` and a sibling json; out_dir is a function-local",
    "scripts/file_backlog_from_manifest.py": "writes a DATED docs/reviews/ filename built at runtime — unresolvable by construction",
}


# ── Discovery ─────────────────────────────────────────────────────────────────
#
# Two filters, and BOTH are load-bearing. Dropping either produced a useless scan when
# this was first written: a permissive version found 59 "generators", most of them
# `check_*.py` scripts that only READ a site/ path, and report writers dumping transient
# `docs/restart/_*.txt` files that are not committed at all.
#
#   1. the path must be the TARGET of a write call, resolved through module-level
#      constants — not merely a string the module mentions;
#   2. the path must be GIT-TRACKED — "committed artifact" is a literal claim, and the
#      index is the only honest way to check it.


def _flatten_div(node: ast.AST) -> list[str] | None:
    """`ROOT / "docs" / "X.md"` → ['docs', 'X.md']; anything else → None."""
    parts: list[str] = []
    cur = node
    while isinstance(cur, ast.BinOp) and isinstance(cur.op, ast.Div):
        if not (isinstance(cur.right, ast.Constant) and isinstance(cur.right.value, str)):
            return None
        parts.append(cur.right.value)
        cur = cur.left
    if not parts:
        return None
    parts.reverse()
    return parts


def _resolve_path_expr(node: ast.AST, consts: dict[str, str]) -> str | None:
    """A relative artifact path for a path expression, or None."""
    if isinstance(node, ast.Name):
        return consts.get(node.id)
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value if "/" in node.value else None
    parts = _flatten_div(node)
    if parts:
        # A `/`-chain rooted at a Name we know resolves through it; one rooted at
        # ROOT/REPO_ROOT starts at its first literal segment.
        base = node
        while isinstance(base, ast.BinOp):
            base = base.left
        if isinstance(base, ast.Name) and base.id in consts:
            return "/".join([consts[base.id]] + parts)
        return "/".join(parts)
    return None


def _module_constants(tree: ast.AST) -> dict[str, str]:
    """Module-level `NAME = <path expr>` bindings, as relative paths."""
    consts: dict[str, str] = {}
    for node in getattr(tree, "body", []):
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        parts = _flatten_div(node.value)
        if parts:
            consts[target.id] = "/".join(parts)
        elif isinstance(node.value, ast.Constant) and isinstance(node.value.value, str) and "/" in node.value.value:
            consts[target.id] = node.value.value
    return consts


def _has_write_call(tree: ast.AST) -> bool:
    """Does this module perform a file write at all? AST-only — a substring check for
    `open(` matches every READ, which is how a first draft of this scan turned 9 real
    generators into 59 candidates, most of them `check_*.py` scripts."""
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        fn = node.func
        if isinstance(fn, ast.Attribute) and fn.attr in ("write_text", "write_bytes", "writelines"):
            return True
        if isinstance(fn, ast.Attribute) and fn.attr == "dump" and isinstance(fn.value, ast.Name) and fn.value.id == "json":
            return True
        if isinstance(fn, ast.Name) and fn.id == "open":
            mode = node.args[1] if len(node.args) > 1 else None
            mode_val = mode.value if isinstance(mode, ast.Constant) else None
            for kw in node.keywords:
                if kw.arg == "mode" and isinstance(kw.value, ast.Constant):
                    mode_val = kw.value.value
            if isinstance(mode_val, str) and ("w" in mode_val or "a" in mode_val or "x" in mode_val):
                return True
    return False


def _named_paths(tree: ast.AST) -> set[str]:
    """Every artifact-root-relative path this module names, however it names it.

    Deliberately WIDER than "the resolved target of a write call". The precise version
    missed `deploy/sync_doc_metadata.py` — the largest generator in the repo — because it
    writes through a loop over computed paths, and it missed the whole `v4_build_*` family
    for the same reason. Under-discovery is the failure mode this registry exists to
    prevent (an unclassified generator is invisible forever); over-discovery costs one
    BUILDER/EXCLUDED line with a reason. So the write-call check gates WHETHER a module is a
    candidate, and this supplies WHICH artifacts to attribute to it.
    """
    consts = _module_constants(tree)
    out: set[str] = set(consts.values())
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if "/" in node.value and not node.value.startswith(("http", "//")):
                out.add(node.value)
        else:
            parts = _flatten_div(node)
            if parts:
                out.add("/".join(parts))
    return {p for p in out if p.split("/")[0] in ARTIFACT_ROOTS}


def _tracked_paths(repo: str = REPO) -> frozenset[str]:
    """Every git-tracked path under the artifact roots. Cached per process."""
    global _TRACKED_CACHE
    if _TRACKED_CACHE is None:
        import subprocess

        out = subprocess.run(
            ["git", "-C", repo, "ls-files", "--", *ARTIFACT_ROOTS],
            capture_output=True,
            text=True,
            timeout=60,
        )
        _TRACKED_CACHE = frozenset(ln.strip() for ln in out.stdout.splitlines() if ln.strip())
    return _TRACKED_CACHE


_TRACKED_CACHE: frozenset[str] | None = None


def discover_generators(repo: str = REPO) -> dict[str, tuple[str, ...]]:
    """`{rel_script_path: (artifact_path, …)}` for every script that writes committed output.

    NOT hand-listed — the point is that a new generator must be classified rather than
    silently added. `deploy/` is scanned alongside `scripts/` because sync_doc_metadata,
    the biggest generator in the repo, lives there.
    """
    tracked = _tracked_paths(repo)
    out: dict[str, tuple[str, ...]] = {}
    for top in GENERATOR_DIRS:
        d = os.path.join(repo, top)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".py"):
                continue
            rel = f"{top}/{name}"
            try:
                with open(os.path.join(d, name), encoding="utf-8") as fh:
                    tree = ast.parse(fh.read())
            except (OSError, SyntaxError):
                continue
            if not _has_write_call(tree):
                continue
            committed = sorted(p for p in _named_paths(tree) if p in tracked)
            if committed:
                out[rel] = tuple(committed)
    return out


# ── Lane resolution ───────────────────────────────────────────────────────────
def lane_trigger_paths(lane: str, repo: str = REPO) -> list[str]:
    """The union of a lane workflow's push + pull_request path globs."""
    import yaml

    path = os.path.join(repo, _LANE_WORKFLOW[lane])
    with open(path, encoding="utf-8") as fh:
        spec = yaml.safe_load(fh)
    # PyYAML resolves the bare key `on:` to the boolean True (YAML 1.1 truthiness).
    triggers = spec.get("on", spec.get(True)) or {}
    globs: list[str] = []
    for event in ("push", "pull_request"):
        globs += (triggers.get(event) or {}).get("paths") or []
    return globs


def lane_covers(input_glob: str, trigger_globs: list[str]) -> bool:
    """Does some trigger glob fire on a change matching `input_glob`?

    Compared glob-to-glob, not path-to-glob: the registry declares an input as a pattern
    ('lambdas/**'), and the question is whether the lane's filter admits that pattern.
    A trigger of `lambdas/**` covers an input of `lambdas/**` and of `lambdas/web/x.py`;
    an input of `lambdas/**` is NOT covered by a trigger of `lambdas/web/x.py`.
    """
    probe = input_glob.replace("/**", "/_probe_/x.py").replace("*", "x")
    for g in trigger_globs:
        if g == input_glob:
            return True
        pattern = g.replace("/**", "/*")
        if fnmatch.fnmatch(probe, pattern) or fnmatch.fnmatch(probe, g.replace("**", "*")):
            return True
    return False


def reconcile_whitelist_re(repo: str = REPO) -> "re.Pattern[str]":
    """The compiled generator-output whitelist from ci-cd.yml's reconcile step.

    #3012's live lesson: adding a generator to run_generators() without adding its
    output to ALLOWED makes the reconcile job refuse-and-red on the NEXT innocent
    merge — the lane had the writer but not the write.
    """
    with open(os.path.join(repo, ".github", "workflows", "ci-cd.yml"), encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"ALLOWED='([^']+)'", text)
    if not m:
        raise AssertionError("ci-cd.yml no longer defines the reconcile ALLOWED whitelist")
    return re.compile(m.group(1))


def run_generators_commands(repo: str = REPO) -> list[str]:
    """The command lines inside ci-cd.yml's `run_generators()` shell function."""
    with open(os.path.join(repo, ".github", "workflows", "ci-cd.yml"), encoding="utf-8") as fh:
        text = fh.read()
    start = text.index("run_generators() {")
    end = text.index("\n          }", start)
    return [ln.strip() for ln in text[start:end].splitlines() if "python3" in ln]
