"""tests/pair_seam_residue.py — the #2847 must-agree-seam ledger (box 4, epic #2842).

The dated, shrink-only companion to ``tests/pair_seam_guard_lib.py``, in the shape
``tests/conformance_residue.py`` (#2844) and ``tests/lambda_enrollment_ledger.py``
(#2846) established: **an entry may only ever come OUT.** A row the sweep no longer
finds is a red, so the ratchet is forced to count down; a new seam is a red, never a
new baseline row you add to make the red go away.

Two dicts, and the difference between them is the whole point:

``PAIR_SEAM_RESIDUE`` — the must-agree seam census as it stood on the seed date.
    Reasonless by construction and honestly so: nobody can retroactively argue 286
    seams, and PR #3169 was right to refuse "299 rows of ceremony written by a model
    that cannot ground a single one of them". This is a PIN, not a debt claim —
    contracting all of these is neither the goal nor proportionate (ADR-103/144).
    Frozen: every value is the seed date, and the guard asserts that, so a new seam
    cannot be smuggled in here with a later date. Rows leave when the seam
    disappears or when a ``PairContract`` covers it.

``PAIR_SEAM_DECISIONS`` — seams born AFTER the seed date that are deliberately
    not contracted. ``(date, reason)``, and the reason has to be an argument, not a
    label: the guard enforces a 40-character floor, the same bar #2846 puts on its
    own dated exemptions. This dict starts EMPTY on purpose — the first row someone
    writes is the first time this instrument has actually cost anything, and that
    cost is the point of standing rule 3.

Seeded 2026-08-25 by ``python3 tests/pair_seam_guard_lib.py`` (286 seams over 39
partitions), the sweep's own output — no hand-typed list. Three seams the six
enrolled #2847 contracts already cover are absent by construction:
``computed_metrics`` <- daily_metrics_compute (write), ``adaptive_mode`` <-
adaptive_mode_lambda (write), ``engagement_state`` -> site_api_freshness (read).

THE NAMES ARE LOAD-BEARING (measured in CI, 2026-08-25)
--------------------------------------------------------
The first draft called these ``PAIR_SEAM_BASELINE`` / ``PAIR_SEAM_EXEMPTIONS``, and
the #3000 doc literal moved 557 -> 844 declared gates. ``scripts/gate_census.py``'s
``_REGISTRY_NAME`` matches ``.*_BASELINE`` and ``.*_EXEMPT.*``, so it enumerated all
286 rows as 286 SEPARATE gates and, because its exemption-data branch tests
``(root / entry).exists()``, flagged every one of them ``stale-exemption`` — the
keys are composite seam identities that merely CONTAIN a path, not paths. One gate
with 286 dated rows was being reported as 286 gates and 286 false leads.

Renamed to sit where its two siblings already sit: ``CONFORMANCE_RESIDUE`` (#2844)
and ``RAW_CONSTRUCTIONS``/``DEPLOY_REGISTRATION`` (#2846) do not match that regex
either, and they are the same kind of object. This is consistency, not evasion —
the census's composite-key blind spot is real and worth its own look, but silently
inflating the platform's gate count by 51% to make the point would be the wrong way
to raise it. Do not rename these back without re-measuring the census.
"""

SEED_DATE = "2026-08-25"

#: The grandfathered census. FROZEN at SEED_DATE — see the module docstring.
PAIR_SEAM_RESIDUE: dict[str, str] = {
    "adaptive_mode::mcp/tools_coach_checkin.py::read": SEED_DATE,
    "adaptive_mode::mcp/tools_reading.py::read": SEED_DATE,
    "ai_analysis::lambdas/compute/state_of_matthew_lambda.py::read": SEED_DATE,
    "ai_analysis::lambdas/emails/chronicle_data.py::read": SEED_DATE,
    "ai_analysis::lambdas/operational/coherence_sentinel_lambda.py::read": SEED_DATE,
    "ai_analysis::lambdas/web/site_api_coach_narrative.py::read": SEED_DATE,
    "ai_analysis::lambdas/web/site_api_coach_stance.py::read": SEED_DATE,
    "anomalies::lambdas/emails/anomaly_detector_lambda.py::write": SEED_DATE,
    "anomalies::lambdas/emails/daily_brief_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/emails/evening_nudge_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/emails/freshness_checker_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/emails/freshness_checker_lambda.py::write": SEED_DATE,
    "apple_health::lambdas/ingestion/health_auto_export_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/ingestion/health_auto_export_lambda.py::write": SEED_DATE,
    "apple_health::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/operational/qa_smoke_lambda.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_biomarkers.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_body.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_fingerprint.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_freshness.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_journey.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_meals.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_mind.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_physical.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_pulse.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_rollups.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_sleep.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_api_training.py::read": SEED_DATE,
    "apple_health::lambdas/web/site_stats_refresh_lambda.py::read": SEED_DATE,
    "apple_health::mcp/tools_cgm.py::read": SEED_DATE,
    "apple_health::mcp/tools_health.py::read": SEED_DATE,
    "apple_health::mcp/tools_lifestyle.py::read": SEED_DATE,
    "challenges::lambdas/compute/character_sheet_lambda.py::write": SEED_DATE,
    "challenges::lambdas/intelligence/challenge_generator_lambda.py::read": SEED_DATE,
    "challenges::lambdas/intelligence/challenge_generator_lambda.py::write": SEED_DATE,
    "challenges::lambdas/web/site_api_social_challenges.py::read": SEED_DATE,
    "challenges::lambdas/web/site_api_social_challenges.py::write": SEED_DATE,
    "chronicle::lambdas/content/site_writer.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_approve_lambda.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_approve_lambda.py::write": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_data.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_email_sender_lambda.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_email_sender_lambda.py::write": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_podcast_lambda.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_store.py::read": SEED_DATE,
    "chronicle::lambdas/emails/chronicle_store.py::write": SEED_DATE,
    "chronicle::lambdas/emails/coach_panel_podcast_lambda.py::read": SEED_DATE,
    "chronicle::lambdas/web/ask_retrieval.py::read": SEED_DATE,
    "chronicle::lambdas/web/site_api_coach_narrative.py::read": SEED_DATE,
    "coach_actions::lambdas/intelligence/intelligence_common.py::write": SEED_DATE,
    "coach_actions::lambdas/web/site_api_lambda.py::read": SEED_DATE,
    "coach_thread::lambdas/training/training_notes.py::write": SEED_DATE,
    "coach_thread::mcp/tools_coach_intelligence.py::read": SEED_DATE,
    "computed_insights::lambdas/compute/daily_insight_compute_lambda.py::read": SEED_DATE,
    "computed_insights::lambdas/compute/daily_insight_compute_lambda.py::write": SEED_DATE,
    "computed_insights::lambdas/compute/weekly_signal_lambda.py::read": SEED_DATE,
    "computed_insights::lambdas/emails/daily_brief_lambda.py::write": SEED_DATE,
    "computed_metrics::lambdas/ai/ai_calls.py::read": SEED_DATE,
    "computed_metrics::lambdas/ai/ai_output_validator.py::read": SEED_DATE,
    "computed_metrics::lambdas/compute/acwr_compute_lambda.py::write": SEED_DATE,
    "computed_metrics::lambdas/emails/anomaly_detector_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/emails/coach_nudge_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/emails/daily_debrief_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/emails/weekly_digest_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/intelligence/field_notes_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/operational/coherence_sentinel_lambda.py::read": SEED_DATE,
    "computed_metrics::lambdas/web/site_api_discovery.py::read": SEED_DATE,
    "computed_metrics::lambdas/web/site_api_habits.py::read": SEED_DATE,
    "computed_metrics::mcp/tools_health.py::read": SEED_DATE,
    "computed_metrics::mcp/tools_training.py::read": SEED_DATE,
    "day_grade::lambdas/compute/adaptive_mode_lambda.py::read": SEED_DATE,
    "day_grade::lambdas/compute/daily_metrics_compute_lambda.py::write": SEED_DATE,
    "day_grade::lambdas/compute/failure_pattern_compute_lambda.py::read": SEED_DATE,
    "day_grade::lambdas/emails/daily_brief_lambda.py::write": SEED_DATE,
    "day_grade::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "day_grade::lambdas/operational/coherence_sentinel_lambda.py::read": SEED_DATE,
    "diary_claims::lambdas/web/site_api_diary.py::read": SEED_DATE,
    "diary_claims::mcp/tools_coach_intelligence.py::read": SEED_DATE,
    "diary_claims::mcp/tools_journal.py::write": SEED_DATE,
    "diary_reactions::lambdas/coach/coach_diary_reaction.py::write": SEED_DATE,
    "diary_reactions::lambdas/web/site_api_thirdwall.py::read": SEED_DATE,
    "email_log::lambdas/common/send_ledger.py::read": SEED_DATE,
    "email_log::lambdas/compute/weekly_signal_lambda.py::read": SEED_DATE,
    "email_log::lambdas/compute/weekly_signal_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/ai_review_pack_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/ai_review_pack_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/anomaly_detector_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/anomaly_detector_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/between_chronicle_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/between_chronicle_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/chronicle_email_sender_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/chronicle_store.py::write": SEED_DATE,
    "email_log::lambdas/emails/daily_brief_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/daily_brief_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/evening_nudge_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/evening_nudge_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/insight_email_parser_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/insight_email_parser_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/milestone_digest_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/milestone_digest_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/monday_compass_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/nutrition_review_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/nutrition_review_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/partner_email_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/partner_email_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/weekly_digest_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/weekly_digest_lambda.py::write": SEED_DATE,
    "email_log::lambdas/emails/weekly_plate_lambda.py::read": SEED_DATE,
    "email_log::lambdas/emails/weekly_plate_lambda.py::write": SEED_DATE,
    "engagement_state::lambdas/coach/coach_chat_grounding.py::read": SEED_DATE,
    "engagement_state::lambdas/compute/adaptive_mode_lambda.py::write": SEED_DATE,
    "engagement_state::lambdas/compute/character_sheet_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/compute/state_of_matthew_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/coach_panel_podcast_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/daily_brief_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/daily_debrief_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/monthly_digest_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/emails/weekly_digest_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "engagement_state::lambdas/web/site_api_ai_context.py::read": SEED_DATE,
    "engagement_state::mcp/tools_coach_checkin.py::read": SEED_DATE,
    "experiments::lambdas/compute/daily_insight_compute_lambda.py::read": SEED_DATE,
    "experiments::lambdas/emails/chronicle_data.py::read": SEED_DATE,
    "experiments::lambdas/emails/coach_nudge_lambda.py::read": SEED_DATE,
    "experiments::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "experiments::lambdas/web/site_api_discovery.py::read": SEED_DATE,
    "experiments::lambdas/web/site_api_journey.py::read": SEED_DATE,
    "experiments::lambdas/web/site_api_protocols.py::read": SEED_DATE,
    "experiments::lambdas/web/site_api_rollups.py::read": SEED_DATE,
    "experiments::mcp/tools_lifestyle.py::write": SEED_DATE,
    "field_notes::lambdas/emails/chronicle_data.py::read": SEED_DATE,
    "field_notes::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "field_notes::lambdas/intelligence/field_notes_lambda.py::read": SEED_DATE,
    "field_notes::lambdas/intelligence/field_notes_lambda.py::write": SEED_DATE,
    "field_notes::lambdas/web/site_api_thirdwall.py::read": SEED_DATE,
    "field_notes::mcp/tools_lifestyle.py::read": SEED_DATE,
    "field_notes::mcp/tools_lifestyle.py::write": SEED_DATE,
    "flourishing::lambdas/content/theme_river.py::read": SEED_DATE,
    "flourishing::lambdas/health/flourishing.py::write": SEED_DATE,
    "flourishing::lambdas/web/site_api_fulfillment.py::read": SEED_DATE,
    "flourishing::mcp/tools_journal.py::read": SEED_DATE,
    "food_delivery::lambdas/common/digest_utils.py::read": SEED_DATE,
    "food_delivery::lambdas/ingestion/food_delivery_lambda.py::write": SEED_DATE,
    "food_delivery::lambdas/web/site_api_meals.py::read": SEED_DATE,
    "food_delivery::lambdas/web/site_api_nutrition.py::read": SEED_DATE,
    "forecast::lambdas/ai/ai_calls.py::read": SEED_DATE,
    "forecast::lambdas/compute/forecast_engine_lambda.py::write": SEED_DATE,
    "forecast::lambdas/compute/state_of_matthew_lambda.py::read": SEED_DATE,
    "forecast::lambdas/web/site_api_foresight.py::read": SEED_DATE,
    "habit_scores::lambdas/coach/coach_prediction_evaluator.py::read": SEED_DATE,
    "habit_scores::lambdas/compute/adaptive_mode_lambda.py::read": SEED_DATE,
    "habit_scores::lambdas/compute/daily_metrics_compute_lambda.py::write": SEED_DATE,
    "habit_scores::lambdas/compute/failure_pattern_compute_lambda.py::read": SEED_DATE,
    "habit_scores::lambdas/emails/daily_brief_lambda.py::write": SEED_DATE,
    "habit_scores::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "habit_scores::lambdas/web/site_api_ai_context.py::read": SEED_DATE,
    "habit_scores::lambdas/web/site_api_habits.py::read": SEED_DATE,
    "habit_scores::lambdas/web/site_api_mind.py::read": SEED_DATE,
    "health_check::lambdas/operational/pipeline_health_check_lambda.py::write": SEED_DATE,
    "health_check::lambdas/web/site_api_status.py::read": SEED_DATE,
    "hevy::lambdas/compute/daily_metrics_compute_lambda.py::read": SEED_DATE,
    "hevy::lambdas/content/vacation_fund.py::read": SEED_DATE,
    "hevy::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "hevy::lambdas/training/hevy_common.py::write": SEED_DATE,
    "hevy::lambdas/training/training_notes.py::read": SEED_DATE,
    "hevy::lambdas/web/site_api_pulse.py::read": SEED_DATE,
    "hevy::lambdas/web/site_api_training.py::read": SEED_DATE,
    "hevy::mcp/tools_hevy_routine.py::read": SEED_DATE,
    "hevy::mcp/tools_strength.py::read": SEED_DATE,
    "hevy::mcp/tools_training_notes.py::read": SEED_DATE,
    "hypotheses::lambdas/compute/hypothesis_engine_lambda.py::write": SEED_DATE,
    "hypotheses::lambdas/compute/state_of_matthew_lambda.py::read": SEED_DATE,
    "hypotheses::lambdas/intelligence/challenge_generator_lambda.py::read": SEED_DATE,
    "hypotheses::mcp/tools_lifestyle.py::read": SEED_DATE,
    "insights::lambdas/emails/insight_email_parser_lambda.py::write": SEED_DATE,
    "insights::lambdas/web/site_api_ledger.py::read": SEED_DATE,
    "insights::mcp/tools_lifestyle.py::read": SEED_DATE,
    "insights::mcp/tools_lifestyle.py::write": SEED_DATE,
    "journal_quotes::lambdas/web/site_api_diary.py::read": SEED_DATE,
    "journal_quotes::lambdas/web/site_api_thirdwall.py::read": SEED_DATE,
    "journal_quotes::mcp/tools_journal.py::write": SEED_DATE,
    "measurements::lambdas/ingestion/measurements_ingestion_lambda.py::write": SEED_DATE,
    "measurements::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "measurements::lambdas/web/site_api_physical.py::read": SEED_DATE,
    "notion::lambdas/compute/adaptive_mode_lambda.py::read": SEED_DATE,
    "notion::lambdas/compute/circadian_compliance_lambda.py::read": SEED_DATE,
    "notion::lambdas/compute/daily_insight_compute_lambda.py::read": SEED_DATE,
    "notion::lambdas/compute/daily_metrics_compute_lambda.py::read": SEED_DATE,
    "notion::lambdas/emails/evening_nudge_lambda.py::read": SEED_DATE,
    "notion::lambdas/emails/freshness_checker_lambda.py::read": SEED_DATE,
    "notion::lambdas/emails/freshness_checker_lambda.py::write": SEED_DATE,
    "notion::lambdas/ingestion/notion_lambda.py::read": SEED_DATE,
    "notion::lambdas/ingestion/notion_lambda.py::write": SEED_DATE,
    "notion::lambdas/intelligence/field_notes_lambda.py::read": SEED_DATE,
    "notion::lambdas/intelligence/intelligence_common.py::read": SEED_DATE,
    "notion::lambdas/web/site_api_fulfillment.py::read": SEED_DATE,
    "notion::lambdas/web/site_api_mind.py::read": SEED_DATE,
    "notion::lambdas/web/site_api_pulse.py::read": SEED_DATE,
    "notion::mcp/tools_journal.py::read": SEED_DATE,
    "notion::mcp/tools_social_connection.py::read": SEED_DATE,
    "panelcast::lambdas/emails/coach_panel_podcast_lambda.py::read": SEED_DATE,
    "panelcast::lambdas/emails/coach_panel_podcast_lambda.py::write": SEED_DATE,
    "panelcast::lambdas/emails/podcast_script_v2.py::read": SEED_DATE,
    "panelcast::lambdas/emails/podcast_script_v2.py::write": SEED_DATE,
    "panelcast::lambdas/web/site_api_coach_ledger.py::read": SEED_DATE,
    "platform_memory::lambdas/compute/daily_insight_compute_lambda.py::read": SEED_DATE,
    "platform_memory::lambdas/compute/daily_insight_compute_lambda.py::write": SEED_DATE,
    "platform_memory::lambdas/compute/failure_pattern_compute_lambda.py::write": SEED_DATE,
    "platform_memory::lambdas/compute/hypothesis_engine_lambda.py::write": SEED_DATE,
    "platform_memory::lambdas/emails/weekly_plate_lambda.py::read": SEED_DATE,
    "platform_memory::lambdas/emails/weekly_plate_lambda.py::write": SEED_DATE,
    "routine_index::lambdas/training/routine_repo.py::write": SEED_DATE,
    "routine_index::lambdas/training/routine_title.py::read": SEED_DATE,
    "routine_index::lambdas/web/site_api_protocols.py::read": SEED_DATE,
    "sick_days::lambdas/health/sick_day_checker.py::read": SEED_DATE,
    "sick_days::lambdas/health/sick_day_checker.py::write": SEED_DATE,
    "sick_days::mcp/tools_sick_days.py::read": SEED_DATE,
    "sick_days::mcp/tools_sick_days.py::write": SEED_DATE,
    "strava::lambdas/content/vacation_fund.py::read": SEED_DATE,
    "strava::lambdas/emails/monthly_digest_lambda.py::read": SEED_DATE,
    "strava::lambdas/ingestion/enrichment_lambda.py::write": SEED_DATE,
    "strava::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "strava::lambdas/intelligence/intelligence_common.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_autonomic.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_nutrition.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_physical.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_pulse.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_training.py::read": SEED_DATE,
    "strava::lambdas/web/site_api_vitals_depth.py::read": SEED_DATE,
    "strava::lambdas/web/site_stats_refresh_lambda.py::read": SEED_DATE,
    "strava::mcp/tools_benchmark.py::read": SEED_DATE,
    "strava::mcp/tools_correlation.py::read": SEED_DATE,
    "strava::mcp/tools_health.py::read": SEED_DATE,
    "strava::mcp/tools_nutrition.py::read": SEED_DATE,
    "strava::mcp/tools_training.py::read": SEED_DATE,
    "subscribers::lambdas/emails/weekly_digest_lambda.py::read": SEED_DATE,
    "subscribers::lambdas/operational/canary_lambda.py::read": SEED_DATE,
    "subscribers::lambdas/operational/canary_lambda.py::write": SEED_DATE,
    "subscribers::lambdas/operational/delete_user_data_lambda.py::read": SEED_DATE,
    "subscribers::lambdas/operational/delete_user_data_lambda.py::write": SEED_DATE,
    "subscribers::lambdas/web/email_subscriber_lambda.py::read": SEED_DATE,
    "subscribers::lambdas/web/email_subscriber_lambda.py::write": SEED_DATE,
    "subscribers::lambdas/web/site_api_social.py::read": SEED_DATE,
    "subscribers::lambdas/web/site_api_social_engage.py::read": SEED_DATE,
    "subscribers::lambdas/web/site_api_social_ladder.py::read": SEED_DATE,
    "subscribers::lambdas/web/subscriber_onboarding_lambda.py::read": SEED_DATE,
    "supplements::lambdas/ingestion/habitify_lambda.py::write": SEED_DATE,
    "supplements::lambdas/web/site_api_protocols.py::read": SEED_DATE,
    "training_notes::lambdas/training/training_notes_llm.py::write": SEED_DATE,
    "training_notes::mcp/tools_training_notes.py::read": SEED_DATE,
    "weekly_correlations::lambdas/compute/daily_insight_compute_lambda.py::read": SEED_DATE,
    "weekly_correlations::lambdas/compute/weekly_correlation_compute_lambda.py::write": SEED_DATE,
    "weekly_correlations::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "weekly_correlations::lambdas/web/site_api_ai_context.py::read": SEED_DATE,
    "weekly_correlations::lambdas/web/site_api_discovery.py::read": SEED_DATE,
    "weekly_correlations::lambdas/web/site_api_journey.py::read": SEED_DATE,
    "weekly_correlations::lambdas/web/site_api_ledger.py::read": SEED_DATE,
    "what_changed::lambdas/compute/weekly_correlation_compute_lambda.py::write": SEED_DATE,
    "what_changed::lambdas/emails/between_chronicle_lambda.py::read": SEED_DATE,
    "what_changed::lambdas/web/site_api_ai_context.py::read": SEED_DATE,
    "what_changed::lambdas/web/site_api_ledger.py::read": SEED_DATE,
    "whoop::lambdas/coach/intake_response.py::read": SEED_DATE,
    "whoop::lambdas/compute/failure_pattern_compute_lambda.py::read": SEED_DATE,
    "whoop::lambdas/emails/monday_compass_lambda.py::read": SEED_DATE,
    "whoop::lambdas/ingestion/enrichment_lambda.py::read": SEED_DATE,
    "whoop::lambdas/ingestion/whoop_lambda.py::write": SEED_DATE,
    "whoop::lambdas/intelligence/ai_expert_analyzer_lambda.py::read": SEED_DATE,
    "whoop::lambdas/operational/hevy_restamp_lambda.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_autonomic.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_body.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_fingerprint.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_freshness.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_lambda.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_nutrition.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_pulse.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_rollups.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_sleep.py::read": SEED_DATE,
    "whoop::lambdas/web/site_api_training.py::read": SEED_DATE,
    "whoop::mcp/tools_health.py::read": SEED_DATE,
    "whoop::mcp/tools_hevy_routine.py::read": SEED_DATE,
    "whoop::mcp/tools_training.py::read": SEED_DATE,
}

#: Seams born after SEED_DATE that are deliberately not contracted: (date, reason).
#: The reason must be an argument (40-char floor, enforced by the guard).
PAIR_SEAM_DECISIONS: dict[str, tuple[str, str]] = {}

__all__ = ["PAIR_SEAM_RESIDUE", "PAIR_SEAM_DECISIONS", "SEED_DATE"]
