"""tests/test_derived_artifact_registry_2986.py — epic #2986's derivation guard.

The registry (`tests/derived_artifact_registry.py`) declares, per derived artifact:
generator · outputs · writer · guard · **the lane that guard runs in**. This file is the
guard over the registry, in both directions, plus the assertion the three originating
incidents each failed in a different place:

    a DERIVED artifact's guard must run in a lane its INPUTS trigger.

That is the #2975 rule generalized. `incident_log_patterns`' guard ran in CI/CD while its
input was `docs/**`; `generate_platform_model`'s guard runs in CI/CD but outside the
`premerge` marker; `generate_mcp_tool_catalog`'s guard ran nowhere at all and its output
drifted a month behind a timestamp the reconcile bot refreshed daily.

WHY THE LANE AND NOT JUST "IS THERE A GUARD". "Is there a guard?" was already YES for two
of the three. The question that separated a working guard from a misattributing one was
*which lane*, and that is not a property of the guard — it is a property of the workflow's
path filter. So the lane is declared and then CHECKED against the workflow, never inferred.
"""

from __future__ import annotations

import os
import sys

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

import derived_artifact_registry as reg  # noqa: E402

DISCOVERED = reg.discover_generators()
DERIVED_ENTRIES = {k: v for k, v in reg.ARTIFACTS.items() if v["decision"] == reg.DERIVED}


# ── Both directions over the registry ────────────────────────────────────────


def test_every_discovered_generator_is_classified():
    """A NEW script writing a committed artifact must be classified — DERIVED, BUILDER, or
    EXCLUDED — before it can merge. The alternative is what this epic was filed for: a
    generator nobody has an opinion about, drifting silently."""
    missing = sorted(set(DISCOVERED) - set(reg.ARTIFACTS))
    assert not missing, (
        f"{len(missing)} generator(s) write a committed artifact and are not in ARTIFACTS: {missing}. "
        "Classify each in tests/derived_artifact_registry.py — DERIVED (drift-gated), "
        "BUILDER (regenerated by a named step), or EXCLUDED (does not own the path)."
    )


def test_the_registry_does_not_rot():
    """Every entry still resolves to a real discovered generator, or is an acknowledged
    scanner blind spot. Without this the registry decays into a hand-list describing
    scripts that no longer exist — which is the failure mode a registry is supposed to end."""
    unmatched = set(reg.ARTIFACTS) - set(DISCOVERED)
    unexplained = sorted(unmatched - set(reg.DISCOVERY_BLIND))
    assert not unexplained, (
        f"registry entries matching no discovered generator and not listed in DISCOVERY_BLIND: {unexplained}. "
        "Either the script was deleted (drop the entry) or discovery cannot see it (add it to "
        "DISCOVERY_BLIND with the reason)."
    )
    stale_blind = sorted(set(reg.DISCOVERY_BLIND) & set(DISCOVERED))
    assert not stale_blind, (
        f"DISCOVERY_BLIND still lists {stale_blind}, but discovery now FINDS them — remove the "
        "entries. The blind list is shrink-only; leaving a solved entry in it overstates the "
        "scanner's limits and hides that it improved."
    )


def test_every_blind_entry_is_registered():
    """DISCOVERY_BLIND is a statement about the SCANNER, not a second registry. An entry
    there that is not in ARTIFACTS would be an artifact tracked nowhere."""
    orphans = sorted(set(reg.DISCOVERY_BLIND) - set(reg.ARTIFACTS))
    assert not orphans, f"DISCOVERY_BLIND names {orphans}, which have no ARTIFACTS entry"


def test_the_scan_is_not_vacuous():
    """A discovery returning nothing would make the first assertion trivially true, and
    read as 'no unclassified generators'. Zero is never the right answer for this repo."""
    assert len(DISCOVERED) > 15, f"discovery found only {len(DISCOVERED)} generators — the scan is broken, not the repo"
    assert DERIVED_ENTRIES, "no DERIVED artifacts registered — the registry describes nothing that can drift"
    roots = {p.split("/")[0] for paths in DISCOVERED.values() for p in paths}
    assert len(roots) >= 2, f"every discovered artifact sits under one root ({roots}) — the scan is narrower than it looks"


# ── Shape ────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("name", sorted(reg.ARTIFACTS))
def test_entry_shape(name):
    entry = reg.ARTIFACTS[name]
    assert entry["decision"] in reg.VALID_DECISIONS, f"{name}: unknown decision {entry['decision']!r}"
    assert entry["generator"] == name, f"{name}: generator field disagrees with its key"
    # A reason that could be pasted onto any other entry records that nobody looked
    # (the #2056 lesson). Length is a weak proxy, but a real one — the reasons that
    # rotted in past registries were all under a line.
    assert len(entry["reason"]) >= 60, f"{name}: reason is too thin to be specific — {entry['reason']!r}"
    if entry["decision"] == reg.BUILDER:
        assert entry.get("step"), f"{name}: a BUILDER must name the step that runs it"


@pytest.mark.parametrize("name", sorted(DERIVED_ENTRIES))
def test_derived_entry_declares_all_five(name):
    """The charter's four pieces plus the lane. A DERIVED artifact missing any of them is
    exactly one of the three broken triples this epic was filed on."""
    e = DERIVED_ENTRIES[name]
    for facet in ("outputs", "writer", "guard", "guard_lane", "inputs"):
        assert e.get(facet), f"{name}: DERIVED artifact is missing its {facet}"
    assert e["guard_lane"] in reg._LANE_WORKFLOW, f"{name}: guard_lane {e['guard_lane']!r} is not a real lane"


@pytest.mark.parametrize("name", sorted(DERIVED_ENTRIES))
def test_the_declared_generator_and_outputs_exist(name):
    e = DERIVED_ENTRIES[name]
    assert os.path.exists(os.path.join(reg.REPO, name)), f"{name}: generator file does not exist"
    for out in e["outputs"]:
        if "*" in out:
            continue
        assert os.path.exists(os.path.join(reg.REPO, out)), f"{name}: declared output {out} does not exist"


# ── The lane assertions — the point of the whole file ────────────────────────


@pytest.mark.parametrize("name", sorted(DERIVED_ENTRIES))
def test_the_guard_actually_runs_in_its_declared_lane(name):
    """Declared is not the same as wired. `generate_mcp_tool_catalog` had a working
    `--check` that no workflow step, pytest, or reconcile job ever invoked."""
    e = DERIVED_ENTRIES[name]
    workflow = os.path.join(reg.REPO, reg._LANE_WORKFLOW[e["guard_lane"]])
    with open(workflow, encoding="utf-8") as fh:
        text = fh.read()
    assert e["guard"] in text, (
        f"{name}: declares its guard runs in {e['guard_lane']}, but {e['guard']!r} does not appear in "
        f"{reg._LANE_WORKFLOW[e['guard_lane']]}. A guard nobody runs is a green light wired to nothing."
    )


@pytest.mark.parametrize("name", sorted(DERIVED_ENTRIES))
def test_the_lane_triggers_on_the_artifacts_inputs(name):
    """THE assertion. A guard placed in a lane the staling change cannot trigger reds a
    later, innocent commit — and whoever debugs it starts from an unrelated diff. That is
    #2975 in one sentence, and it is now checkable for every registered artifact."""
    e = DERIVED_ENTRIES[name]
    triggers = reg.lane_trigger_paths(e["guard_lane"])
    uncovered = [i for i in e["inputs"] if not reg.lane_covers(i, triggers)]
    assert not uncovered, (
        f"{name}: input(s) {uncovered} can stale this artifact, but lane {e['guard_lane']} does not "
        f"trigger on them — so the guard reds a LATER commit, not the one that staled it. "
        f"Lane triggers: {sorted(triggers)}"
    )


@pytest.mark.parametrize("name", sorted(DERIVED_ENTRIES))
def test_a_reconciled_artifact_really_is_in_run_generators(name):
    """The self-healing half. `reconciled=True` is a claim about ci-cd.yml; check it."""
    e = DERIVED_ENTRIES[name]
    if not e.get("reconciled"):
        pytest.skip(f"{name} does not claim to be reconciled")
    commands = reg.run_generators_commands()
    assert any(e["writer"] in c for c in commands), (
        f"{name}: claims reconciled=True but {e['writer']!r} is not in ci-cd.yml's run_generators(). " f"Present: {commands}"
    )


def test_lane_covers_rejects_a_narrower_trigger():
    """Mutation proof for the coverage helper itself, run every time. A helper that
    returned True unconditionally would make the lane assertion above vacuous — and it
    would look identical in CI."""
    assert reg.lane_covers("lambdas/**", ["lambdas/**"])
    assert reg.lane_covers("lambdas/web/x.py", ["lambdas/**"])
    assert not reg.lane_covers("lambdas/**", ["lambdas/web/x.py"])
    assert not reg.lane_covers("docs/**", ["lambdas/**", "mcp/**"])
