"""tests/test_fullbody_block_calendar_4064.py — v0.3's block calendar and full-body session.

WHY THIS FILE EXISTS

v0.3 went ACTIVE on 2026-09-21 and block 1 starts Thursday 2026-09-24, but the generator
only knew a WEEKDAY grid (Mon/Wed/Fri full-body, Thursday a walk) and built every "full"
day with the v0.1 muscle-budget selector, the §3 role printed as a label. So the plan for
the first session of the block was a walk, and a heavy day had no top set.

What these tests hold:

  1. THE CALENDAR IS DATA, PINNED. The first 13 program weeks — 39 session dates, roles,
     block numbers and the two deload weeks — are written out literally below. A change
     to `BLOCK_CALENDAR` or to the redline's deload period reds this test by name.
  2. THE DELOAD PERIOD HAS ONE HOME. It is read from `owner_redlines`, with a mutation
     control: moving the redline moves the calendar.
  3. §3 IS THE SESSION. Each required role trains four anchors; the three roles together
     train every pattern exactly twice; a heavy exposure is one top set + two back-offs
     at 4–6; the numbers match the redline's rep-scheme prose; deload removes ~30 % of
     sets and never a top set.
  4. THE GENERATOR BUILDS IT for 2026-09-24 (not a walk), sets back-offs at −10 % of the
     floored top set, and files it in the "Full Body" folder.
  5. v0.2 / INACTIVE IS UNTOUCHED. With `ACTIVE` False the seam serves the JSON grid and
     2026-09-24 (a Thursday) is whatever that grid says — the calendar is never consulted.
  6. plan_next_session FOR 2026-09-24, THROUGH THE MCP HANDLER, proposes the full-body
     HEAVY session of week 1 — the real program module, the real catalog, readers mocked.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
import unittest.mock
from contextlib import ExitStack
from unittest.mock import patch

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "lambdas"))

os.environ.setdefault("S3_BUCKET", "test-bucket")
os.environ.setdefault("USER_ID", "matthew")
os.environ.setdefault("AWS_DEFAULT_REGION", "us-west-2")

from training import owner_redlines, program_structure, routine_generator  # noqa: E402

CATALOG = json.loads((REPO / "config" / "movement_catalog.json").read_text())

# ── 1. the first 13 weeks, literally ─────────────────────────────────────────
# (week, block, deload, [(date, role), ...]). Written by hand from the owner's statement on
# #4064 — Thu 09-24, Sat 09-26, Mon 09-28, then Mon/Wed/Fri — not generated by the code
# under test, so the test cannot agree with a bug by construction.
H, M, HM = "heavy", "moderate", "heavy_moderate"
EXPECTED_13_WEEKS = [
    (1, 1, False, [("2026-09-24", H), ("2026-09-26", M), ("2026-09-28", HM)]),
    (2, 1, False, [("2026-09-30", H), ("2026-10-02", M), ("2026-10-05", HM)]),
    (3, 1, False, [("2026-10-07", H), ("2026-10-09", M), ("2026-10-12", HM)]),
    (4, 1, False, [("2026-10-14", H), ("2026-10-16", M), ("2026-10-19", HM)]),
    (5, 1, False, [("2026-10-21", H), ("2026-10-23", M), ("2026-10-26", HM)]),
    (6, 1, True, [("2026-10-28", H), ("2026-10-30", M), ("2026-11-02", HM)]),
    (7, 2, False, [("2026-11-04", H), ("2026-11-06", M), ("2026-11-09", HM)]),
    (8, 2, False, [("2026-11-11", H), ("2026-11-13", M), ("2026-11-16", HM)]),
    (9, 2, False, [("2026-11-18", H), ("2026-11-20", M), ("2026-11-23", HM)]),
    (10, 2, False, [("2026-11-25", H), ("2026-11-27", M), ("2026-11-30", HM)]),
    (11, 2, False, [("2026-12-02", H), ("2026-12-04", M), ("2026-12-07", HM)]),
    (12, 2, True, [("2026-12-09", H), ("2026-12-11", M), ("2026-12-14", HM)]),
    (13, 3, False, [("2026-12-16", H), ("2026-12-18", M), ("2026-12-21", HM)]),
]


def test_the_first_13_weeks_are_pinned():
    got = [
        (w["week"], w["block"], w["deload"], [(s["date"], s["session_role"]) for s in w["sessions"]])
        for w in program_structure.block_calendar(13)
    ]
    assert got == EXPECTED_13_WEEKS


def test_block_1_opens_thu_sat_mon_then_runs_mon_wed_fri():
    weeks = program_structure.block_calendar(13)
    assert [s["weekday"] for s in weeks[0]["sessions"]] == ["Thursday", "Saturday", "Monday"]
    for w in weeks[1:]:
        assert [s["weekday"] for s in w["sessions"]] == ["Wednesday", "Friday", "Monday"], w
    # no gap and no double at the seam: each session is 2 or 3 days after the previous one
    dates = [s["date"] for w in weeks for s in w["sessions"]]
    assert len(dates) == len(set(dates)) == 39
    from datetime import date

    gaps = {(date.fromisoformat(b) - date.fromisoformat(a)).days for a, b in zip(dates, dates[1:])}
    assert gaps == {2, 3}


def test_calendar_entry_answers_every_day_in_week_1():
    by_day = {d: program_structure.calendar_entry(d) for d in [f"2026-09-{n}" for n in range(23, 31)]}
    assert by_day["2026-09-23"] is None, "before block 1 the weekday grid answers, not the calendar"
    lifting = {d: e["session_role"] for d, e in by_day.items() if e and e["archetype"] == "full"}
    assert lifting == {"2026-09-24": H, "2026-09-26": M, "2026-09-28": HM, "2026-09-30": H}
    for d in ("2026-09-25", "2026-09-27", "2026-09-29"):
        assert by_day[d]["archetype"] == "aerobic", d
    assert by_day["2026-09-24"]["week"] == 1 and by_day["2026-09-30"]["week"] == 2


def test_optional_fourth_is_saturday_from_week_2_and_never_in_a_deload_week():
    assert program_structure.calendar_entry("2026-10-03")["session_role"] == "optional_fourth"
    assert program_structure.calendar_entry("2026-10-03")["optional"] is True
    assert program_structure.calendar_entry("2026-10-31")["archetype"] == "aerobic", "week 6 is a deload — no optional fourth"


# ── 2. the deload period has one home ────────────────────────────────────────
def test_deload_period_is_read_from_the_redline_with_a_mutation_control():
    assert owner_redlines.REDLINES["lifting_sessions_per_wk"]["deload"] == {"every_nth_week": 6, "sets_pct": -30, "loads": "held"}
    assert [w["week"] for w in program_structure.block_calendar(13) if w["deload"]] == [6, 12]
    with unittest.mock.patch.dict(owner_redlines.REDLINES["lifting_sessions_per_wk"]["deload"], {"every_nth_week": 4}):
        assert [w["week"] for w in program_structure.block_calendar(13) if w["deload"]] == [4, 8, 12]


# ── 3. §3 is the session ─────────────────────────────────────────────────────
def test_every_anchor_pattern_is_trained_exactly_twice_across_the_three_roles():
    counts: dict[str, int] = {}
    for role in program_structure.BLOCK_CALENDAR["session_roles"]:
        anchors = program_structure.SESSION_TEMPLATES[role]["anchors"]
        assert len(anchors) == 4, role
        for pattern, _ in anchors:
            counts[pattern] = counts.get(pattern, 0) + 1
    assert counts == {p: 2 for p in program_structure.ANCHORS}


def test_squat_and_hinge_are_never_heavy_on_the_same_day():
    for role, tmpl in program_structure.SESSION_TEMPLATES.items():
        heavy = {p for p, i in tmpl["anchors"] if i == "heavy"}
        assert not {"squat", "hinge"} <= heavy, role


def test_heavy_exposure_is_a_top_set_plus_two_back_offs():
    rx = program_structure.session_prescription_for_role("heavy", catalog_movements=CATALOG["movements"])
    squat = next(e for e in rx["exposures"] if e["pattern"] == "squat")
    assert [s["kind"] for s in squat["sets"]] == ["top", "back_off", "back_off"]
    assert squat["sets"][0]["reps"] == [4, 6] and squat["sets"][0]["rpe"] == [7, 8]
    assert all(s["pct_of_top"] == 90 for s in squat["sets"][1:])
    assert squat["movement_key"] == "leg_press"


def test_exposure_numbers_match_the_redline_rep_scheme_prose():
    prose = owner_redlines.REDLINES["lifting_sessions_per_wk"]["rep_scheme"]
    e = program_structure.EXPOSURES
    assert f"{e['heavy']['reps'][0]}–{e['heavy']['reps'][1]}" in prose
    assert f"RPE {e['heavy']['top_rpe'][0]}–{e['heavy']['top_rpe'][1]}" in prose
    assert f"−{abs(e['heavy']['back_off_pct'])} %" in prose
    assert f"moderate {e['moderate']['reps'][0]}–{e['moderate']['reps'][1]}" in prose
    assert (
        f"accessories {e['accessory']['reps'][0]}–{e['accessory']['reps'][1]} at RIR {e['accessory']['rir'][0]}–{e['accessory']['rir'][1]}"
        in prose
    )


def test_the_program_summary_carries_the_calendar_and_the_anchor_sets_per_pattern():
    summary = program_structure.summary()
    assert summary["block_calendar"]["block_1_start"] == "2026-09-24"
    # #4090: vertical pull runs 2 sets per exposure so BACK (row + pulldown) sits inside 6–10;
    # the per-MUSCLE ranges are held in tests/test_v03_load_ramp_4090.py, not per pattern
    assert summary["weekly_anchor_sets"] == {**{p: 6 for p in program_structure.ANCHORS}, "vertical_pull": 4}


def test_sessions_fit_the_ceiling_and_the_week_totals_sit_in_the_redline_band():
    ceiling = program_structure.week_grid()["session_set_ceiling"]
    totals = {r: program_structure.session_prescription_for_role(r)["total_sets"] for r in program_structure.SESSION_TEMPLATES}
    assert all(t <= ceiling for t in totals.values()), totals
    week = sum(totals[r] for r in program_structure.BLOCK_CALENDAR["session_roles"])
    lo, hi = owner_redlines.REDLINES["lifting_sessions_per_wk"]["total_hard_sets_wk"]
    assert lo <= week <= hi, week
    for role in program_structure.BLOCK_CALENDAR["session_roles"]:
        n_acc = len(program_structure.SESSION_TEMPLATES[role]["accessories"])
        assert 2 <= n_acc <= 3, role
        assert set(program_structure.SESSION_TEMPLATES[role]["accessories"]) <= set(program_structure.ACCESSORY_POOL["full"])


def test_deload_cuts_about_30_percent_of_sets_and_keeps_every_top_set_and_anchor():
    for role in program_structure.SESSION_TEMPLATES:
        full = program_structure.session_prescription_for_role(role)
        dl = program_structure.session_prescription_for_role(role, deload=True)
        assert dl["deload_trim"]["sets_after"] == full["total_sets"] - round(full["total_sets"] * 0.30)
        assert [e["pattern"] for e in dl["exposures"]] == [e["pattern"] for e in full["exposures"]]
        for e in dl["exposures"]:
            assert len(e["sets"]) >= 1
            if e["intensity"] == "heavy":
                assert e["sets"][0]["kind"] == "top"


def test_without_the_catalog_anchors_are_patterns_not_guesses():
    rx = program_structure.session_prescription_for_role("heavy")
    anchors = [e for e in rx["exposures"] if e["kind"] == "anchor"]
    assert all(e["movement_key"] is None and "not read" in e["resolution_note"] for e in anchors)


# ── 4. the generator builds it ───────────────────────────────────────────────
def _generate(day: str, **kw):
    with patch.object(routine_generator, "_load_note_indexes", return_value=({}, {}, {}, {})):
        return routine_generator.generate_routines(routine_generator.GeneratorInputs(target_date=day, **kw))


def test_generator_builds_the_heavy_full_body_session_on_2026_09_24():
    ideal, floor = _generate("2026-09-24")
    assert ideal.archetype == "full" and ideal.variant == "ideal"
    assert ideal.title.startswith("Full Body HEAVY — W1")
    assert [b.movement_key for b in ideal.exercises] == [
        "leg_press",
        "db_bench_press_flat",
        "machine_row",
        "lat_pulldown",
        "leg_curl",
        "cable_tricep_pushdown",
        "db_curl",
    ]
    # #4090: pulldown 2 sets (back 10, not 12); the lateral raise gave way to an arm pair (delts 6, not 8)
    assert [len(b.sets) for b in ideal.exercises] == [3, 3, 3, 2, 2, 2, 2]
    assert ideal.exercises[0].sets[0].rep_range_start == 4 and ideal.exercises[0].sets[0].rep_range_end == 6
    assert ideal.inputs_snapshot["calendar"]["week"] == 1
    assert ideal.inputs_snapshot["session_prescription"]["hevy_folder"] == "Full Body"
    # the Minimum Viable Session: anchors only, top set + one back-off
    assert floor.variant == "floor" and [len(b.sets) for b in floor.exercises] == [2, 2, 2, 2]


def test_mutation_control_the_weekday_grid_alone_makes_2026_09_24_a_walk():
    with patch.object(program_structure, "calendar_entry", return_value=None):
        routines = _generate("2026-09-24")
    assert routines[0].archetype == "aerobic", "without the calendar, Thursday is the grid's walk — the defect #4064 names"


def test_generator_back_offs_sit_10_percent_under_the_ramped_top_set():
    lb = 0.45359237
    history = {"C7973E0E": [{"date": "2026-09-20", "top_weight_kg": 200 * lb, "sets": [{"weight_kg": 200 * lb, "reps": 8}]}]}
    weights = {"2026-09-20": 316.0, "2026-09-24": 315.0}
    with patch.object(routine_generator, "_load_note_indexes", return_value=(history, weights, {}, {})):
        ideal = routine_generator.generate_routines(routine_generator.GeneratorInputs(target_date="2026-09-24"))[0]
    leg_press = ideal.exercises[0]
    top = leg_press.sets[0].weight_kg
    # #4090: week 1 of the v0.3 entry ramp — 60 % of the anchor after the 15 % discount
    assert top == 46.5  # ceil-to-0.5 kg of 200 lb x 0.85 x 0.60 = 46.27 kg
    assert [s.weight_kg for s in leg_press.sets[1:]] == [routine_generator._floor_half_kg(top * 0.9)] * 2
    assert any("back-offs at 90%" in r for r in ideal.rationale)
    # the note leads with history (ADR-068's one best line), then the §3 prescription
    assert "HEAVY: 1 top set of 4–6 @ RPE 7–8" in leg_press.notes


def test_generator_deload_week_holds_loads_and_cuts_sets():
    ideal = _generate("2026-10-28")[0]
    assert "DELOAD" in ideal.title
    assert sum(len(b.sets) for b in ideal.exercises) == 12
    assert any("deload: sets 17 -> 12" in r for r in ideal.rationale)


def test_red_recovery_drops_accessories_not_anchors():
    ideal = _generate("2026-09-24", recovery_tier="red")[0]
    assert [b.movement_key for b in ideal.exercises] == ["leg_press", "db_bench_press_flat", "machine_row", "lat_pulldown"]


def test_hevy_folder_for_full_is_the_program_folder():
    from mcp.hevy_routine_commit_report import folder_title_for

    ideal = _generate("2026-09-24")[0]
    assert folder_title_for(ideal) == program_structure.HEVY_FOLDER == "Full Body"


def test_folder_is_created_if_absent_at_first_commit_never_before():
    """The folder is find-or-create at commit (`ensure_folder`). No live write happens here —
    the write client is mocked — and nothing in the generator or the planner creates one."""
    from mcp import hevy_routine_commit_report as rep

    created: list[str] = []
    with (
        patch("training.hevy_write_client.list_all_folders", return_value=([{"id": 1, "title": "Push"}], False)),
        patch("training.hevy_write_client.create_folder", side_effect=lambda t: created.append(t) or {"routine_folder": {"id": 9}}),
    ):
        fid, miss = rep.ensure_folder("Full Body")
    assert (fid, miss, created) == (9, None, ["Full Body"])
    with (
        patch("training.hevy_write_client.list_all_folders", return_value=([{"id": 7, "title": "Full Body"}], False)),
        patch("training.hevy_write_client.create_folder", side_effect=AssertionError("must not create a duplicate")),
    ):
        assert rep.ensure_folder("Full Body") == (7, None)


def test_title_type_label_is_full_body():
    from training.routine_title import format_title, format_why_note

    ideal = _generate("2026-09-24")[0]
    assert format_title(ideal, {"phase": "Foundation", "type_count_in_phase": 1, "all_time_count": 5}) == "Foundation - Full Body - 1 - 5"
    assert format_why_note(ideal).startswith("Full-body heavy")


# ── 5. v0.2 / inactive is untouched ──────────────────────────────────────────
def test_inactive_program_never_consults_the_calendar():
    live = json.loads((REPO / "config" / "training_week.json").read_text())
    thursday = live["schedule"]["3"]["archetype"]
    with (
        patch.object(program_structure, "ACTIVE", False),
        patch.object(program_structure, "calendar_entry", side_effect=AssertionError("calendar read under an inactive program")),
    ):
        routines = _generate("2026-09-24")
    assert routines[0].archetype == thursday
    assert all("session_role" not in r for r in routines[0].rationale)


def test_inactive_program_plan_session_says_the_json_grid_decides():
    from training import plan_engine

    with patch.object(program_structure, "ACTIVE", False):
        block = plan_engine.constraint_block(date="2026-09-24")
    assert block["session"]["source"] == "json" and block["session"]["archetype"] is None


# ── 6. plan_next_session for 2026-09-24, through the MCP handler ─────────────
def _stage1_patches():
    return [
        patch("mcp.tools_benchmark.tool_get_benchmark", return_value={"applicable": False, "reason": "offline"}),
        patch("mcp.tools_health.tool_get_readiness_score", return_value={"score": 60}),
        patch("mcp.tools_training.tool_get_acwr_status", return_value={"zone": "safe"}),
        patch("mcp.tools_strength.tool_get_muscle_volume", return_value={"muscle_volume": {}}),
        patch("mcp.tools_plan._walking_volume_last_7d", return_value=None),
        patch("mcp.tools_plan._protein_days_7d", return_value=(None, None)),
        patch("mcp.tools_plan._gather_performed_evidence", return_value=None),
        patch("mcp.tools_plan._rotation_window", return_value=None),
        patch("mcp.tools_plan._pain_dismissals", return_value=[]),
        patch("mcp.tools_plan._nutrition_critics_block", return_value={"verdicts": []}),
        patch("mcp.tools_plan._load_anchor_indexes", return_value=({}, {})),
        patch("training.training_notes.training_notes_health", side_effect=RuntimeError("offline")),
        patch("ai.bedrock_client.invoke", side_effect=AssertionError("no model in stage 1")),
    ]


def test_plan_next_session_2026_09_24_through_the_mcp_handler_proposes_full_body_heavy():
    from mcp import handler as h

    with ExitStack() as st:
        for cm in _stage1_patches():
            st.enter_context(cm)
        st.enter_context(patch.object(h, "_emit_tool_metric"))
        st.enter_context(patch.object(h, "_audit_tool_call"))
        resp = h.handle_tools_call({"name": "plan_next_session", "arguments": {"target_date": "2026-09-24"}})
    out = json.loads(resp["content"][0]["text"])
    assert out["target_date"] == "2026-09-24", out
    session = out["constraint_block"]["session"]
    assert session["source"] == "block_calendar"
    assert (session["archetype"], session["session_role"], session["week"], session["block"], session["deload"]) == ("full", H, 1, 1, False)
    rx = session["prescription"]
    assert rx["hevy_folder"] == "Full Body"
    assert [(e["pattern"], e["intensity"], e["movement_key"]) for e in rx["exposures"] if e["kind"] == "anchor"] == [
        ("squat", "heavy", "leg_press"),
        ("bench", "heavy", "db_bench_press_flat"),
        ("row", "heavy", "machine_row"),
        ("vertical_pull", "moderate", "lat_pulldown"),
    ]
    assert rx["total_sets"] == 17
    assert "constraint_block.session" in out["how_to_use"]
