"""tests/test_strava_population.py — the Strava distance/elevation population rule (#2331, ADR-104).

`strava_lambda._normalize` used to write ``round(...) if activity.get("distance") else None``.
`0` is falsy, so a genuinely flat run was stored as *unmeasured*. The naive repair —
un-collapse every zero — is worse: it would enter 758 gym `Workout` sessions and 650
indoor-trainer records into the distance population as measured 0.0-mile efforts, and the
all-time "top N%" claims the platform publishes are percentiles over exactly that
population. So #2331 is a population-membership decision first and a coercion second.

What these tests pin:

  * **The ADR-104 distinction, spelled out.** measured-zero → `0.0`; absent-because-the-
    metric-was-not-measured → `None`. Both directions, with the reason for each.
  * **The decision covers what ingestion actually produces.** The type set is checked
    against `config/strava_activity_type_census.json` — machine-generated by
    `scripts/strava_type_census.py` from the live archive — so a sport Matthew takes up
    next month reds this file instead of silently defaulting.
  * **Consumers tolerate the 0.** Every reader of `distance_miles` /
    `total_elevation_gain_feet` is exercised on the 0 path: the percentile pools (which
    change), the enriched-name builder, the digest/vacation-fund sums (which do not).
  * **The out-of-population arm is not vacuous.** A mutation that deletes it changes a
    published figure — the all-time percentile a reader sees on an activity.
  * **The reconciliation script re-derives the same rule and writes Decimal.**
"""

import json
import os
import sys

import pytest

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "lambdas"))
sys.path.insert(0, os.path.join(_REPO, "scripts"))

for _k, _v in {
    "S3_BUCKET": "test-bucket",
    "TABLE_NAME": "life-platform",
    "USER_ID": "matthew",
    "AWS_DEFAULT_REGION": "us-west-2",
    "AWS_REGION": "us-west-2",
}.items():
    os.environ.setdefault(_k, _v)

from ingestion import strava_population as pop  # noqa: E402
from ingestion.strava_lambda import _normalize  # noqa: E402

CENSUS_PATH = os.path.join(_REPO, "config", "strava_activity_type_census.json")


def _api_activity(**kw):
    """A raw Strava API activity as `_normalize` receives it."""
    base = {"id": 1, "name": "test", "sport_type": "Run", "type": "Run", "trainer": False, "manual": False}
    base.update(kw)
    return base


# ══════════════════════════════════════════════════════════════════════════
# 1. The ADR-104 distinction, made explicit
# ══════════════════════════════════════════════════════════════════════════


def test_measured_zero_on_an_outdoor_run_is_stored_as_zero_not_absent():
    """The bug in one line: a pancake-flat GPS run measured 0 ft of gain. That is a
    measurement, it belongs in the elevation distribution, and it used to vanish."""
    out = _normalize(_api_activity(distance=8046.72, total_elevation_gain=0))
    assert out["total_elevation_gain_feet"] == 0.0, "a measured zero must survive as zero"
    assert out["total_elevation_gain_feet"] is not None
    assert out["distance_miles"] == 5.0


def test_absent_because_not_reported_stays_absent():
    """Strava omitting the key entirely is absence — never coerce it to 0."""
    out = _normalize(_api_activity(name="Walk"))
    assert out["distance_miles"] is None
    assert out["total_elevation_gain_feet"] is None


def test_gym_session_zero_is_absence_not_a_measured_zero():
    """Distance is not a property of a bench-press session. Strava's 0.0 is schema
    filler; publishing it as a measured 0.0 miles would be a fabricated data point."""
    for sport in ("WeightTraining", "Workout", "Yoga", "HighIntensityIntervalTraining"):
        out = _normalize(_api_activity(sport_type=sport, type=sport, distance=0, total_elevation_gain=0))
        assert out["distance_miles"] is None, sport
        assert out["total_elevation_gain_feet"] is None, sport
        # The raw API value is still stored verbatim — absence is a statement about the
        # DERIVED figure, not a reason to drop what Strava sent.
        assert out["distance_meters"] == 0


def test_indoor_trainer_zero_is_absence_even_on_a_distance_bearing_type():
    """The archive's dominant case: 372 WHOOP-synced Walks and 159 Rides with
    trainer=True and distance 0. Matthew plainly covered ground; the distance was not
    measured. Storing 0 would fabricate a measurement, which is the same ADR-104 sin
    pointing the other way."""
    out = _normalize(_api_activity(sport_type="Walk", type="Walk", trainer=True, distance=0, total_elevation_gain=0))
    assert out["distance_miles"] is None
    assert out["total_elevation_gain_feet"] is None


def test_manually_entered_zero_is_absence():
    """A hand-logged activity's 0 is an unfilled field, not a measurement."""
    out = _normalize(_api_activity(sport_type="Walk", type="Walk", manual=True, distance=0, total_elevation_gain=0))
    assert out["distance_miles"] is None


def test_indoor_trainer_keeps_a_nonzero_measurement():
    """The channel gate only decides ZEROS. A treadmill run with a footpod reports real
    distance; that must survive untouched."""
    out = _normalize(_api_activity(sport_type="Run", type="Run", trainer=True, distance=5000, total_elevation_gain=0))
    assert out["distance_miles"] == 3.11
    assert out["total_elevation_gain_feet"] is None  # 0 with no elevation channel → absent


def test_water_sports_are_in_distance_but_out_of_elevation_population():
    """A swim has a real distance and no meaningful vertical gain."""
    out = _normalize(_api_activity(sport_type="Swim", type="Swim", distance=0, total_elevation_gain=0))
    assert out["distance_miles"] == 0.0
    assert out["total_elevation_gain_feet"] is None


def test_unknown_activity_type_defaults_to_absent():
    """An unclassified sport must not silently join a published population."""
    out = _normalize(_api_activity(sport_type="Hovercraft", type="Hovercraft", distance=0, total_elevation_gain=0))
    assert out["distance_miles"] is None
    assert out["total_elevation_gain_feet"] is None


# ══════════════════════════════════════════════════════════════════════════
# 2. The type set is derived from what ingestion actually sees
# ══════════════════════════════════════════════════════════════════════════


def _census():
    with open(CENSUS_PATH) as fh:
        return json.load(fh)


def test_every_observed_activity_type_carries_an_explicit_decision():
    """Acceptance criterion 1 of #2331: the rule's type set is derived from the archive,
    not hand-typed. Regenerate with `python3 scripts/strava_type_census.py --write`; a new
    type reds this test until its distance/elevation membership is decided deliberately."""
    census = _census()
    undecided = sorted(t for t in census["types"] if not pop.is_decided(t))
    assert undecided == [], f"activity types seen in the archive with no population decision: {undecided}"


def test_census_carries_its_provenance():
    """A census with no provenance is indistinguishable from a hand-typed list."""
    prov = _census()["_provenance"]
    assert prov["generated_by"] == "scripts/strava_type_census.py"
    assert prov["activities"] > 0 and prov["day_records"] > 0
    assert "read-only" in prov["source"]


def test_the_two_populations_are_not_the_same_set():
    """If they were, the per-metric decision would be decoration."""
    assert pop.DISTANCE_POPULATION != pop.ELEVATION_POPULATION
    assert "Swim" in pop.DISTANCE_POPULATION and "Swim" not in pop.ELEVATION_POPULATION
    assert "WeightTraining" not in pop.DISTANCE_POPULATION


# ══════════════════════════════════════════════════════════════════════════
# 3. Consumers on the 0 path
# ══════════════════════════════════════════════════════════════════════════


def _day(activities):
    return {"activities": activities}


def test_percentile_pool_membership_matches_the_writer_rule():
    """The pool's `is not None` gate and the writer's population rule must be the SAME
    population, or the denominator of every published percentile is a different set from
    the one the rule defines."""
    from ingestion import enrichment_lambda

    api_acts = [
        _api_activity(sport_type="Run", type="Run", distance=8046.72, total_elevation_gain=0),  # measured flat run
        _api_activity(sport_type="Run", type="Run", distance=16093.4, total_elevation_gain=100),
        _api_activity(sport_type="WeightTraining", type="WeightTraining", distance=0, total_elevation_gain=0),
        _api_activity(sport_type="Walk", type="Walk", trainer=True, distance=0, total_elevation_gain=0),
    ]
    stored = [_day([_normalize(a) for a in api_acts])]
    elevations, distances = enrichment_lambda.build_percentile_lookup(stored)

    expected_dist = sum(1 for a in api_acts if pop.distance_miles(a, a.get("distance")) is not None)
    expected_elev = sum(1 for a in api_acts if pop.elevation_gain_feet(a, a.get("total_elevation_gain")) is not None)
    assert len(distances) == expected_dist == 2
    assert len(elevations) == expected_elev == 2
    # The measured zero IS in the pool, at the bottom of the distribution.
    assert elevations[0] == 0.0


def test_enriched_name_does_not_print_a_zero_stat():
    """A 0.0mi / 0ft suffix would be noise on every flat activity — the name builder's
    truthiness check is correct HERE (it is a display choice, not a data claim)."""
    from ingestion import enrichment_lambda

    act = _normalize(_api_activity(name="Flat Loop", sport_type="Run", type="Run", distance=8046.72, total_elevation_gain=0))
    name = enrichment_lambda.build_enriched_name(act, None, [], [], [], [])
    assert "0ft" not in name
    assert "Flat Loop" in name


def test_extensive_day_totals_are_unchanged_by_the_fix():
    """`total_distance_miles` / `total_elevation_gain_feet` are sums over the whole day, so
    an absent value and a measured 0 contribute identically. Named here so nobody reads
    the fix as moving a headline number that it does not move."""
    from ingestion.strava_lambda import transform

    acts = [
        _normalize(_api_activity(sport_type="Run", type="Run", distance=8046.72, total_elevation_gain=0)),
        _normalize(_api_activity(sport_type="WeightTraining", type="WeightTraining", distance=0, total_elevation_gain=0)),
    ]
    rec = transform({"activities": acts}, "2026-08-10")[0]
    assert rec["total_distance_miles"] == 5.0
    assert rec["total_elevation_gain_feet"] == 0.0


@pytest.mark.parametrize("zero_value", [0.0])
def test_digest_and_vacation_fund_readers_tolerate_a_zero(zero_value):
    """The `or 0` readers must neither crash nor change their sum when a null becomes a
    measured 0. Exercised against the real reader expressions."""
    from content import vacation_fund
    from emails import weekly_digest_extractors  # noqa: F401

    act_zero = {"sport_type": "Run", "distance_miles": zero_value, "total_elevation_gain_feet": zero_value}
    act_null = {"sport_type": "Run", "distance_miles": None, "total_elevation_gain_feet": None}
    # weekly digest's per-activity render expression
    for act in (act_zero, act_null):
        assert round(float(act.get("distance_miles") or 0), 1) == 0.0
        assert round(float(act.get("total_elevation_gain_feet") or 0)) == 0
    # vacation fund's float coercion
    assert vacation_fund._f(zero_value) == 0.0
    assert vacation_fund._f(None) == 0.0


def test_search_activities_names_the_population_it_ranks_against():
    """Acceptance criterion 3 of #2331: a 'top N% all-time' claim must say what the N% is
    OF. `all_time_total_acts` is the denominator; `population` is its definition."""
    from mcp import tools_data

    assert tools_data._population_label("distance_miles") == pop.DISTANCE_POPULATION_LABEL
    assert tools_data._population_label("total_elevation_gain_feet") == pop.ELEVATION_POPULATION_LABEL
    for label in (pop.DISTANCE_POPULATION_LABEL, pop.ELEVATION_POPULATION_LABEL):
        assert "not indoor-trainer or manually entered" in label


# ══════════════════════════════════════════════════════════════════════════
# 4. Mutation proof — the out-of-population arm is load-bearing
# ══════════════════════════════════════════════════════════════════════════


def test_removing_the_out_of_population_arm_changes_a_published_percentile(monkeypatch):
    """Delete the arm (every type in-population, every record measured) and re-run the
    exact pipeline that publishes 'top N% distance ever' on an activity's name. If the
    published percentile does not move, the arm guards nothing.

    This is the figure the issue is about: the denominator of every all-time percentile
    on the site, in the digests and in MCP search.
    """
    from ingestion import enrichment_lambda

    api_acts = [
        _api_activity(sport_type="Run", type="Run", name="Long Run", distance=16093.4, total_elevation_gain=100),
        _api_activity(sport_type="Run", type="Run", name="Flat Run", distance=8046.72, total_elevation_gain=0),
    ] + [
        _api_activity(sport_type="WeightTraining", type="WeightTraining", name="Lift", distance=0, total_elevation_gain=0) for _ in range(8)
    ]

    def _pipeline():
        stored = [_day([_normalize(a) for a in api_acts])]
        sorted_elev, sorted_dist = enrichment_lambda.build_percentile_lookup(stored)
        long_run = stored[0]["activities"][0]
        return len(sorted_dist), enrichment_lambda.percentile(sorted_dist, long_run["distance_miles"])

    denom_with_arm, pct_with_arm = _pipeline()

    # The mutation: strip the population decision so every type is in, and every record
    # counts as measured — i.e. exactly the "coerce 0 correctly" fix the issue warns against.
    monkeypatch.setattr(pop, "DISTANCE_POPULATION", frozenset(pop._DECISIONS) | {"WeightTraining"})
    monkeypatch.setattr(pop, "ELEVATION_POPULATION", frozenset(pop._DECISIONS) | {"WeightTraining"})
    monkeypatch.setattr(pop, "has_measurement_channel", lambda activity: True)

    denom_mutated, pct_mutated = _pipeline()

    assert denom_with_arm == 2, "only the two runs have a measured distance"
    assert denom_mutated == 10, "the mutation sweeps all eight gym sessions into the population"
    assert pct_with_arm == 50.0
    assert pct_mutated == 90.0
    assert pct_with_arm != pct_mutated, "the out-of-population arm must change a published figure"
    # And the published LABEL flips with it — "top 10% distance ever" appears only in the
    # mutated world, manufactured entirely out of gym sessions that never had a distance.
    assert enrichment_lambda.percentile_label(pct_with_arm, "distance") is None
    assert enrichment_lambda.percentile_label(pct_mutated, "distance") == "top 10% distance ever"


# ══════════════════════════════════════════════════════════════════════════
# 5. The reconciliation script
# ══════════════════════════════════════════════════════════════════════════


def test_reconciliation_plans_only_rows_the_rule_disagrees_with():
    import reconcile_strava_measured_zero as rec

    flat_run = {
        "sport_type": "Run",
        "distance_meters": 8046.72,
        "total_elevation_gain_meters": 0,
        "distance_miles": 5.0,
        "total_elevation_gain_feet": None,
    }
    gym = {
        "sport_type": "WeightTraining",
        "distance_meters": 0,
        "total_elevation_gain_meters": 0,
        "distance_miles": None,
        "total_elevation_gain_feet": None,
    }
    already_right = {
        "sport_type": "Run",
        "distance_meters": 8046.72,
        "total_elevation_gain_meters": 0,
        "distance_miles": 5.0,
        "total_elevation_gain_feet": 0.0,
    }

    assert rec.plan_activity(flat_run) == {"total_elevation_gain_feet": (None, 0.0)}
    assert rec.plan_activity(gym) == {}, "an already-correct absence is not a write"
    assert rec.plan_activity(already_right) == {}, "idempotent — a second run is a no-op"


def test_reconciliation_writes_decimal_never_float():
    """boto3 rejects float. #2331's writes are derived numbers, so this is the whole risk."""
    from decimal import Decimal

    import reconcile_strava_measured_zero as rec

    acts = [
        {
            "sport_type": "Run",
            "distance_meters": 8046.72,
            "total_elevation_gain_meters": 0,
            "distance_miles": 5.0,
            "total_elevation_gain_feet": None,
        }
    ]
    planned = rec.plan_day({"activities": acts})
    updated = rec._apply_changes(acts, planned)
    value = updated[0]["total_elevation_gain_feet"]
    assert isinstance(value, Decimal) and not isinstance(value, float)
    assert value == Decimal("0.0")
    assert acts[0]["total_elevation_gain_feet"] is None, "the input row must not be mutated in place"


def test_reconciliation_is_dry_run_unless_apply_is_passed():
    """Reading the source, not the behaviour: --apply must be an explicit opt-in flag, and
    every DDB write must sit behind it."""
    import ast
    import inspect

    import reconcile_strava_measured_zero as rec

    tree = ast.parse(inspect.getsource(rec.main))
    apply_flags = [n for n in ast.walk(tree) if isinstance(n, ast.Constant) and n.value == "--apply"]
    assert apply_flags, "the script must expose an explicit --apply flag"
    writes = [
        n for n in ast.walk(tree) if isinstance(n, ast.Attribute) and n.attr in ("update_item", "put_item", "delete_item", "batch_writer")
    ]
    assert writes, "sanity: the script does write when applied"
    # Every write is inside the `if args.apply:` block.
    apply_guards = [
        n
        for n in ast.walk(tree)
        if isinstance(n, ast.If)
        and isinstance(n.test, ast.Attribute)
        and n.test.attr == "apply"
        and isinstance(n.test.value, ast.Name)
        and n.test.value.id == "args"
    ]
    guarded = {
        id(w)
        for g in apply_guards
        for w in ast.walk(g)
        if isinstance(w, ast.Attribute) and w.attr in ("update_item", "put_item", "delete_item", "batch_writer")
    }
    assert {id(w) for w in writes} <= guarded, "a DDB write escapes the --apply guard"
