"""tests/test_session_sequence_4110.py — v0.3's sessions follow a SEQUENCE, not weekdays.

WHY THIS FILE EXISTS

#4064 bound each v0.3 session to a weekday (Thu 09-24 / Sat 09-26 / Mon 09-28, then
Mon/Wed/Fri). Owner, 2026-09-23: "more just focusing on planned sequence and not forgetting
next if I audible a change." Under the weekday calendar a walk on a lifting day silently
SKIPPED that session. These tests hold the replacement:

  1. THE SEQUENCE IS PINNED. heavy -> moderate -> heavy-moderate, 3 per program week, deload
     every 6th week, block of 6 — written out literally, not generated by the code under test.
  2. THE ISSUE'S FIXTURES. Heavy done Thu, walk Fri, walk Sat -> Sun serves MODERATE (not a
     weekday slot's session); two sessions skipped do not advance the week; an Engine day
     (cardio only, logged in Hevy) does not advance it; a warm-up-only log does not; two
     loaded logs on one day are one session; a session before the block start does not count.
  3. THE MUTATION CONTROL. A predicate under which a walk advances the position reds the
     fixture — so the fixture is proven to be able to fail.
  4. ONE WEEK. `plan_engine.program_week` (the `not_before_week` gate, #4098), the served
     session's `week`, and the week the load ramp is handed (#4090) are the same number.
  5. THE SURFACES. `constraint_block` names the position and the session that advanced it;
     the generator builds the sequence's session on a day the old calendar called a walk;
     an unread Hevy record is `sequence_unreadable` / week None — never a silent session 1.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
from contextlib import ExitStack
from unittest.mock import patch

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "lambdas"))

os.environ.setdefault("S3_BUCKET", "test-bucket")
os.environ.setdefault("USER_ID", "matthew")
os.environ.setdefault("AWS_DEFAULT_REGION", "us-west-2")

from training import owner_redlines, plan_engine, program_structure, routine_generator, session_sequence, training_streaks  # noqa: E402

H, M, HM = "heavy", "moderate", "heavy_moderate"


# ── fixtures: Hevy per-workout rows in the live DDB shape ────────────────────
def lift(day: str, title: str = "Foundation - Full Body - 1 - 1", *, start: str | None = None, wid: str | None = None) -> dict:
    return {
        "date": day,
        "sk": f"DATE#{day}#WORKOUT#{wid or 'L' + day}",
        "title": title,
        "source_workout_id": wid or "L" + day,
        "start_time": start or f"{day}T14:00:00Z",
        "exercises": [
            {
                "name": "Linear Leg Press",
                "sets": [{"type": "warmup", "weight_kg": 40, "reps": 10}, {"type": "normal", "weight_kg": 90, "reps": 5}],
            }
        ],
    }


def walk(day: str) -> dict:
    return {
        "date": day,
        "sk": f"DATE#{day}#WORKOUT#W{day}",
        "title": "Walk",
        "source_workout_id": "W" + day,
        "exercises": [{"name": "Walking", "sets": [{"type": "normal", "duration_sec": 3600, "distance_m": 5000}]}],
    }


def engine(day: str) -> dict:
    """The live Engine day: cycling + treadmill + stretching — no load (2026-09-21's shape)."""
    return {
        "date": day,
        "sk": f"DATE#{day}#WORKOUT#E{day}",
        "title": "Foundation - Engine - 3 - 15",
        "source_workout_id": "E" + day,
        "exercises": [
            {"name": "Cycling", "sets": [{"type": "normal", "duration_sec": 1800}]},
            {"name": "Treadmill", "sets": [{"type": "normal", "duration_sec": 1800}]},
            {"name": "Stretching", "sets": [{"type": "normal", "duration_sec": 600}]},
        ],
    }


def warmup_only(day: str) -> dict:
    return {
        "date": day,
        "title": "Started, bailed",
        "source_workout_id": "U" + day,
        "exercises": [{"name": "Bench Press (Barbell)", "sets": [{"type": "warmup", "weight_kg": 20, "reps": 10}]}],
    }


def served(day: str, rows: list[dict]) -> dict:
    e = session_sequence.next_session(day, rows)
    assert e is not None and e["source"] == "session_sequence", e
    return e


# ── 1. the sequence, pinned ──────────────────────────────────────────────────
# (index, week, session_in_week, role, block, deload) for the first 39 sessions, by hand.
EXPECTED = [
    (i, i // 3 + 1, i % 3 + 1, [H, M, HM][i % 3], 1 if i < 18 else (2 if i < 36 else 3), (i // 3 + 1) in (6, 12)) for i in range(39)
]


def test_the_first_13_program_weeks_are_pinned():
    got = [
        (p["sequence_index"], p["week"], p["session_in_week"], p["session_role"], p["block"], p["deload"])
        for p in session_sequence.preview(39)
    ]
    assert got == EXPECTED
    assert session_sequence.position(1)["position_label"] == "week 1 · session 2 of 3 · moderate"
    assert session_sequence.position(15)["position_label"] == "week 6 · session 1 of 3 · heavy · DELOAD"


def test_the_sequence_is_defined_once_in_program_structure():
    seq = program_structure.SESSION_SEQUENCE
    assert seq["block_start"] == "2026-09-24"
    assert seq["session_roles"] == [H, M, HM] and seq["sessions_per_week"] == 3 and seq["weeks_per_block"] == 6
    assert set(seq["session_roles"]) <= set(program_structure.SESSION_TEMPLATES)
    assert program_structure.summary()["session_sequence"] is seq
    # the weekday calendar is retired, not kept beside the sequence as a second answer
    for gone in ("BLOCK_CALENDAR", "block_calendar", "calendar_entry", "_session_dates"):
        assert not hasattr(program_structure, gone), gone


def test_deload_period_is_the_redlines_with_a_mutation_control():
    assert [p["week"] for p in session_sequence.preview(39) if p["deload"] and p["session_in_week"] == 1] == [6, 12]
    with patch.dict(owner_redlines.REDLINES["lifting_sessions_per_wk"]["deload"], {"every_nth_week": 4}):
        assert [p["week"] for p in session_sequence.preview(39) if p["deload"] and p["session_in_week"] == 1] == [4, 8, 12]


# ── 2. the issue's fixtures ──────────────────────────────────────────────────
def test_heavy_thu_walk_fri_walk_sat_then_sunday_serves_moderate():
    rows = [lift("2026-09-24"), walk("2026-09-25"), walk("2026-09-26")]
    sun = served("2026-09-27", rows)
    assert (sun["session_role"], sun["week"], sun["session_in_week"]) == (M, 1, 2)
    assert sun["position_label"] == "week 1 · session 2 of 3 · moderate"
    assert sun["advanced_by"]["date"] == "2026-09-24" and sun["advanced_by"]["was"] == "week 1 · session 1 of 3 · heavy"
    # the audible postponed the moderate session: Fri, Sat AND Sun all serve it
    for d in ("2026-09-25", "2026-09-26", "2026-09-27"):
        assert served(d, rows)["session_role"] == M, d


def test_two_skipped_sessions_do_not_advance_the_week():
    rows = [lift("2026-09-24"), lift("2026-09-26"), lift("2026-09-28")]
    assert served("2026-09-29", rows)["week"] == 2
    # the same fortnight with the second and third sessions audibled to walks
    skipped = [lift("2026-09-24"), walk("2026-09-26"), walk("2026-09-28")] + [walk(f"2026-10-0{n}") for n in range(1, 7)]
    e = served("2026-10-07", skipped)
    assert (e["week"], e["session_role"], e["completed_sessions"]) == (1, M, 1)


def test_engine_days_warmup_only_logs_and_rest_days_never_advance():
    rows = [lift("2026-09-24"), engine("2026-09-25"), warmup_only("2026-09-26")]
    assert served("2026-09-28", rows)["session_role"] == M  # 09-27: nothing logged at all


def test_two_loaded_logs_on_one_day_are_one_session():
    rows = [lift("2026-09-24", start="2026-09-24T15:00:00Z", wid="b"), lift("2026-09-24", start="2026-09-24T14:00:00Z", wid="a")]
    e = served("2026-09-25", rows)
    assert e["completed_sessions"] == 1 and e["session_role"] == M
    assert e["advanced_by"]["workout_id"] == "a" and e["advanced_by"]["loaded_logs_that_day"] == 2


def test_sessions_before_the_block_start_and_on_the_planned_day_do_not_count():
    rows = [lift("2026-09-22"), lift("2026-09-23")]
    first = served("2026-09-24", rows)
    assert (first["session_role"], first["completed_sessions"], first["advanced_by"]) == (H, 0, None)
    # a session logged ON the planned day is the one that day's plan served — stable all day
    assert served("2026-09-24", rows + [lift("2026-09-24")])["session_role"] == H
    assert served("2026-09-25", rows + [lift("2026-09-24")])["session_role"] == M
    assert session_sequence.next_session("2026-09-23", rows) is None, "before the block start the weekday grid answers"


def test_tombstoned_rows_never_count():
    assert served("2026-09-25", [{**lift("2026-09-24"), "tombstone": True}])["session_role"] == H


def test_every_loaded_session_advances_seven_days_a_week():
    """Ruling: the optional 4th is retired as a slot — a 4th loaded session in seven days is the
    next session, and the redline's calendar ceiling is an ADVISORY beside it, never a skip."""
    rows = [lift(f"2026-09-{d}") for d in (24, 25, 26, 27)]
    e = served("2026-09-28", rows)
    assert (e["week"], e["session_role"]) == (2, M)
    assert e["spacing"]["loaded_yesterday"] is True and e["spacing"]["loaded_sessions_prior_7d"] == 4
    assert len(e["spacing"]["advisories"]) == 2


# ── 3. the mutation control ──────────────────────────────────────────────────
def test_mutation_control_a_walk_that_advances_the_position_reds_the_fixture():
    rows = [lift("2026-09-24"), walk("2026-09-25"), walk("2026-09-26")]
    with patch.object(training_streaks, "is_loaded_session", lambda w: True):
        sun = session_sequence.next_session("2026-09-27", rows)
    assert sun["session_role"] != M, "with walks counted, Sunday is no longer the moderate session — the fixture can fail"
    assert sun["completed_sessions"] == 3 and sun["week"] == 2


# ── 4. one week ──────────────────────────────────────────────────────────────
def _sessions(n: int) -> list[dict]:
    from common.pacific_time import shift_day_key

    return [lift(shift_day_key("2026-09-24", i)) for i in range(n)]


@pytest.mark.parametrize("n_done", [0, 2, 3, 14, 15, 17, 18])
def test_the_gate_the_session_and_the_ramp_read_one_week(n_done):
    from common.pacific_time import shift_day_key

    rows = _sessions(n_done)
    day = shift_day_key("2026-09-24", n_done + 1)
    week = plan_engine.program_week(day, rows)
    assert week == n_done // 3 + 1
    block = plan_engine.constraint_block(date=day, block_workouts=rows)
    assert block["program_week"] == week == block["session"]["week"]
    anchor = next(t for t in block["tripwires"] if t["id"] == "anchor_lift_strength_drop")
    assert (anchor["state"] == "not_yet_active") == (week < 6)
    # the ramp is handed the served session's week (full_body_session reads day_entry['week'])
    with patch("training.load_ramp.ramp_floor", side_effect=lambda f, w: {**f, "_week": w}) as rf:
        _generate(day, block_workouts=rows)
    assert {c.args[1] for c in rf.call_args_list} <= {week}


def test_program_week_is_zero_before_the_block_and_unknown_when_unread():
    assert plan_engine.program_week("2026-09-23") == 0
    assert plan_engine.program_week("2026-09-24", None) is None
    assert plan_engine.program_week("2026-09-24", []) == 1
    assert plan_engine.program_week("not-a-day", []) is None


# ── 5. the surfaces ──────────────────────────────────────────────────────────
def _generate(day: str, **kw):
    with patch.object(routine_generator, "_load_note_indexes", return_value=({}, {}, {}, {})):
        return routine_generator.generate_routines(routine_generator.GeneratorInputs(target_date=day, **kw))


def test_constraint_block_names_the_position_and_what_advanced_it():
    rows = [lift("2026-09-24", title="Foundation - Full Body - 1 - 1"), walk("2026-09-25"), walk("2026-09-26")]
    block = plan_engine.constraint_block(date="2026-09-27", block_workouts=rows)
    s = block["session"]
    assert s["source"] == "session_sequence" and s["position_label"] == "week 1 · session 2 of 3 · moderate"
    assert s["advanced_by"]["title"] == "Foundation - Full Body - 1 - 1"
    assert s["prescription"]["session_role"] == M
    assert block["inputs"]["block_workouts"]["state"] == "measured"


def test_an_unread_record_is_unknown_never_session_one():
    block = plan_engine.constraint_block(date="2026-09-27")
    assert block["session"]["source"] == "sequence_unreadable" and "prescription" not in block["session"]
    assert block["program_week"] is None
    assert block["inputs"]["block_workouts"]["state"] == "not_supplied"


def test_generator_serves_the_sequence_on_a_day_the_old_calendar_called_a_walk():
    rows = [lift("2026-09-24"), walk("2026-09-25"), walk("2026-09-26")]
    ideal = _generate("2026-09-27", block_workouts=rows)[0]  # Sunday: a walk under #4064's calendar
    assert ideal.archetype == "full" and ideal.title.startswith("Full Body MODERATE — W1")
    assert ideal.inputs_snapshot["calendar"]["position_label"] == "week 1 · session 2 of 3 · moderate"
    assert any("session sequence: week 1 · session 2 of 3 · moderate" in r and "advanced by 2026-09-24" in r for r in ideal.rationale)


def test_generator_reads_the_record_itself_when_the_caller_did_not_and_says_so_when_it_cannot():
    with patch.object(session_sequence, "load_block_workouts", return_value=[lift("2026-09-24")]) as ld:
        assert _generate("2026-09-25")[0].title.startswith("Full Body MODERATE")
    ld.assert_called_once_with("2026-09-25")
    with patch.object(session_sequence, "load_block_workouts", side_effect=RuntimeError("ddb down")):
        routines = _generate("2026-09-27")  # Sunday — the weekday grid's walk
    assert routines[0].archetype == "aerobic"
    assert any("session sequence UNREADABLE" in r for r in routines[0].rationale)


def test_inactive_program_never_reads_the_sequence():
    with (
        patch.object(program_structure, "ACTIVE", False),
        patch.object(session_sequence, "load_block_workouts", side_effect=AssertionError("sequence read under an inactive program")),
        patch.object(session_sequence, "next_session", side_effect=AssertionError("sequence read under an inactive program")),
    ):
        _generate("2026-09-27")


def test_plan_next_session_through_the_mcp_handler_serves_the_next_undone_session():
    from mcp import handler as h
    from tests.test_fullbody_block_calendar_4064 import _stage1_patches

    rows = [lift("2026-09-24"), walk("2026-09-25"), walk("2026-09-26")]
    with ExitStack() as st:
        for cm in _stage1_patches():
            st.enter_context(cm)
        st.enter_context(patch("mcp.tools_plan._block_workouts", return_value=rows))
        st.enter_context(patch.object(h, "_emit_tool_metric"))
        st.enter_context(patch.object(h, "_audit_tool_call"))
        resp = h.handle_tools_call({"name": "plan_next_session", "arguments": {"target_date": "2026-09-27"}})
    out = json.loads(resp["content"][0]["text"])
    s = out["constraint_block"]["session"]
    assert (s["source"], s["session_role"], s["position_label"]) == ("session_sequence", M, "week 1 · session 2 of 3 · moderate")
    assert s["advanced_by"]["date"] == "2026-09-24"
    assert out["constraint_block"]["program_week"] == 1


def test_the_mcp_reader_uses_the_sanctioned_hevy_path_from_the_block_start():
    from mcp import tools_plan

    with patch("mcp.tools_strength._read_hevy_all_phases", return_value=([lift("2026-09-24")], ["experiment"])) as rd:
        assert tools_plan._block_workouts("2026-09-27") == [lift("2026-09-24")]
    rd.assert_called_once_with("2026-09-24", "2026-09-26")
    with patch("mcp.tools_strength._read_hevy_all_phases", side_effect=AssertionError("nothing to read before the block")):
        assert tools_plan._block_workouts("2026-09-24") == []
