#!/usr/bin/env python3
"""config_provenance_audit.py — a generated `config/` object is graded against the CLOCK (#3785).

Why a THIRD check in this workflow
----------------------------------
`config_twin_sync` asks "does repo `config/x` equal `s3://…/config/x`?" and
`config_mirror_audit` asks "what OWNS each live object?". Both are right and
neither can see the failure this file exists for.

On 2026-09-14 an ad-hoc `aws s3 cp` pushed the repo's copy of
`config/hevy_template_index.json` — a June-1 hand build, 789 templates — over the
live generated index of 820. `draft_custom` silently lost 39 templates. The daily
**Config twin drift** workflow was GREEN for **nine consecutive runs** across that
window, and the reason is the finding:

    while the clobber was active, live read 789 and the committed twin read 789.
    They AGREED.

A comparison gate is structurally blind in exactly the state that matters, because
it compares two artifacts capable of being wrong **together**. A green from it
means *"these two agree"*, never *"this one is right"*. The existing CloudWatch
dead-man (`hevy-template-index-not-rebuilt-48h`) is blind for a different reason:
it watches the PRODUCER's `TemplateIndexRebuilt` emit, and the producer was firing
perfectly — a silent revert followed by a silent repair at the next 13:40Z run.

The discriminator was there the whole time. **Only the generated object carries
`_built_at`**; the stale committed twin predates the producer and carries none. So
this audit grades ONE artifact against the clock, and it is therefore not blind
when both sides are wrong: the moment the repo copy lands on S3, `_built_at`
disappears from live and this reds.

Everything here is DERIVED — nothing is a hand-maintained list
---------------------------------------------------------------
``enrolment``  A module under `lambdas/`/`mcp/` that (a) assigns a module-level
               string constant beginning with `config/` and (b) mentions
               `_built_at` in its source is declaring "I generate this object and
               I stamp it". Both halves are required: the constant alone is a
               reader's key, and the stamp alone is some other module's payload.
               The next generated artifact enrols itself.
``cadence``    Read from the EventBridge rule in `cdk/stacks/` whose DESCRIPTION
               names the key. Never a number chosen in this file. A key whose
               cadence cannot be derived is a FINDING ("name the key in the rule
               description"), never a default — a guessed ceiling is how a
               freshness check becomes decorative.
``ceiling``    Two cadence periods, the same two-period reasoning as the existing
               `hevy-template-index-not-rebuilt-48h` alarm: one dropped run or one
               vendor 429 self-heals on tomorrow's rebuild without waking anyone.

Three assertions per enrolled key, and one inverse
--------------------------------------------------
1. **The stamp is present.** Its absence IS the clobber; nothing else needs to be
   compared. This is the assertion the nine green runs did not have.
2. **The stamp is fresh** — `_built_at` within the derived ceiling.
3. **The stamp is self-consistent** — `_sha256` recomputes over the payload it
   stamps. Catches a truncated or partial write, which neither (1) nor (2) can see.
4. **Inverse:** a live `config/` object that CARRIES `_built_at` but which no
   producer declares is reported. That is the symmetric blindness — an artifact
   generated by something outside the derivation, ageing with nobody watching.

Read-only: GetObject and ListObjectsV2, nothing else. Exit 1 under `--strict` on a
finding; a fetch failure is reported as UNKNOWN and never silently passes.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import sys
from datetime import datetime, timezone

BUCKET = os.environ.get("CONFIG_BUCKET", "matthew-life-platform")
PREFIX = "config/"
SOURCE_ROOTS = ("lambdas", "mcp")
CDK_ROOT = "cdk/stacks"
STAMP = "_built_at"
DIGEST = "_sha256"
# Two producer periods before a stale stamp is a finding — the same reasoning the
# `hevy-template-index-not-rebuilt-48h` alarm states: one dropped run or one vendor
# 429 self-heals on the next scheduled rebuild without waking anyone.
CEILING_PERIODS = 2


# ── enrolment: which config/ keys are GENERATED, derived from the producers ──


def declared_generated(repo="."):
    """{config key: "path:CONSTANT"} for every module that declares a `config/` key
    AND stamps provenance. Both halves required — see the module docstring."""
    out: dict[str, str] = {}
    for root in SOURCE_ROOTS:
        base = os.path.join(repo, root)
        for dirpath, _dirs, files in os.walk(base):
            if "__pycache__" in dirpath:
                continue
            for name in sorted(files):
                if not name.endswith(".py"):
                    continue
                path = os.path.join(dirpath, name)
                try:
                    src = open(path, encoding="utf-8").read()
                except OSError:
                    continue
                if STAMP not in src:
                    continue  # cheap pre-filter only — the real test is the AST below
                try:
                    tree = ast.parse(src)
                except SyntaxError:
                    continue
                # The stamp leg must be a dict KEY the module actually constructs, not a
                # substring. A `grep`-shaped check reads docstrings and comments too, so
                # a producer that STOPS stamping — the exact self-erasure this audit's
                # ratchet exists to catch — kept its enrolment through a mention on a
                # comment line. Caught by that ratchet's own must-fail control, which
                # passed when it should have failed.
                if not any(
                    isinstance(n, ast.Dict) and any(isinstance(k, ast.Constant) and k.value == STAMP for k in n.keys)
                    for n in ast.walk(tree)
                ):
                    continue
                for node in tree.body:
                    if not isinstance(node, ast.Assign):
                        continue
                    value = node.value
                    if not (isinstance(value, ast.Constant) and isinstance(value.value, str)):
                        continue
                    if not value.value.startswith(PREFIX):
                        continue
                    for target in node.targets:
                        if isinstance(target, ast.Name):
                            rel = os.path.relpath(path, repo)
                            out[value.value] = f"{rel}:{target.id}"
    return out


# ── cadence: read from the EventBridge rule whose description names the key ──


def _cron_period_seconds(fields: dict) -> int | None:
    """Seconds between firings for a `Schedule.cron(...)` kwarg map, or None when the
    shape is one this function cannot read honestly."""

    def fixed(key):
        v = fields.get(key)
        return v if isinstance(v, str) and v not in ("*", "?") and "," not in v and "/" not in v and "-" not in v else None

    if any(k in fields for k in ("day", "week_day", "month", "year")):
        return None  # not a plain daily/hourly rule — do not guess
    if fixed("minute") and fixed("hour"):
        return 86400
    if fixed("minute") and fields.get("hour") in (None, "*"):
        return 3600
    return None


def declared_cadence(repo="."):
    """{config key: (seconds, "cdk/stacks/x.py")} from rule DESCRIPTIONS naming the key."""
    out: dict[str, tuple[int, str]] = {}
    base = os.path.join(repo, CDK_ROOT)
    for dirpath, _dirs, files in os.walk(base):
        for name in sorted(files):
            if not name.endswith(".py"):
                continue
            path = os.path.join(dirpath, name)
            try:
                src = open(path, encoding="utf-8").read()
            except OSError:
                continue
            if PREFIX not in src:
                continue
            try:
                tree = ast.parse(src)
            except SyntaxError:
                continue
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                fname = func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", "")
                if fname != "Rule":
                    continue
                kwargs = {k.arg: k.value for k in node.keywords}
                desc = kwargs.get("description")
                if not (isinstance(desc, ast.Constant) and isinstance(desc.value, str)):
                    continue
                sched = kwargs.get("schedule")
                if not isinstance(sched, ast.Call):
                    continue
                fields = {k.arg: k.value.value for k in sched.keywords if isinstance(k.value, ast.Constant)}
                period = _cron_period_seconds(fields)
                if period is None:
                    continue
                for token in desc.value.split():
                    key = token.strip(",.;:'\"")
                    if key.startswith(PREFIX):
                        out[key] = (period, os.path.relpath(path, repo))
    return out


# ── the assertions ───────────────────────────────────────────────────────────


def assess(key, body, *, ceiling_seconds, now=None):
    """Pure assessor: (ok, code, message) for ONE live object's provenance.

    `body` is the parsed live JSON, or None when the object is absent/unreadable.
    `ceiling_seconds` is None when the cadence could not be derived — reported, not
    papered over with a default.
    """
    now = now or datetime.now(timezone.utc)
    if body is None:
        return False, "unreadable", f"{key}: live object absent or not JSON — nothing to grade"
    if not isinstance(body, dict) or STAMP not in body:
        return (
            False,
            "no-stamp",
            (
                f"{key}: the live object carries NO {STAMP}. A generated artifact has been replaced by "
                "something that does not stamp itself — most likely a hand-owned or committed copy pushed "
                "over it. This is the #3785 clobber, and a comparison against that same copy cannot see it."
            ),
        )
    raw = body.get(STAMP)
    try:
        built = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
        if built.tzinfo is None:
            built = built.replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return False, "bad-stamp", f"{key}: {STAMP}={raw!r} is not an ISO instant"
    age = (now - built).total_seconds()
    if age < 0:
        return False, "future-stamp", f"{key}: {STAMP}={raw} is in the FUTURE by {-age:.0f}s"

    digest_msg = ""
    declared = body.get(DIGEST)
    if declared:
        payload = body.get("templates")
        if isinstance(payload, dict):
            recomputed = hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()
            if recomputed != declared:
                return (
                    False,
                    "digest-mismatch",
                    (
                        f"{key}: {DIGEST} declares {str(declared)[:16]}… but the payload hashes to "
                        f"{recomputed[:16]}… — a partial or corrupted write. Neither the stamp's presence nor "
                        "its age can see this."
                    ),
                )
            digest_msg = f", {DIGEST} verified"

    if ceiling_seconds is None:
        return (
            False,
            "no-cadence",
            (
                f"{key}: stamped {age / 3600:.1f}h ago but NO producer cadence is derivable — no EventBridge "
                f"rule description in {CDK_ROOT}/ names this key, so there is no honest ceiling to grade "
                "against. Name the key in the rule's description rather than picking a number here."
            ),
        )
    if age > ceiling_seconds:
        return (
            False,
            "stale",
            (
                f"{key}: {STAMP} is {age / 3600:.1f}h old, past the {ceiling_seconds / 3600:.0f}h ceiling "
                f"({CEILING_PERIODS} producer periods). The rebuild is not reaching the object."
            ),
        )
    return True, "fresh", f"{key}: {STAMP} {age / 3600:.1f}h old, within the {ceiling_seconds / 3600:.0f}h ceiling{digest_msg}"


# ── live read + report ───────────────────────────────────────────────────────


def _s3():
    import boto3

    return boto3.client("s3", region_name=os.environ.get("AWS_REGION", "us-west-2"))


def _get_json(s3, key):
    try:
        return json.loads(s3.get_object(Bucket=BUCKET, Key=key)["Body"].read().decode("utf-8", "replace"))
    except Exception:
        return None


def _live_stamped_keys(s3):
    """Live `config/*.json` objects that carry a provenance stamp — the inverse read."""
    out = []
    token = None
    while True:
        kw = {"Bucket": BUCKET, "Prefix": PREFIX}
        if token:
            kw["ContinuationToken"] = token
        resp = s3.list_objects_v2(**kw)
        for obj in resp.get("Contents", []):
            key = obj["Key"]
            if key.endswith(".json") and obj.get("Size", 0) < 5_000_000:
                body = _get_json(s3, key)
                if isinstance(body, dict) and STAMP in body:
                    out.append(key)
        if not resp.get("IsTruncated"):
            return out
        token = resp.get("NextContinuationToken")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--strict", action="store_true", help="exit 1 on any finding")
    ap.add_argument("--repo", default=".")
    args = ap.parse_args(argv)

    enrolled = declared_generated(args.repo)
    cadence = declared_cadence(args.repo)

    print(f"config provenance — s3://{BUCKET}/{PREFIX} ({len(enrolled)} generated artifact(s) declared by their producers)")
    for key, who in sorted(enrolled.items()):
        secs = cadence.get(key, (None, None))[0]
        cad = f"{secs / 3600:.0f}h" if secs else "UNDERIVABLE"
        print(f"    {key}  <- {who}   cadence {cad}")

    if not enrolled:
        # The vacuity guard. An empty derivation would pass this check on every object
        # in the bucket, which is the exact shape #2019's residue had.
        print("::error::derivation returned NO generated artifacts — the audit would pass vacuously")
        return 1

    s3 = _s3()
    findings = []
    for key, who in sorted(enrolled.items()):
        secs = cadence.get(key, (None, None))[0]
        ceiling = secs * CEILING_PERIODS if secs else None
        ok, code, msg = assess(key, _get_json(s3, key), ceiling_seconds=ceiling)
        print(f"  {'🟢' if ok else '🔴'} {msg}")
        if not ok:
            findings.append((key, code, who))

    stamped = set(_live_stamped_keys(s3))
    orphans = sorted(stamped - set(enrolled))
    for key in orphans:
        print(f"  🟡 WARN {key}: carries {STAMP} but no producer under {'/'.join(SOURCE_ROOTS)} declares it — ageing unwatched")

    if findings:
        print(f"\n{len(findings)} generated artifact(s) failed their provenance check:")
        for key, code, who in findings:
            print(f"    {key}  [{code}]  producer {who}")
        print("\nDo NOT fix this by committing the live bytes over the repo copy — that greens a comparison")
        print("check and buries the question of who wrote the object (#3785).")
        return 1 if args.strict else 0
    print(f"\n🟢 every declared generated artifact carries a fresh provenance stamp ({len(orphans)} unwatched stamped object(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
