#!/usr/bin/env python3
"""
deploy/doc_restamp_guard.py — THE GENERIC RE-STAMP RULE (epic #2986, folded #2838).

  A sync/apply run may only advance a freshness date on content it actually
  regenerated or verified. It must NEVER advance a date stamp on a block whose
  content bytes it did not touch or re-derive.

WHY THIS IS A MODULE AND NOT SIX MORE PER-LITERAL FIXES
  The rule already existed three times, once per literal, each time discovered by an
  incident:
    • `scripts/doc_facts_ops.py` CHECK D3 — the secret_count `live-verified` stamp
      goes stale after 90d, because the count cannot be derived from the repo and the
      doc-sync was re-stamping "Last updated" over a number nobody had checked since
      2026-07-10 ("manufactured freshness").
    • `deploy/sync_doc_secret_inventory.py` — the same fact's explicit refresh command,
      which writes the literal AND its verification date together.
    • `docs/MCP_TOOL_CATALOG.md` — a body a month stale under a stamp the reconcile bot
      refreshed every single day (the observation that seeded epic #2986).
  Three instances, one rule, no standing statement of it. This module is the standing
  statement: it is derived from `sync_doc_metadata.RULES` itself, so a NEW stamped
  literal is covered the moment it is added — nobody has to remember to enrol it.

THE TWO VERIFICATION SIGNALS (both mean "this run touched the content")
  1. RE-DERIVED IN THIS RUN — the sync itself rewrote a non-date literal in the doc.
     The stamp then travels with content the run demonstrably re-derived.
  2. REGENERATED BY ANOTHER WRITER — the doc's non-date bytes already differ from
     `HEAD`, i.e. a generator (`generate_mcp_tool_catalog.py`, `generate_platform_model.py`,
     the alarm inventory sync, a human's edit) rewrote the body in this working tree
     before the sync ran. This is the MCP_TOOL_CATALOG case done honestly.
  Neither signal ⇒ the stamp is HELD at its existing value. A held stamp is not drift:
  `--check` has ignored date-only differences since #2649, so holding can never red CI.
  It simply stops the machine from manufacturing freshness.

WHY DATE-MASKED COMPARISON, NOT A PLAIN BYTE COMPARE
  Staling a stamp is itself a byte change. A naive `text != HEAD` would call a
  yesterday-dated header "regenerated" and re-stamp it — the exact bug, laundered
  through a diff. Every comparison here masks `YYYY-MM-DD` first, so only SUBSTANCE
  counts as regeneration (the same per-change masking #2649 established, reused rather
  than re-invented).

FAIL-CLOSED
  If the HEAD content cannot be read (no git, detached object store, a path git does
  not know), `regenerated_by_another_writer()` returns False and the stamp is held.
  A stamp that stays honest-but-old is a smaller lie than one that is advanced without
  evidence — and the epic exists because the platform kept choosing the larger one.

Guard: `tests/test_doc_restamp_rule_2986.py` (mutation-proves both directions over the
SET of stamped rules discovered from `sync_doc_metadata.RULES`).
"""

from __future__ import annotations

import re
import subprocess  # nosec B404 — fixed argv `git show`, no shell
from pathlib import Path

# The placeholder that makes a replacement template a FRESHNESS STAMP. This one token is
# the whole enrolment mechanism: `stamped_rules()` derives the guarded SET from it, so a
# new stamped literal joins the guard by existing, never by being listed somewhere.
STAMP_PLACEHOLDER = "{date}"

# Prefix for the "stamp held" line in a sync run's per-doc report. It is deliberately NOT
# the "  ~ " (drift) or "  ! " (rule broken) prefix — a hold is a correct outcome, so the
# caller must not count it as a stale literal.
HOLD_PREFIX = "  · "

_DATE_STAMP_RE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")


def mask_dates(text: str) -> str:
    """`text` with every YYYY-MM-DD replaced by a fixed token, so comparisons see substance."""
    return _DATE_STAMP_RE.sub("<date>", text)


def differs_only_by_date_stamp(old: str, new: str) -> bool:
    """True when `old` and `new` are identical once every YYYY-MM-DD is masked.

    #2649's contract, unchanged and now shared: a date-only difference is not drift, and
    the masking is PER-CHANGE rather than per-line because `docs/ARCHITECTURE.md` carries
    the date and the Lambda count on the same line.
    """
    return mask_dates(old) == mask_dates(new)


def stamped_rules(rules) -> list:
    """The guarded SET: every `(doc, pattern, template)` whose template stamps a date.

    Derived from the sync tool's own rule table — guard the SET, not an instance list.
    """
    return [r for r in rules if STAMP_PLACEHOLDER in r[2]]


def stamped_docs(rules) -> list[str]:
    """Sorted doc paths carrying at least one freshness stamp."""
    return sorted({r[0] for r in stamped_rules(rules)})


def _git(root: Path, *args: str) -> subprocess.CompletedProcess | None:
    """Run a read-only git command, or None when git cannot be run at all."""
    try:
        return subprocess.run(  # nosec B603 B607 — fixed argv, no shell, read-only
            ["git", *args],
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None


def head_text(root: Path, rel_path: str) -> str | None:
    """Committed (`HEAD`) content of `rel_path`.

    Returns `""` when git knows the tree but not the path (a brand-new file), and None
    when git could not answer at all (no binary, no repo, no commits) — the fail-closed
    case the caller must treat as "cannot verify".
    """
    shown = _git(root, "show", f"HEAD:{rel_path}")
    if shown is None:
        return None
    if shown.returncode == 0:
        return shown.stdout
    head = _git(root, "rev-parse", "--verify", "--quiet", "HEAD")
    if head is not None and head.returncode == 0:
        return ""  # HEAD resolves, the path does not exist in it: the file is new
    return None


def regenerated_by_another_writer(root: Path, rel_path: str, current_text: str) -> bool:
    """Signal 2 — did something else rewrite this doc's SUBSTANCE in this working tree?

    True when the doc is new to `HEAD` or its date-masked content differs from `HEAD`.
    False when only dates moved, or when git cannot answer (fail-closed: hold the stamp).
    """
    head = head_text(root, rel_path)
    if head is None:
        return False
    return mask_dates(head) != mask_dates(current_text)


def may_restamp(*, rederived_in_run: bool, regenerated: bool) -> bool:
    """THE RULE, in one expression. Either verification signal licenses the stamp."""
    return bool(rederived_in_run or regenerated)


def hold_note(rel_path: str, held: int) -> str:
    """The report line for a held stamp — legible in CI logs, not counted as drift."""
    plural = "" if held == 1 else "s"
    return (
        f"{HOLD_PREFIX}held {held} date re-stamp{plural} on {rel_path}: this run neither re-derived "
        f"a literal here nor found regenerated content (#2986 — no manufactured freshness)"
    )


def resolve(root: Path, rel_path: str, original: str, current: str, held: list, rederived: bool) -> tuple[str, list[str]]:
    """Settle a doc's deferred date-only rewrites. Returns `(text, report_lines)`.

    `held` is the list of `(pattern, replacement)` rewrites the caller withheld because
    they moved nothing but a date. They are applied only when a verification signal says
    the run earned them; otherwise the text is returned unstamped and the report explains
    why. `original` (not `current`) is the pre-run text — the regeneration signal must be
    read from what the doc looked like BEFORE this sync touched any literal.
    """
    if not held:
        return current, []
    if may_restamp(rederived_in_run=rederived, regenerated=regenerated_by_another_writer(root, rel_path, original)):
        for pattern, replacement in held:
            current = re.sub(pattern, replacement, current)
        return current, []
    return current, [hold_note(rel_path, len(held))]
