"""deploy/doc_alarm_inventory.py — the machine-maintained alarm inventory in MONITORING.md (#934).

Split out of ``deploy/sync_doc_metadata.py`` (#2649): that script is at its recorded
size ceiling (`tests/test_module_size_guard.py`), and the guard's rule is to pay for
new lines out of an extracted sibling rather than raise the number.

The inventory is regenerated from the CDK-derived alarm-name set so MONITORING.md can
never again name a CloudWatch alarm that no stack defines (the SRE-grader phantom-name
finding — #932 hand-fixed, #934 gates).

**Discovery is injected, not imported.** ``sync(dry_run, by_stack)`` takes the
already-discovered ``{stack_stem: [names]}`` mapping, so this module never imports its
parent and there is no cycle. It also keeps the AST discovery patchable in exactly one
place (the parent), rather than making a re-export look like a patch point when it is
not.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MONITORING_PATH = ROOT / "docs" / "MONITORING.md"

ALARM_INV_BEGIN = "<!-- BEGIN GENERATED: alarm-inventory — deploy/sync_doc_metadata.py (#934); do not hand-edit -->"
ALARM_INV_END = "<!-- END GENERATED: alarm-inventory -->"


def render(by_stack: dict) -> str:
    """Render the marker-delimited inventory block from `{stack_stem: [names]}`."""
    total = sum(len(v) for v in by_stack.values())
    lines = [
        ALARM_INV_BEGIN,
        "",
        f"_**{total}** CloudWatch alarms are defined in `cdk/stacks/*.py` and AST-discovered by "
        "`deploy/sync_doc_metadata.py::_auto_discover_alarm_names` (#795 counts them, #934 names them). "
        "Regenerated by `python3 deploy/sync_doc_metadata.py --apply` and gated by `--check`: add / rename / "
        "remove an alarm in CDK and this updates automatically; a name here that no stack defines reds CI._",
        "",
    ]
    for stem in sorted(by_stack):
        names = by_stack[stem]
        lines.append(f"**`{stem}.py`** ({len(names)})")
        lines.append("")
        lines.extend(f"- `{n}`" for n in names)
        lines.append("")
    lines.append(ALARM_INV_END)
    return "\n".join(lines)


def sync(dry_run: bool, by_stack: dict | None) -> list[str]:
    """Regenerate MONITORING.md's alarm-inventory block from the CDK-derived name set."""
    if not MONITORING_PATH.exists():
        return [f"  SKIP (not found): {MONITORING_PATH}"]
    if by_stack is None:
        return ["  ! alarm-name discovery returned None (cdk/stacks/*.py unreadable?) — inventory NOT verified"]
    src = MONITORING_PATH.read_text(encoding="utf-8")
    begin = src.find(ALARM_INV_BEGIN)
    end = src.find(ALARM_INV_END)
    if begin == -1 or end == -1 or end < begin:
        return ["  ! alarm-inventory markers missing from docs/MONITORING.md — add the BEGIN/END GENERATED: alarm-inventory pair (#934)"]
    expected = render(by_stack)
    current = src[begin : end + len(ALARM_INV_END)]
    if current == expected:
        return []
    new_src = src[:begin] + expected + src[end + len(ALARM_INV_END) :]
    if not dry_run:
        MONITORING_PATH.write_text(new_src, encoding="utf-8")
    total = sum(len(v) for v in by_stack.values())
    return [f"  ~ alarm inventory regenerated ({total} alarms across {len(by_stack)} stacks, from cdk/stacks/*.py)"]
