#!/bin/bash
# =============================================================================
# v4_cutover.sh — big-bang cutover to "The Measured Life" (one engine, three doors)
# =============================================================================
# Matthew runs this in the terminal. Claude Code does NOT execute it (deploy
# discipline). It only touches S3 (site/ prefix) + CloudFront — never the engine.
#
# WHAT IT DOES
#   1. Pre-flight gates (block the cutover if anything's off):
#        - migration inventory: 0 unmapped
#        - all three doors present + well-formed; legacy tree intact (84 pages)
#        - tokens.css present
#   2. Generates the edge redirect artifact from redirects.map (you apply it to
#      CloudFront — see step 2 output). 301s every old URL to its v4 home.
#   3. Syncs site/ to s3://matthew-life-platform/site/ via the safe wrapper
#      (never `aws s3 sync --delete` at bucket root — ADR-032/033/046).
#   4. Invalidates CloudFront (us-east-1).
#   5. Prints the post-cutover verification commands.
#
# ─────────────────────────────────────────────────────────────────────────────
# CONFIRM BEFORE RUNNING — the 6 judgement calls baked into redirects.map
# (flip in scripts/v4_migration_inventory.py RULES, then re-run it, if any are wrong):
#     status        -> Cockpit (/cockpit)        [System if it's uptime/freshness]
#     achievements  -> Cockpit (/cockpit)        [could surface in Story]
#     field-notes   -> Story (/)             [Cockpit if it's a live panel]
#     community     -> Story (/)             [System if a functional signup]
#     results       -> Evidence              [could anchor a Story beat]
#     ask           -> Evidence              [verify intent — it's interactive]
#   archive/v1/**   -> /legacy (preserved verbatim, noindex)
#
# ─────────────────────────────────────────────────────────────────────────────
# ROLLBACK (one flip)
#   The legacy site is preserved byte-content-verbatim under /legacy and the
#   pre-cutover deploy is recoverable two ways:
#     a) git:  `git revert <cutover-commit>` (or checkout the pre-v4 tag) then
#              re-run deploy/deploy_site.sh — restores the old site/ tree.
#     b) edge: remove/disable the CloudFront redirect function from step 2;
#              old URLs resolve to their preserved files again.
#   S3 object versioning on the bucket also retains the prior objects.
# =============================================================================
set -euo pipefail

BUCKET="matthew-life-platform"
DISTRIBUTION_ID="E3S424OXQZ8NBE"
SITE_DIR="site"
GEN_DIR="deploy/generated"

cd "$(git rev-parse --show-toplevel)"

echo "═══ v4 CUTOVER — The Measured Life ═══"
echo

# ── 1. Pre-flight gates ──────────────────────────────────────────────────────
echo "[1/5] Pre-flight gates…"

python3 scripts/v4_migration_inventory.py >/tmp/v4_inv.txt 2>&1 || { cat /tmp/v4_inv.txt; echo "❌ inventory gate failed"; exit 1; }
grep -q "PASS: every preserved page maps" /tmp/v4_inv.txt || { cat /tmp/v4_inv.txt; echo "❌ inventory not PASS"; exit 1; }
echo "  ✓ migration inventory: 0 unmapped"

for f in "$SITE_DIR/index.html" "$SITE_DIR/cockpit/index.html" "$SITE_DIR/evidence/index.html" "$SITE_DIR/assets/css/tokens.css"; do
  [ -f "$f" ] || { echo "❌ missing required v4 file: $f"; exit 1; }
done
echo "  ✓ three doors + tokens present"

LEGACY_PAGES=$(find "$SITE_DIR/legacy" -name '*.html' 2>/dev/null | wc -l | tr -d ' ')
[ "$LEGACY_PAGES" -ge 80 ] || { echo "❌ legacy tree looks incomplete ($LEGACY_PAGES pages)"; exit 1; }
echo "  ✓ legacy preserved ($LEGACY_PAGES pages)"

python3 - <<'PY' || { echo "❌ HTML well-formedness check failed"; exit 1; }
from html.parser import HTMLParser
import glob, sys
bad = 0
for f in glob.glob("site/**/*.html", recursive=True):
    try:
        HTMLParser(convert_charrefs=True).feed(open(f, encoding="utf-8").read())
    except Exception as e:
        print("  PARSE FAIL", f, e); bad += 1
sys.exit(1 if bad else 0)
PY
echo "  ✓ all HTML well-formed"
echo

# ── 2. Edge redirect artifact (you apply this to CloudFront) ─────────────────
echo "[2/5] Generating edge redirect function from redirects.map…"
mkdir -p "$GEN_DIR"
python3 - <<'PY'
import json
pairs = []
with open("redirects.map", encoding="utf-8") as fh:
    for line in fh:
        line = line.rstrip("\n")
        if not line or "\t" not in line:
            continue
        old, new = line.split("\t", 1)
        pairs.append((old, new))
table = {o: n for o, n in pairs}
js = (
    "// AUTO-GENERATED by deploy/v4_cutover.sh from redirects.map — do not hand-edit.\n"
    "// CloudFront Function (viewer-request). Apply to distribution E3S424OXQZ8NBE.\n"
    "var R = " + json.dumps(table, indent=0) + ";\n"
    "function handler(event) {\n"
    "  var req = event.request;\n"
    "  var uri = req.uri;\n"
    "  if (uri.length > 1 && uri.charAt(uri.length-1) !== '/' && uri.indexOf('.') === -1) uri += '/';\n"
    "  var dst = R[uri];\n"
    "  if (dst) {\n"
    "    return { statusCode: 301, statusDescription: 'Moved Permanently',\n"
    "             headers: { 'location': { value: dst } } };\n"
    "  }\n"
    "  return req;\n"
    "}\n"
)
open("deploy/generated/v4_redirects_function.js", "w", encoding="utf-8").write(js)
print(f"  ✓ wrote deploy/generated/v4_redirects_function.js ({len(table)} 301s)")
PY
echo "  → APPLY (one-time, via console or CLI): publish this as a CloudFront Function"
echo "    associated with the default behaviour as viewer-request, then re-invalidate."
echo "    (Rollback = disassociate the function.)"
echo

read -r -p "Pre-flight passed. Proceed to sync site/ to S3 and invalidate? [y/N] " ok
[ "$ok" = "y" ] || { echo "Aborted before any S3/CloudFront change."; exit 0; }

# ── 3. Sync site/ to S3 (safe wrapper — no --delete at bucket root) ──────────
echo "[3/5] Syncing $SITE_DIR/ to s3://$BUCKET/site/ …"
if [ -f "deploy/sync_site_to_s3.sh" ]; then
  bash deploy/sync_site_to_s3.sh
else
  echo "❌ deploy/sync_site_to_s3.sh not found"; exit 1
fi

# ── 4. Invalidate CloudFront ─────────────────────────────────────────────────
echo "[4/5] Invalidating CloudFront ($DISTRIBUTION_ID)…"
aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*" >/dev/null
echo "  ✓ invalidation requested"

# ── 5. Verify ────────────────────────────────────────────────────────────────
echo "[5/5] Cutover deploy done. Verify:"
echo "  • Doors:    curl -sI https://averagejoematt.com/ ; /cockpit ; /evidence/"
echo "  • Redirect: curl -sI https://averagejoematt.com/training/   # expect 301 -> /evidence/training/"
echo "  • Legacy:   curl -sI https://averagejoematt.com/legacy/      # preserved, noindex"
echo "  • Visual:   python3 tests/visual_qa.py            # green across the three doors"
echo "  • Crawl:    python3 tests/validate_links.py       # no unintended 404s"
echo
echo "If anything is wrong: see ROLLBACK in this script's header."
