#!/usr/bin/env python3
"""
Patch role_policies.py to add email_chronicle_sender() policy function (BS-03).

Run from project root:
  python3 deploy/patch_role_policies_bs03.py

Idempotent — skips if function already present.
"""

import sys
from pathlib import Path

TARGET = Path(__file__).parent.parent / "cdk/stacks/role_policies.py"

NEW_FUNCTION = '''

def email_chronicle_sender() -> list[iam.PolicyStatement]:
    """Chronicle email sender (BS-03): reads DDB (chronicle + subscribers), KMS, SES send, DLQ.
    No ai-keys — content is pre-generated by wednesday-chronicle and stored in DDB.
    No S3 read — no config or file reads needed.
    Separate from wednesday-chronicle IAM by design (Board: independent failure domains).
    """
    return [
        iam.PolicyStatement(
            sid="DynamoDB",
            actions=["dynamodb:GetItem", "dynamodb:Query"],
            resources=[TABLE_ARN],
        ),
        iam.PolicyStatement(
            sid="KMS",
            actions=["kms:Decrypt"],
            resources=[KMS_KEY_ARN],
        ),
        iam.PolicyStatement(
            sid="SES",
            actions=["ses:SendEmail", "sesv2:SendEmail"],
            resources=[SES_IDENTITY],
        ),
        iam.PolicyStatement(
            sid="DLQ",
            actions=["sqs:SendMessage"],
            resources=[DLQ_ARN],
        ),
    ]
'''

content = TARGET.read_text()

if "email_chronicle_sender" in content:
    print("✅ email_chronicle_sender() already present in role_policies.py — skipping")
    sys.exit(0)

# Insert after email_evening_nudge function (find its last closing bracket before next def/class)
ANCHOR = "def email_evening_nudge()"
if ANCHOR not in content:
    print(f"❌ Anchor '{ANCHOR}' not found in role_policies.py")
    sys.exit(1)

# Find the end of email_evening_nudge by locating the next top-level def or comment block after it
anchor_idx = content.index(ANCHOR)
# Find next top-level def after anchor
import re
# Top-level defs start at column 0 after the anchor
search_from = anchor_idx + len(ANCHOR)
next_def = re.search(r'\ndef [a-z]', content[search_from:])
if next_def:
    insert_pos = search_from + next_def.start()
else:
    insert_pos = len(content)

new_content = content[:insert_pos] + NEW_FUNCTION + content[insert_pos:]
TARGET.write_text(new_content)
print(f"✅ email_chronicle_sender() added to {TARGET}")
print("   Next step: npx cdk deploy LifePlatformEmail")
