"""
token_alarm_window.py — genesis rebuild token-alarm suppression window (#1961).

Same shape as `_TEMP_CEILING_WINDOW` in `lambdas/operational/cost_governor_lambda.py`
(ADR-133): a dated `[start, end)` window, consulted by code at evaluation time, so
behavior auto-reverts by plain date comparison — no deploy or manual step is needed
to revert once the window has passed.

Why this exists: a reset's post-genesis full-cycle rebuild (character sheet +
compute + coach dossiers + chronicle backfill all regenerate in the days right
after genesis) predictably spikes Anthropic output-token usage well above the
platform's steady-state daily baseline. `cdk/stacks/monitoring_stack.py`'s fixed
150,000-token `ai-tokens-platform-daily-total` alarm has no reset-window
awareness, so this PREDICTED spike pages the urgent topic exactly like an
unexplained runaway (#1961 — cycle 11's genesis stamped 2026-07-27, and the alarm
fired ALARM on 2026-07-26 daily sums of 169,444 and 183,414 against the 150,000
threshold; the remediation agent's own triage ack for that run called the spike
"expected during full-cycle rebuilds"). The genesis date itself can land a
calendar day either side of when the rebuild's token spend actually posts (UTC
metric aggregation vs. the PT-anchored reset run), hence the 1-day lookback below.

Consulted by `lambdas/operational/remediation_dispatcher_lambda.py` (the urgent-
alarm fast path): a token-platform alarm breach that lands inside this window is
treated as an expected, already-understood condition and is NOT escalated into an
automated `repository_dispatch` triage run — it is logged and marked suppressed
instead, i.e. it ends up in the digest, not paging the operator.

NOTE (deploy scope, #1961): this module governs the automated-triage escalation
path only. The raw CloudWatch alarm's SNS action (`ai-tokens-platform-daily-total`
routed straight to the `life-platform-alerts` urgent topic, which also carries a
directly-wired human EmailSubscription — see `cdk/stacks/operational_stack.py`) is
unchanged by this file: that's a static CDK resource, evaluated at synth/deploy
time, and making IT window-aware would need a periodic gauge metric + composite
alarm (a bigger change than this story's effort-S badge covers) plus an actual
`cdk deploy`. Until that follow-up ships, the raw urgent-topic email still fires
on a genesis-week breach even when this module correctly identifies it as
expected — this file only prevents the wasted automated remediation-agent run
that used to follow it.

STAMPED BLOCK — regenerated by `deploy/restart_pipeline.py`'s
`stamp_token_alarm_window()` on every reset. Don't hand-edit the tuple; adjust
WINDOW_DAYS_BEFORE / WINDOW_DAYS_AFTER below if the window's SHAPE needs to
change (that part is not auto-derived).
"""

from datetime import date, timedelta

# How many days before / after the stamped genesis the rebuild spike is expected
# to land. BEFORE covers the UTC/PT calendar-day slop observed in cycle 11 (spike
# posted the day before the stamped genesis); AFTER covers the typical full-cycle
# rebuild's completion window (character sheet, compute, coach dossiers, chronicle
# backfill — cycle 11's example cleared within days, not weeks).
WINDOW_DAYS_BEFORE = 1
WINDOW_DAYS_AFTER = 7

# [start, end) ISO dates, inclusive start / exclusive end.
# Stamped for genesis 2026-08-10 by restart_pipeline.py.
TOKEN_ALARM_GENESIS_WINDOW = ("2026-08-09", "2026-08-17")


def is_within_token_alarm_window(check_date: date | None = None) -> bool:
    """True if `check_date` (default: today) falls within the stamped genesis
    rebuild window `[start, end)`. Never raises: a malformed stamp is treated as
    "not in window" (the safer default — an alarm still pages rather than being
    silently swallowed by a corrupt window)."""
    d = check_date or date.today()
    try:
        start = date.fromisoformat(TOKEN_ALARM_GENESIS_WINDOW[0])
        end = date.fromisoformat(TOKEN_ALARM_GENESIS_WINDOW[1])
    except (ValueError, IndexError, TypeError):
        return False
    return start <= d < end


def window_for_genesis(genesis_iso: str) -> tuple[str, str]:
    """Compute the `[start, end)` window a given genesis date should stamp.
    Pure function — used by both `restart_pipeline.py` (to write the stamp) and
    tests (to assert the stamped value matches what today's genesis implies)."""
    g = date.fromisoformat(genesis_iso)
    start = g - timedelta(days=WINDOW_DAYS_BEFORE)
    end = g + timedelta(days=WINDOW_DAYS_AFTER)
    return start.isoformat(), end.isoformat()
