"""movement_catalog.py — the rules over `config/movement_catalog.json` entries (#4108).

`config/movement_catalog.json` grew from 26 hand-curated movements to every exercise the owner
has ever logged in Hevy (built by `deploy/build_movement_catalog.py`). This module owns the two
questions every consumer asks of one entry, so the file carries data and the rules live once:

GENERATOR ELIGIBILITY — `generator_eligible(entry, skill_ceiling)` (owner ruling C on #4108,
2026-09-23: every catalogued exercise may be programmed; there is NO frequency gate — a
movement's `sessions` / `last_done` are recorded, never used to exclude it):

  * the skill ceiling applies to every entry (`skill_tier <= skill_ceiling`; the anchor
    patterns' exemption from the ceiling is #4080's, applied where anchors resolve, in
    `program_structure._resolve_movement`, not here), AND
  * a REVIEWED entry is eligible as written, OR
  * an unreviewed entry is eligible when it has a prescribable shape — a `default_rep_range`.
    The muscle selector builds rep-range sets; a plank, a treadmill or an id whose Hevy
    metadata is gone has no rep range to prescribe, so it is catalogued but never picked.
    That is a SHAPE rule, not a frequency one: the builder gives every rep-based Hevy type a
    range by tier.

An entry with no `reviewed` key is treated as reviewed: that is every catalog written before
#4108 and every hand-written test fixture, all curated by construction.

ANCHOR FAMILY — `anchor_family(entry)`: which v0.3 anchor pattern (`program_structure.ANCHORS`:
squat, hinge, bench, row, overhead_press, vertical_pull) the entry is a LOADED variant of, or
None. It reuses the program's own classifier (`program_structure.classify_movement`, the same
one adherence reads) and adds the two conditions a title substring cannot carry:

  * the entry's `primary_muscle` is one of the anchor's own `primary_muscles` ("Upright Row" is a
    shoulders movement that happens to contain "row"), and
  * it is loaded — Hevy type `weight_reps` (a squat jump is not a squat anchor); the vertical
    pull accepts every rep-based type (a pull-up — `reps_only` on Hevy — IS the pattern). An entry with no Hevy
    type (the hand-curated ones) counts as loaded unless its primary muscle is cardio.

The builder writes the result as each entry's `anchor_family` for readability, and
`tests/test_movement_catalog_4108.py` holds every stored value equal to this function.

THE THREE PROVENANCES:

  * `hand_curated` — the original 26 (and anything a human writes by hand). `reviewed: true`.
  * `hevy_history` — generated by the builder from the logged history. `reviewed: false` until a
    human reviews it (set `reviewed: true`; the builder then preserves the entry verbatim).
  * `coach_added` — an exercise the owner has NOT necessarily trained, added deliberately
    (owner ruling on #4108: the catalog may carry never-done exercises). To add one, write a
    minimal entry under a new key in `config/movement_catalog.json`:

        "landmine_press": {"title": "Landmine Press", "hevy_template_id_hint": "<Hevy id>",
                           "provenance": "coach_added"}

    and run `python3 deploy/build_movement_catalog.py --write`. The builder keeps every field
    written, fills each ABSENT field from Hevy's template metadata exactly as it enriches a
    history entry (muscles, skill tier, type, equipment, rep range) when the hint — or, with no
    hint, the exact title — maps to a Hevy template, records `sessions` / `last_done` (0 /
    null until it is done) and defaults `reviewed` to false. It is eligible under the same rule
    as every other entry. An entry that maps to no Hevy template stays as written: give it
    `primary_muscle`, `skill_tier` and a `default_rep_range` by hand, or it is catalogued only.
"""

from __future__ import annotations

from typing import Any

PROVENANCE_CURATED = "hand_curated"
PROVENANCE_HISTORY = "hevy_history"
PROVENANCE_COACH = "coach_added"
PROVENANCES = frozenset({PROVENANCE_CURATED, PROVENANCE_HISTORY, PROVENANCE_COACH})

#: Hevy exercise types that are counted in reps (the muscle selector's set shape). Hevy's GET
#: side names the bodyweight types `bodyweight_weighted` / `bodyweight_assisted` (measured on
#: the live template list 2026-09-23); the create side names them `bodyweight_reps` /
#: `bodyweight_assisted_reps` (mcp/tools_hevy_routine._HEVY_EXERCISE_TYPES). Both spellings are
#: listed so a coach_added entry written with either is read the same.
REP_BASED_TYPES = frozenset(
    {"weight_reps", "reps_only", "bodyweight_weighted", "bodyweight_assisted", "bodyweight_reps", "bodyweight_assisted_reps"}
)

#: Hevy types that load an anchor pattern (see ANCHOR FAMILY above), per family; the default
#: applies to every family not listed. A pull-up is `reps_only` on Hevy's GET side.
ANCHOR_LOADED_TYPES: dict[str, frozenset[str]] = {
    "_default": frozenset({"weight_reps"}),
    "vertical_pull": REP_BASED_TYPES,
}


def is_reviewed(entry: dict[str, Any]) -> bool:
    return bool(entry.get("reviewed", True))


def generator_eligible(entry: dict[str, Any], skill_ceiling: int) -> bool:
    """True when the generator may auto-program this catalog entry at `skill_ceiling`."""
    try:
        tier = int(entry.get("skill_tier", 99))
    except (TypeError, ValueError):
        return False
    if tier > int(skill_ceiling):
        return False
    if is_reviewed(entry):
        return True
    rr = entry.get("default_rep_range")
    return isinstance(rr, dict) and "start" in rr and "end" in rr


def anchor_family(entry: dict[str, Any]) -> str | None:
    """The v0.3 anchor pattern this entry is a loaded variant of, or None."""
    from training.program_structure import ANCHORS, classify_movement

    cls = classify_movement(str(entry.get("title") or ""))
    if not cls.startswith("anchor:"):
        return None
    family = cls.split(":", 1)[1]
    anchor = ANCHORS.get(family) or {}
    if entry.get("primary_muscle") not in (anchor.get("primary_muscles") or []):
        return None
    hevy_type = entry.get("hevy_type")
    if hevy_type is None:
        return family if entry.get("primary_muscle") != "cardio" else None
    loaded = ANCHOR_LOADED_TYPES.get(family, ANCHOR_LOADED_TYPES["_default"])
    return family if hevy_type in loaded else None
