#!/usr/bin/env python3
"""Derive the starter template's cost note from the published stack manifest (#2541).

The template in `oss/starter-slice/` is meant to be copied out of this repo and
handed to a stranger. It therefore cannot read `site/data/stack.json` at runtime --
so the figures are BAKED, and this script is the only thing allowed to bake them.

One source of truth: every dollar in the template comes from
`site/data/stack.json`'s `cost_of_ownership` block, which is itself generated by
`scripts/v4_build_stack_manifest.py`. Nothing is retyped. Two artifacts are
written from it:

  oss/starter-slice/cost_note.json   the machine copy the template's own `cost`
                                     command reads
  oss/starter-slice/README.md        the human copy, between the GENERATED markers

`tests/test_starter_slice.py` re-runs this in memory and fails if either artifact
has drifted, so a manifest change cannot silently leave a stale number in a
template we are about to publish.

Deliberately NOT copied: the manifest's `updated` stamp. Baking a timestamp would
red the drift gate on every unrelated manifest regeneration -- the gate exists to
catch changed MONEY, not a changed date.

Usage:
    python3 scripts/build_starter_slice_cost.py            # write
    python3 scripts/build_starter_slice_cost.py --check    # verify, exit 1 on drift
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "site", "data", "stack.json")
SLICE_DIR = os.path.join(ROOT, "oss", "starter-slice")
NOTE_PATH = os.path.join(SLICE_DIR, "cost_note.json")
README_PATH = os.path.join(SLICE_DIR, "README.md")

BEGIN = "<!-- BEGIN GENERATED: cost (scripts/build_starter_slice_cost.py) -->"
END = "<!-- END GENERATED: cost -->"

MANIFEST_URL = "https://averagejoematt.com/data/stack.json"

# The slice's OWN cost. Not a number, on purpose, and not a second opinion about
# the platform's: nothing here measures what a fourteen-row-a-day pipeline costs in
# someone else's account, so the honest answer is the billed SET plus the ceiling
# it cannot exceed. Same posture the manifest itself takes for devices and hours
# (ADR-104/105): a null with a basis, never a plausible-looking guess.
THIS_SLICE = {
    "monthly_usd": None,
    "basis": (
        "Not asserted. This template has never been billed in a third party's account, and the answer depends on "
        "region, request volume and how long you leave it running -- any figure printed here would be a guess "
        "wearing a decimal point. What IS knowable is the billed set below: storage measured in kilobytes and "
        "roughly thirty on-demand writes a day, with no compute, no schedule and no AI inference. Read your own "
        "AWS bill after a week; that is the only number that will be true for you."
    ),
    "confidence": "no figure asserted",
    "billed_services": ["S3 (PutObject + a few KB stored)", "DynamoDB on-demand (a handful of writes and one query per run)"],
    "free_of_charge": ["Open-Meteo (no key, no account, no bill)", "the local backend (--local touches no AWS service at all)"],
}


def _platform_block(manifest: dict) -> dict:
    aws = manifest["cost_of_ownership"]["aws"]
    composition = aws["composition"]
    return {
        "monthly_usd_typical": aws["monthly_usd_typical"],
        "ceiling_usd": aws["ceiling_usd"],
        "surge_ceiling_usd": aws["surge_ceiling_usd"],
        "non_ai_floor_monthly_usd": composition["non_ai_floor_monthly_usd"],
        "ai_variable_monthly_usd": composition["ai_variable_monthly_usd"],
        "actuals": [{"label": a["label"], "usd": a["usd"]} for a in aws["actuals"]],
        "composition_basis": composition["basis"],
        "actuals_basis": aws["actuals_basis"],
        "ceiling_basis": aws["ceiling_basis"],
        "scope_note": aws["scope_note"],
    }


def build_note(manifest: dict) -> dict:
    return {
        "_generated_by": ("scripts/build_starter_slice_cost.py -- derived from the platform stack manifest. Never hand-edit; regenerate."),
        "_honesty_contract": manifest["cost_of_ownership"]["_honesty_contract"],
        "derived_from": MANIFEST_URL,
        "this_slice": THIS_SLICE,
        "platform": _platform_block(manifest),
    }


def _usd_range(pair) -> str:
    return f"${pair[0]:g}-${pair[1]:g}"


def build_readme_block(note: dict) -> str:
    platform, slice_ = note["platform"], note["this_slice"]
    actuals = ", ".join(f"{a['label']} ${a['usd']:.2f}" for a in platform["actuals"])
    return "\n".join(
        [
            BEGIN,
            "",
            "**What this slice costs you.** " + slice_["basis"],
            "",
            "| billed by this template | free |",
            "| --- | --- |",
            "| " + "<br>".join(slice_["billed_services"]) + " | " + "<br>".join(slice_["free_of_charge"]) + " |",
            "",
            "**What the full platform costs**, for scale — these figures are read from its published manifest,",
            f"[`cost_of_ownership`]({MANIFEST_URL}), not restated here:",
            "",
            "| | |",
            "| --- | --- |",
            f"| typical run-rate | {platform['monthly_usd_typical']} / month |",
            f"| self-imposed ceiling | ${platform['ceiling_usd']:g} / month (floats to ${platform['surge_ceiling_usd']:g} under reader-traffic surge) |",
            f"| non-AI floor | {_usd_range(platform['non_ai_floor_monthly_usd'])} / month |",
            f"| AI, variable | {_usd_range(platform['ai_variable_monthly_usd'])} / month |",
            f"| billed actuals | {actuals} |",
            "",
            f"_{platform['scope_note']}_",
            "",
            f"_{note['_honesty_contract']}_",
            "",
            END,
        ]
    )


def apply_to_readme(readme_text: str, block: str) -> str:
    if BEGIN not in readme_text or END not in readme_text:
        raise SystemExit(f"README is missing the generated-cost markers ({BEGIN} / {END})")
    head = readme_text.split(BEGIN)[0]
    tail = readme_text.split(END)[1]
    return head + block + tail


def render(manifest_path: str = MANIFEST) -> tuple[dict, str]:
    """Return (cost_note, readme_text) as they SHOULD be on disk."""
    with open(manifest_path, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)
    note = build_note(manifest)
    with open(README_PATH, "r", encoding="utf-8") as fh:
        readme = fh.read()
    return note, apply_to_readme(readme, build_readme_block(note))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify the artifacts match the manifest; exit 1 on drift")
    args = ap.parse_args()

    note, readme = render()
    note_text = json.dumps(note, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        drifted = []
        if not os.path.exists(NOTE_PATH) or open(NOTE_PATH, encoding="utf-8").read() != note_text:
            drifted.append(NOTE_PATH)
        if open(README_PATH, encoding="utf-8").read() != readme:
            drifted.append(README_PATH)
        if drifted:
            print("DRIFT — regenerate with `python3 scripts/build_starter_slice_cost.py`:", file=sys.stderr)
            for path in drifted:
                print(f"  {os.path.relpath(path, ROOT)}", file=sys.stderr)
            return 1
        print("starter-slice cost note is in sync with the stack manifest")
        return 0

    with open(NOTE_PATH, "w", encoding="utf-8") as fh:
        fh.write(note_text)
    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write(readme)
    print(f"wrote {os.path.relpath(NOTE_PATH, ROOT)} and the cost block in {os.path.relpath(README_PATH, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
