#!/usr/bin/env python3
"""Build the AJM brand assets — themed mark SVGs + the favicon/app-icon rasters.

Source of truth is three hand-authored masters in ``site/assets/marks/``:

    mark-a.svg    the single-"A" dial — pure vector, no text, no font dependency
    mark-ajm.svg  the AJM monogram dial, ``currentColor`` ink + ``class="ember"``
    lockup.svg    monogram + "averagejoematt" wordmark, same colour convention

Which master is used where is a size decision, not a taste one. Below ~32px the
three letters of "AJM" collapse into texture, so the favicon and the 20px header
mark both use ``mark-a``; the app icons, avatars and lockup are large enough to
carry the full monogram. This is the design doc's own rule for the favicon,
applied consistently to every small-size surface.

Everything else under ``site/assets/marks/`` and every icon raster is GENERATED
from those three. Do not hand-edit a generated file — re-run this script.

Two things this script exists to do that a hand export cannot:

1. **Outline the text.** The masters set "AJM" / "averagejoematt" as live
   ``<text font-family="'IBM Plex Mono'">``. An SVG consumed as ``<img src>``, as
   a favicon, or by a social crawler resolves no webfont, so those letters would
   fall back to the platform's default monospace — wrong letterforms, wrong
   metrics, overflowing the dial. Every generated file has its text converted to
   ``<path>`` outlines against the site's own self-hosted IBM Plex Mono Medium,
   so it renders identically with no font loaded at all.

2. **Retint per theme.** ``currentColor`` does not resolve inside a CSS
   ``background-image``, which is how the header mark is consumed, so each theme
   gets its ink and ember baked to literals from ``site/assets/css/tokens.css``.

Usage::

    python3 scripts/build_brand_assets.py            # write the assets
    python3 scripts/build_brand_assets.py --check    # verify nothing drifted

Rasterisation goes through Playwright (already a dev dependency for the visual-QA
harness) rather than adding a native-dep SVG rasteriser for six PNGs.
"""

from __future__ import annotations

import argparse
import base64
import re
import shutil
import sys
import tempfile
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
MARKS = ROOT / "site" / "assets" / "marks"
ICONS = ROOT / "site" / "assets" / "icons"
SITE = ROOT / "site"

# IBM Plex Mono *Medium* — the masters set font-weight:500, so the Medium face is
# the correct one, not Regular. Self-hosted already; see site/assets/css/fonts.css.
FONT = ROOT / "site" / "assets" / "fonts" / "v4" / "-F6qfjptAgt5VM-kVkqdyU8n3twJwlBFgsAXHNk.woff2"

# Literals lifted from site/assets/css/tokens.css. The marks were drawn on this
# palette, so these are exact matches, not approximations:
#   dark  --ink #ECE3D2  --ember #DD7A37  --page #0E0C08
#   light --ink #221E17  --ember #A34E13  --page #F4EFE4
THEMES = {
    "dark": {"ink": "#ECE3D2", "ember": "#DD7A37", "ground": "#0E0C08"},
    "light": {"ink": "#221E17", "ember": "#A34E13", "ground": "#F4EFE4"},
}

GENERATED_BANNER = "<!-- GENERATED by scripts/build_brand_assets.py — do not edit; edit the master and re-run. -->"


# ── text → outlines ─────────────────────────────────────────────────────────

_TEXT_RE = re.compile(
    r"<text\s+([^>]*?)>([^<]*)</text>",
    re.S,
)


def _attrs(blob: str) -> dict[str, str]:
    return {m.group(1): m.group(2) for m in re.finditer(r'([a-z-]+)="([^"]*)"', blob)}


def outline_text(svg: str, font: TTFont) -> str:
    """Replace every <text> element with an equivalent <path> of outlines.

    Reproduces the CSS text-layout model the masters were eyeballed against:
    advance width is the sum of glyph advances plus ``letter-spacing`` applied
    after *every* character including the last, and ``text-anchor="middle"``
    centres on that full advance. Matching this is what makes the outlined
    result land pixel-identical to the browser's own rendering of the master.
    """
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]

    def replace(m: re.Match[str]) -> str:
        a = _attrs(m.group(1))
        text = m.group(2)
        size = float(a["font-size"])
        spacing = float(a.get("letter-spacing", 0))
        scale = size / upm
        anchor_x = float(a["x"])
        baseline = float(a["y"])
        fill = a.get("fill", "currentColor")

        names = []
        for ch in text:
            if ord(ch) not in cmap:
                raise SystemExit(f"glyph missing from {FONT.name}: {ch!r} — the font subset cannot set {text!r}")
            names.append(cmap[ord(ch)])

        advance = sum(hmtx[n][0] * scale + spacing for n in names)
        if a.get("text-anchor") == "middle":
            pen_x = anchor_x - advance / 2
        elif a.get("text-anchor") == "end":
            pen_x = anchor_x - advance
        else:
            pen_x = anchor_x

        commands: list[str] = []
        for name in names:
            svg_pen = SVGPathPen(glyphs, ntos=lambda v: f"{round(v, 2):g}")
            # y flips: font space is y-up, SVG user space is y-down.
            glyphs[name].draw(TransformPen(svg_pen, (scale, 0, 0, -scale, pen_x, baseline)))
            commands.append(svg_pen.getCommands())
            pen_x += hmtx[name][0] * scale + spacing

        d = "".join(c for c in commands if c)
        return f'<path d="{d}" fill="{fill}"/>'

    return _TEXT_RE.sub(replace, svg)


# ── retint ──────────────────────────────────────────────────────────────────


def retint(svg: str, theme: str, ground: str | None = None) -> str:
    """Bake ``currentColor`` to theme literals; ember-classed elements get ember.

    Line-wise because the masters are authored one element per line, which keeps
    this a legible substitution rather than an XML round-trip that would reflow
    the whole file and make every future diff unreadable.
    """
    t = THEMES[theme]
    out = []
    for line in svg.splitlines():
        colour = t["ember"] if 'class="ember"' in line else t["ink"]
        out.append(line.replace("currentColor", colour))
    svg = "\n".join(out)

    if ground:
        # Full-bleed ground rect immediately after the opening <svg …> tag.
        vb = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
        w, h = vb.group(1), vb.group(2)
        svg = re.sub(r"(<svg[^>]*>)", rf'\1\n  <rect width="{w}" height="{h}" fill="{ground}"/>', svg, count=1)
    return svg


def banner(svg: str) -> str:
    """Stamp the do-not-edit notice above the root element."""
    return svg.replace("<svg", f"{GENERATED_BANNER}\n<svg", 1)


def maskable(svg: str) -> str:
    """Scale the artwork into the inner 80% Android adaptive-icon safe zone.

    Without this the square gets letterboxed inside the mask on install; the
    manifest currently ships no maskable icon at all.
    """
    body = re.sub(r"<svg[^>]*>\n?", "", svg, count=1).rsplit("</svg>", 1)[0]
    ground = re.search(r'(<rect width="100" height="100" fill="[^"]+"/>)', body)
    keep = ground.group(1) if ground else ""
    art = body.replace(keep, "") if keep else body
    head = re.match(r"<svg[^>]*>", svg).group(0)
    return f'{head}\n  {keep}\n  <g transform="translate(10,10) scale(0.8)">{art}</g>\n</svg>\n'


# ── rasterise ───────────────────────────────────────────────────────────────


def rasterise(svg_path: Path, out: Path, size: int) -> None:
    from playwright.sync_api import sync_playwright

    data = base64.b64encode(svg_path.read_bytes()).decode()
    html = "<html><body style='margin:0'>" f"<img src='data:image/svg+xml;base64,{data}' width='{size}' height='{size}'>" "</body></html>"
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": size, "height": size}, device_scale_factor=1)
        page.set_content(html)
        page.wait_for_timeout(120)
        # Always screenshot to .png — Playwright dispatches the encoder off the
        # file extension and rejects .ico. favicon.ico has always been a PNG here
        # (every modern browser accepts one), so the rename is the whole story.
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            shot = Path(tmp.name)
        page.screenshot(path=str(shot), omit_background=False)
        browser.close()
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(shot, out)
    shot.unlink()


# ── build ───────────────────────────────────────────────────────────────────


def build(dest_marks: Path, dest_icons: Path, dest_site: Path) -> None:
    font = TTFont(FONT)
    dest_marks.mkdir(parents=True, exist_ok=True)
    dest_icons.mkdir(parents=True, exist_ok=True)

    mark_a = (MARKS / "mark-a.svg").read_text()  # no text — nothing to outline
    mark = outline_text((MARKS / "mark-ajm.svg").read_text(), font)
    lockup = outline_text((MARKS / "lockup.svg").read_text(), font)

    generated: dict[str, str] = {}
    for theme, t in THEMES.items():
        # Avatar / profile art — opaque ground, for anywhere that composites onto
        # an unknown background (app icons, social avatars).
        generated[f"mark-ajm-{theme}.svg"] = retint(mark, theme, ground=t["ground"])
        generated[f"lockup-{theme}.svg"] = retint(lockup, theme, ground=t["ground"])
        # Header art — transparent, sits on the page's own paper. Deliberately the
        # single-"A", NOT the AJM monogram: at the 20px the header uses, "AJM"
        # collapses into texture, while the "A" stays legible. Same size logic the
        # design doc applies to the favicon — and it means the tab icon and the
        # header mark are now literally the same mark.
        generated[f"mark-header-{theme}.svg"] = retint(mark_a, theme)
        generated[f"favicon-{theme}.svg"] = retint(mark_a, theme, ground=t["ground"])

    generated["mark-maskable-dark.svg"] = maskable(generated["mark-ajm-dark.svg"])

    for name, svg in generated.items():
        (dest_marks / name).write_text(banner(svg))

    rasters = [
        (dest_marks / "favicon-dark.svg", dest_site / "favicon.ico", 32),
        (dest_marks / "mark-ajm-dark.svg", dest_site / "apple-touch-icon.png", 180),
        (dest_marks / "mark-ajm-dark.svg", dest_icons / "icon-192.png", 192),
        (dest_marks / "mark-ajm-dark.svg", dest_icons / "icon-512.png", 512),
        (dest_marks / "mark-maskable-dark.svg", dest_icons / "icon-maskable-512.png", 512),
    ]
    for src, out, size in rasters:
        rasterise(src, out, size)
        print(f"  raster {out.relative_to(ROOT if ROOT in out.parents else out.parent.parent)} @{size}")

    # iOS reads the -precomposed variant first on older devices; it has always
    # been byte-identical to the plain one here, so keep that.
    shutil.copyfile(dest_site / "apple-touch-icon.png", dest_site / "apple-touch-icon-precomposed.png")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="rebuild into a temp tree and fail if anything differs")
    args = ap.parse_args()

    if not FONT.exists():
        raise SystemExit(f"font not found: {FONT}")

    if not args.check:
        build(MARKS, ICONS, SITE)
        print("brand assets rebuilt")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        t = Path(tmp)
        build(t / "marks", t / "icons", t / "site")
        drift = []
        pairs = [(t / "marks", MARKS), (t / "icons", ICONS), (t / "site", SITE)]
        for fresh_dir, live_dir in pairs:
            for fresh in sorted(fresh_dir.iterdir()):
                live = live_dir / fresh.name
                if not live.exists() or live.read_bytes() != fresh.read_bytes():
                    drift.append(str(live.relative_to(ROOT)))
        if drift:
            print("DRIFT — these are stale, re-run scripts/build_brand_assets.py:", file=sys.stderr)
            for d in drift:
                print(f"  {d}", file=sys.stderr)
            return 1
    print("brand assets up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
