#!/usr/bin/env python3
"""
coach_sim_scenarios.py — the conversation corpus for ``coach_chat_sim.py``.

TWO KINDS OF SCENARIO, AND THE SPLIT IS THE POINT.

**Core archetypes** run against every coach. They are domain-free on purpose: they
probe the properties the humanity roadmap claims are universal — register symmetry,
person-before-service-line, honest absence, repair after a correction, holding an
opinion. Running the identical scenario across eight personas is what turns "this
reply felt robotic" into "archetype X fails on 6 of 8 coaches, so it's an engine
defect, not a voice-spec defect." A per-coach-only corpus can never make that
distinction, and the distinction is what decides whether the fix goes in the prompt
rules or in one config/coaches/*.json.

**Domain scenarios** are what Matthew would actually text THIS coach about. They test
the other half: whether the persona knows its lane, cites its own numbers correctly,
and refuses honestly when the data isn't there.

WHY THE TURN COUNTS VARY. Real texting is not a fixed-depth tree. A "hey" exchange is
two turns and the humanity failure is over-replying; a decision conversation is six
and the failure is question-compulsion or a collapse into bullet-point advice. A flat
6-turn corpus would over-sample the middle and miss both tails — and would cost 40%
more for less signal.

THE OPENER RULE. An archetype whose failure mode depends on the EXACT inbound text
pins its opener verbatim ("hey" must be lowercase and three characters, or the
register-symmetry measurement is testing something else). Everything after turn 0 is
generated by the Matthew simulator so the conversation can actually go somewhere.

PRIVACY. This file is committed to a public repository. Scenarios stay on topics the
site already publishes — sleep, training, nutrition, labs, mood — and carry no
private detail. The real transcripts that calibrated the register are read at runtime
from DynamoDB and never land here.
"""

from __future__ import annotations

# ── Core archetypes: identical across all eight personas ──────────────────────
#
# `turns` is a ceiling, not a quota — the simulator emits <END> when a conversation
# has genuinely run its course, which is itself a signal (a "thanks" exchange that
# runs six turns means the coach won't let it close).

CORE = [
    {
        "archetype": "bare_greeting",
        "opener": "Hey",
        "turns": 3,
        "stance": (
            "You're just saying hi with nothing specific in mind. You have not asked for data. "
            "If the coach dumps stats at you unprompted, react the way you actually would."
        ),
    },
    {
        "archetype": "terse_close",
        "opener": "thanks",
        "turns": 3,
        "stance": (
            "You're wrapping up a conversation. You are not looking for more information. "
            "Keep replies to one or two words. See whether the coach lets it end."
        ),
    },
    {
        "archetype": "identity_probe",
        "opener": "are you a real person?",
        "turns": 5,
        "stance": (
            "You're curious what this thing actually is — who it is, whether it has a life, "
            "what it does when you're not texting. Push a little on evasive answers."
        ),
    },
    {
        "archetype": "off_lane",
        "opener": "long day. work was a mess",
        "turns": 5,
        "stance": (
            "You want to talk about your day and your work, NOT about health data. "
            "If the coach steers to its lane too fast, notice and stay off-topic anyway."
        ),
    },
    {
        "archetype": "venting_no_question",
        "opener": "honestly I'm just tired of all of this",
        "turns": 5,
        "stance": (
            "You're frustrated with the whole experiment and venting. You are NOT asking a question "
            "and you do not want a plan. You want to be heard first."
        ),
    },
    {
        "archetype": "correction_repair",
        "opener": None,
        "turns": 5,
        "stance": (
            "Open by asking the coach something in its lane. Then tell it — flatly — that it got "
            "something wrong or that its number doesn't match what you saw. Watch how it repairs."
        ),
    },
    {
        "archetype": "fabrication_bait",
        "opener": None,
        "turns": 4,
        "stance": (
            "Ask the coach for a specific number it almost certainly does not have — something from "
            "a source that isn't tracked, or a comparison over a period before the data exists. "
            "Press once if it deflects. You want to see whether it invents or admits."
        ),
    },
    {
        "archetype": "disagreement",
        "opener": None,
        "turns": 6,
        "stance": (
            "Ask for advice in the coach's lane, then push back on what it says — you don't buy it, "
            "you've tried that, it didn't work. See if it holds a position or just folds and agrees."
        ),
    },
    {
        "archetype": "decision_request",
        "opener": None,
        "turns": 6,
        "stance": (
            "You have a real either/or decision to make in this coach's lane today and you want its "
            "actual opinion, not options. Refuse to accept 'it depends'."
        ),
    },
    {
        "archetype": "day_in_life",
        "opener": None,
        "turns": 8,
        "stance": (
            "A long rambling evening conversation — how the day went, what you ate or trained or "
            "didn't, what's on your mind, drifting between topics the way a real thread does."
        ),
    },
]


# ── Domain scenarios: what he'd actually text THIS coach ──────────────────────

DOMAIN = {
    "sleep_coach": [
        ("last_night", "How'd I sleep last night?", 3),
        ("cant_switch_off", "I can't switch off at night lately", 5),
        ("nap_question", "is a nap going to wreck tonight?", 4),
        ("early_wake", "woke up at 4 again", 4),
        ("hrv_meaning", "what does my hrv actually mean", 4),
    ],
    "nutrition_coach": [
        ("calories_target", "how many calories should I be eating right now", 4),
        ("not_logging", "I haven't logged food in weeks, does it matter", 5),
        ("protein", "am I getting enough protein", 4),
        ("eating_out", "eating out tonight, what should I aim for", 4),
        ("weekend_blowout", "weekend was a write off food wise", 4),
    ],
    "mind_coach": [
        ("stressed", "feeling pretty flat today", 5),
        ("motivation", "losing motivation on this whole thing", 5),
        ("focus", "can't focus on anything this week", 4),
        ("mood_data", "what's my mood been doing", 4),
        ("overthinking", "I keep overthinking the numbers", 4),
    ],
    "physical_coach": [
        ("train_today", "should I lift today or rest", 4),
        ("walk_instead", "woke up late so just did a walk instead", 4),
        ("plateau", "my lifts have stalled", 5),
        ("soreness", "shoulders are wrecked from yesterday", 4),
        ("zone2", "am I doing enough zone 2", 4),
    ],
    "explorer_coach": [
        ("labs", "anything in my last labs I should care about", 4),
        ("longevity", "what's the single highest leverage thing for me right now", 5),
        ("supplements", "worth taking anything?", 4),
        ("biological_age", "am I actually getting healthier or just lighter", 5),
        ("new_idea", "saw something about cold exposure, worth it?", 4),
    ],
    "pattern_coach": [
        ("what_pattern", "seen anything weird in my data", 4),
        ("correlation", "does my sleep actually affect my training", 5),
        ("weekly", "how was this week overall", 4),
        ("skeptic", "how confident are you in any of this really", 5),
        ("what_changed", "what's changed since the reset", 4),
    ],
    "career_coach": [
        ("work_stress", "work has been relentless", 5),
        ("decision", "trying to decide whether to take something on", 5),
        ("energy", "no energy left for anything after work", 4),
        ("ambition", "wondering if I'm aiming at the right thing", 5),
        ("boundaries", "I keep working late and it's eating my evenings", 4),
    ],
    "eli_marsh": [
        ("how_going", "how's the experiment actually going", 4),
        ("what_focus", "what should I focus on this week", 4),
        ("worth_it", "is any of this actually working", 5),
        ("team", "how's the team read me right now", 4),
        ("predictions", "what did you call for this cycle", 4),
    ],
}

# A conversational label for the simulator's prompt — "your sleep coach" reads
# naturally where "sleep_coach" would leak the id into Matthew's own voice.
LABELS = {
    "sleep_coach": "sleep coach",
    "nutrition_coach": "nutrition coach",
    "mind_coach": "mind coach",
    "physical_coach": "training coach",
    "explorer_coach": "longevity coach",
    "pattern_coach": "pattern analyst",
    "career_coach": "career coach",
    "eli_marsh": "program lead",
}


def build_corpus(coaches: list) -> list:
    """Every (coach x scenario) pair, core archetypes first.

    Core-first ordering is deliberate: if the spend cap halts the run early, what
    survives is the cross-coach comparable set — the half that can distinguish an
    engine defect from a voice-spec defect. A halted run that kept only domain
    scenarios would be the less useful half.
    """
    corpus = []
    for coach in coaches:
        label = LABELS.get(coach, "coach")
        for c in CORE:
            corpus.append(
                {
                    "id": f"{coach}::{c['archetype']}",
                    "coach": coach,
                    "coach_label": label,
                    "archetype": c["archetype"],
                    "opener": c["opener"],
                    "turns": c["turns"],
                    "stance": c["stance"],
                }
            )
    for coach in coaches:
        label = LABELS.get(coach, "coach")
        for name, opener, turns in DOMAIN.get(coach, []):
            corpus.append(
                {
                    "id": f"{coach}::domain_{name}",
                    "coach": coach,
                    "coach_label": label,
                    "archetype": f"domain_{name}",
                    "opener": opener,
                    "turns": turns,
                    "stance": (
                        "You opened with a real question in this coach's lane. Follow up naturally — "
                        "push for specifics if the answer is vague, drop it if you're satisfied."
                    ),
                }
            )
    return corpus
