#!/usr/bin/env python3
"""
export_platform_memory.py — dump the DynamoDB platform-memory partition to markdown.

Continuity tooling (docs/CONTINUITY.md): the platform's compounding memory substrate
lives in ONE DynamoDB partition, written by the MCP memory tools and several compute
lambdas. If the AI tooling is gone, this script exports the whole partition to
human-readable markdown, one file per category.

Key schema (from mcp/tools_memory.py — the canonical writer/reader interface):
    pk = USER#<user>#SOURCE#platform_memory      (default user: matthew)
    sk = MEMORY#<category>#<YYYY-MM-DD>

Known categories are listed in mcp/tools_memory.py::VALID_CATEGORIES and
lambdas/phase_taxonomy.py (MEMORY_DURABLE_CATEGORIES / MEMORY_SCOPED_CATEGORIES),
but this exporter does NOT assume that list — it queries the full partition and
groups by whatever categories actually exist. Items whose sort key does not match
the MEMORY#... pattern land in `_other.md` so nothing is silently dropped.

READ-ONLY: performs only dynamodb:Query against the table. No writes, ever.

Usage:
    # count what's there, write nothing
    python3 scripts/export_platform_memory.py --dry-run

    # export one markdown file per category to ./memory_export/
    python3 scripts/export_platform_memory.py

    # custom target dir / table / user
    python3 scripts/export_platform_memory.py --out /tmp/mem --table life-platform --user matthew
"""

import argparse
import json
import sys
from collections import defaultdict
from decimal import Decimal
from pathlib import Path

import boto3

DEFAULT_TABLE = "life-platform"
DEFAULT_REGION = "us-west-2"
DEFAULT_USER = "matthew"
DEFAULT_OUT = "./memory_export/"
MEMORY_SOURCE = "platform_memory"
SK_PREFIX = "MEMORY#"


def _plain(value):
    """Convert DynamoDB Decimals (and nested containers) to plain JSON-safe types."""
    if isinstance(value, Decimal):
        as_int = int(value)
        return as_int if value == as_int else float(value)
    if isinstance(value, dict):
        return {k: _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(v) for v in value]
    if isinstance(value, set):
        return sorted(_plain(v) for v in value)
    return value


def fetch_partition(table, user_id):
    """Query the full platform-memory partition (paginated). Read-only."""
    pk = f"USER#{user_id}#SOURCE#{MEMORY_SOURCE}"
    items = []
    kwargs = {
        "KeyConditionExpression": "pk = :pk",
        "ExpressionAttributeValues": {":pk": pk},
    }
    while True:
        resp = table.query(**kwargs)
        items.extend(resp.get("Items", []))
        last = resp.get("LastEvaluatedKey")
        if not last:
            return items
        kwargs["ExclusiveStartKey"] = last


def group_by_category(items):
    """Group items by category attribute, falling back to the sk-embedded category."""
    groups = defaultdict(list)
    for item in items:
        sk = str(item.get("sk", ""))
        category = item.get("category")
        if not category and sk.startswith(SK_PREFIX) and sk.count("#") >= 2:
            category = sk.split("#", 2)[1]
        if not category:
            category = "_other"
        groups[str(category)].append(item)
    for records in groups.values():
        records.sort(key=lambda r: str(r.get("sk", "")), reverse=True)
    return dict(sorted(groups.items()))


def render_category_markdown(category, records, table_name, user_id):
    """Render one category's records as a markdown document."""
    lines = [
        f"# Platform memory — {category}",
        "",
        f"Exported from DynamoDB table `{table_name}`, partition "
        f"`USER#{user_id}#SOURCE#{MEMORY_SOURCE}` ({len(records)} records, newest first).",
        "Generated by `scripts/export_platform_memory.py` — see `docs/CONTINUITY.md`.",
        "",
    ]
    for record in records:
        plain = _plain(record)
        sk = plain.pop("sk", "")
        plain.pop("pk", None)
        date = plain.get("date") or (sk.split("#", 2)[2] if sk.startswith(SK_PREFIX) and sk.count("#") >= 2 else sk)
        lines.append(f"## {date}")
        lines.append("")
        lines.append(f"`{sk}`")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(plain, indent=2, sort_keys=True, default=str))
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Export the platform-memory DDB partition to markdown (read-only).")
    parser.add_argument("--table", default=DEFAULT_TABLE, help=f"DynamoDB table name (default: {DEFAULT_TABLE})")
    parser.add_argument("--region", default=DEFAULT_REGION, help=f"AWS region (default: {DEFAULT_REGION})")
    parser.add_argument("--user", default=DEFAULT_USER, help=f"User id in the partition key (default: {DEFAULT_USER})")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"Target directory for markdown files (default: {DEFAULT_OUT})")
    parser.add_argument("--dry-run", action="store_true", help="List per-category record counts only; write nothing")
    args = parser.parse_args(argv)

    table = boto3.resource("dynamodb", region_name=args.region).Table(args.table)
    items = fetch_partition(table, args.user)
    groups = group_by_category(items)

    print(f"Partition USER#{args.user}#SOURCE#{MEMORY_SOURCE} in {args.table} ({args.region}): {len(items)} records")
    for category, records in groups.items():
        dates = [str(r.get("date", "")) for r in records if r.get("date")]
        span = f"  ({min(dates)} .. {max(dates)})" if dates else ""
        print(f"  {category:24s} {len(records):5d}{span}")

    if args.dry_run:
        print("\n--dry-run: nothing written.")
        return 0

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for category, records in groups.items():
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in category) or "_other"
        path = out_dir / f"{safe_name}.md"
        path.write_text(render_category_markdown(category, records, args.table, args.user), encoding="utf-8")
        print(f"  wrote {path}")
    print(f"\nExported {len(items)} records across {len(groups)} categories to {out_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
