#!/usr/bin/env python3
"""gen_mirror_distributions.py — Matthew's published metric distributions for /method/mirror/ (#1392).

The Mirror overlays a reader's Whoop-export numbers on Matthew's OWN distributions
("your HRV sits at his 62nd percentile"). This script builds that artifact:
site/data/mirror_distributions.json — a STATIC, committed, deploy-race-safe snapshot
(the same pattern as /data/calibration_demo.json — no /api endpoint, nothing live).

Per metric it publishes the FULL SORTED SAMPLE (one value per day, rounded), not just
anchor percentiles — so the browser computes an EXACT midrank percentile (ADR-105:
deterministic computation, no interpolation guesswork), plus n and the window. All six
metrics are already public on the site's data pages day by day; this file only
re-shapes what /data/ and /cockpit/ have published all along — it must never grow a
metric that is not already public (no ADR-104 backdoor).

Reads DynamoDB (read-only; Query on the whoop partition) with whatever credentials the
attended session has. Re-run whenever the snapshot ages — the page displays its
`window.end` stamp so staleness is visible, honest, and the reader's to judge.

Run from repo root:  python3 scripts/gen_mirror_distributions.py [--days 365]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date, timedelta
from decimal import Decimal

import boto3
from boto3.dynamodb.conditions import Key

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "lambdas"))

from compute.daily_metrics_compute_lambda import normalize_whoop_sleep  # noqa: E402

OUT_PATH = os.path.join(ROOT, "site", "data", "mirror_distributions.json")
TABLE = "life-platform"
PK = "USER#matthew#SOURCE#whoop"

# metric key → (extractor over the normalized whoop record, decimals to publish at)
METRICS = {
    "recovery_score": (lambda r: r.get("recovery_score"), 0),
    "hrv": (lambda r: r.get("hrv"), 1),
    "resting_heart_rate": (lambda r: r.get("resting_heart_rate"), 0),
    "sleep_duration_hours": (lambda r: r.get("sleep_duration_hours"), 2),
    "sleep_performance": (lambda r: r.get("sleep_score"), 0),
    "strain": (lambda r: r.get("strain"), 1),
}


def _to_float(v):
    if isinstance(v, Decimal):
        return float(v)
    if isinstance(v, (int, float)):
        return float(v)
    return None


def fetch_window(days: int):
    table = boto3.resource("dynamodb", region_name="us-west-2").Table(TABLE)
    end = date.today()
    start = end - timedelta(days=days)
    items = []
    kwargs = {"KeyConditionExpression": Key("pk").eq(PK) & Key("sk").between(f"DATE#{start.isoformat()}", f"DATE#{end.isoformat()}")}
    while True:
        resp = table.query(**kwargs)
        items.extend(resp.get("Items", []))
        lek = resp.get("LastEvaluatedKey")
        if not lek:
            break
        kwargs["ExclusiveStartKey"] = lek
    return start, end, items


def build(days: int) -> dict:
    start, end, items = fetch_window(days)
    samples: dict[str, list[float]] = {k: [] for k in METRICS}
    for item in items:
        # Day-level records only: the partition also holds DATE#<date>#WORKOUT#<id>
        # rows whose per-workout strain would pollute the daily-strain sample.
        if len(str(item.get("sk", "")).split("#")) != 2:
            continue
        rec = normalize_whoop_sleep({k: _to_float(v) for k, v in item.items() if _to_float(v) is not None})
        for metric, (extract, nd) in METRICS.items():
            v = extract(rec)
            if v is None:
                continue
            samples[metric].append(round(v, nd) if nd else round(v))
    out = {
        "_note": (
            "Generated by scripts/gen_mirror_distributions.py from the whoop partition. "
            "Do not hand-edit. One value per day; full sorted samples so the browser "
            "computes exact midrank percentiles. Every metric here is already published "
            "day-by-day on the site's data pages."
        ),
        "window": {"start": start.isoformat(), "end": end.isoformat(), "days": days},
        "metrics": {},
    }
    for metric, vals in samples.items():
        vals.sort()
        out["metrics"][metric] = {"n": len(vals), "sample": vals}
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=365)
    args = ap.parse_args()
    payload = build(args.days)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write("\n")
    ns = {m: d["n"] for m, d in payload["metrics"].items()}
    print(f"wrote {os.path.relpath(OUT_PATH, ROOT)} window={payload['window']['start']}..{payload['window']['end']} n=" + json.dumps(ns))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
