#!/usr/bin/env python3
"""scripts/generate_adr_index.py — regenerate the ADR index table in docs/DECISIONS.md.

THE PROBLEM THIS SOLVES:
  The hand-written index table stalled at ADR-057 while the file grew to 120+ records
  (header claimed "94 ADRs total" while ADR-133 existed). The institutional "why" was
  unnavigable past ADR-057 without grep. Hand-maintained indexes of append-only logs
  always rot; this derives the index from the headings themselves.

WHAT IT DOES:
  Parses every `## ADR-NNN` AND `### ADR-NNN` record heading in docs/DECISIONS.md
  (ADR-046–057 are h3-headed — a `##`-only parse silently dropped 12 real records
  while --check certified the index current, #1321), extracts title + date + status
  from each record body (both body styles supported: the classic
  `**Date:** / **Status:**` block and the newer prose style with the date in the
  heading), and rewrites the table between the ADR-INDEX markers:

      <!-- ADR-INDEX:START (generated by scripts/generate_adr_index.py — do not hand-edit) -->
      ...
      <!-- ADR-INDEX:END -->

  `### ADR-NNN Amendment (...)` headings are NOT records — an amendment folds into
  its parent record's row (its text is part of the parent's body; indexing it
  separately would duplicate the parent's number and inflate the record count).

  The `> N ADRs total (ADR-AAA → ADR-ZZZ)` header line is also derived and rewritten
  — never hand-maintain that count.

  --check additionally asserts the record parse agrees with a permissive any-level
  heading scan (a record headed at a level the parser can't see is a hard error,
  never a silent omission again), and WARNS on unused numbers in the sequence
  (known skipped/merged numbers — see #817).

USAGE:
  python3 scripts/generate_adr_index.py            # dry run (prints what would change)
  python3 scripts/generate_adr_index.py --apply    # rewrite the index in place
  python3 scripts/generate_adr_index.py --check    # CI gate: exit 1 if index is stale

Run after adding an ADR (the wrap skill's doc-impact sweep covers this).
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "DECISIONS.md"

START_MARKER = "<!-- ADR-INDEX:START (generated by scripts/generate_adr_index.py — do not hand-edit) -->"
END_MARKER = "<!-- ADR-INDEX:END -->"

# Record headings are h2 OR h3 (ADR-046–057 are h3, #1321); `### ADR-NNN Amendment (...)`
# headings are sub-records that fold into their parent — the lookahead excludes them.
_HEADING_RE = re.compile(r"^###? ADR-(\d{3})(?!\s*Amendment)\s*[:—–-]?\s*(.*)$", re.MULTILINE)
# Permissive scan: any heading level, amendments included — the consistency oracle for --check.
_ANY_ADR_HEADING_RE = re.compile(r"^#{2,6} ADR-(\d{3})", re.MULTILINE)
# The derived header count line ("> 133 ADRs total (ADR-001 → ADR-135)…" — tail preserved).
_COUNT_LINE_RE = re.compile(r"^> \d+ ADRs total \(ADR-\d{3} → ADR-\d{3}\)", re.MULTILINE)
_DATE_BODY_RE = re.compile(r"\*\*Date:?\*\*:?\s*(\d{4}-\d{2}-\d{2})")
_DATE_ANY_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
_STATUS_BODY_RE = re.compile(r"\*\*Status:?\*\*:?\s*([^\n]+)")


def _records(src: str) -> list[dict]:
    matches = list(_HEADING_RE.finditer(src))
    records = []
    for i, m in enumerate(matches):
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[m.end() : body_end]
        title = m.group(2).strip() or "(untitled)"
        # Date: prefer an explicit **Date:** field, else a date literal in the heading, else the first in the body
        date_m = _DATE_BODY_RE.search(body) or _DATE_ANY_RE.search(m.group(2)) or _DATE_ANY_RE.search(body)
        status_m = _STATUS_BODY_RE.search(body)
        status = status_m.group(1).strip().rstrip(".") if status_m else "—"
        # Keep the column scannable: drop "· **Story:** #NNN (...)" suffixes and long tails —
        # cut at the first separator, then hard-cap at a word boundary (no unbalanced markdown).
        status = re.split(r"\s*[·;—]\s+", status)[0].strip()
        if len(status) > 40:
            status = status[:40].rsplit(" ", 1)[0].rstrip(" ,(") + "…"
        if status.count("**") % 2:
            status = status.replace("**", "")
        # Pipes in titles/status would break the markdown table
        records.append(
            {
                "num": m.group(1),
                "title": title.replace("|", "\\|"),
                "status": status.replace("|", "\\|")[:40],
                "date": date_m.group(1) if date_m else "—",
            }
        )
    return records


def _build_table(records: list[dict]) -> str:
    lines = [
        START_MARKER,
        "| # | Title | Status | Date |",
        "|---|-------|--------|------|",
    ]
    for r in records:
        lines.append(f"| ADR-{r['num']} | {r['title']} | {r['status']} | {r['date']} |")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main():
    is_apply = "--apply" in sys.argv
    is_check = "--check" in sys.argv
    if is_apply and is_check:
        print("error: --check and --apply are mutually exclusive", file=sys.stderr)
        sys.exit(2)

    src = DECISIONS.read_text(encoding="utf-8")
    if START_MARKER not in src or END_MARKER not in src:
        print(f"error: ADR-INDEX markers not found in {DECISIONS} — add them around the index table", file=sys.stderr)
        sys.exit(2)

    records = _records(src)
    if len(records) < 50:  # sanity floor — a parse regression must not wipe the index
        print(f"error: only {len(records)} ADR headings parsed (< 50) — refusing to regenerate", file=sys.stderr)
        sys.exit(2)

    # Consistency oracle (#1321): every ADR number visible to a permissive any-level heading
    # scan must be a parsed record. A mismatch means a record is headed at a level (or in a
    # form) _HEADING_RE can't see — regenerating would re-certify a silent omission, so this
    # is a hard error in every mode, never a warning.
    rec_nums = [r["num"] for r in records]
    dupes = sorted({n for n in rec_nums if rec_nums.count(n) > 1})
    if dupes:
        print(f"error: duplicate ADR record heading(s): {', '.join('ADR-' + n for n in dupes)}", file=sys.stderr)
        sys.exit(2)
    all_nums = set(_ANY_ADR_HEADING_RE.findall(src))
    unparsed = sorted(all_nums - set(rec_nums))
    if unparsed:
        print(
            f"error: {len(unparsed)} ADR number(s) appear in headings the record parser cannot see: "
            f"{', '.join('ADR-' + n for n in unparsed)} — extend _HEADING_RE (#1321)",
            file=sys.stderr,
        )
        sys.exit(2)
    assert len(records) == len(all_nums), "record count must equal distinct ADR numbers"

    # Unused numbers in the sequence (skipped/merged — see #817): warn, never fail.
    lo, hi = min(int(n) for n in all_nums), max(int(n) for n in all_nums)
    gaps = [f"ADR-{i:03d}" for i in range(lo, hi + 1) if f"{i:03d}" not in all_nums]
    if gaps:
        print(f"⚠️  unused ADR number(s) in the {lo:03d}–{hi:03d} sequence (skipped/merged — see #817): {', '.join(gaps)}")

    table = _build_table(records)
    pre, rest = src.split(START_MARKER, 1)
    _, post = rest.split(END_MARKER, 1)
    new_src = pre + table + post

    # Derive the header count line too — a hand-maintained "N ADRs total" rots (#1321).
    if _COUNT_LINE_RE.search(new_src):
        new_src = _COUNT_LINE_RE.sub(f"> {len(records)} ADRs total (ADR-{lo:03d} → ADR-{hi:03d})", new_src, count=1)
    else:
        print("warning: '> N ADRs total (ADR-AAA → ADR-ZZZ)' header line not found — count not rewritten", file=sys.stderr)

    if new_src == src:
        print(f"✅ ADR index current ({len(records)} records, ADR-{records[0]['num']} → ADR-{records[-1]['num']}).")
        sys.exit(0)

    if is_check:
        print(f"❌ ADR index is STALE ({len(records)} records exist). Fix: python3 scripts/generate_adr_index.py --apply")
        sys.exit(1)
    if is_apply:
        DECISIONS.write_text(new_src, encoding="utf-8")
        print(f"✅ Regenerated ADR index: {len(records)} records (ADR-{records[0]['num']} → ADR-{records[-1]['num']}).")
    else:
        print(f"Would regenerate index with {len(records)} records (ADR-{records[0]['num']} → ADR-{records[-1]['num']}). Pass --apply.")


if __name__ == "__main__":
    main()
