#!/usr/bin/env python3
"""scripts/generate_adr_index.py — regenerate the ADR index table in docs/DECISIONS.md.

THE PROBLEM THIS SOLVES:
  The hand-written index table stalled at ADR-057 while the file grew to 120+ records
  (header claimed "94 ADRs total" while ADR-133 existed). The institutional "why" was
  unnavigable past ADR-057 without grep. Hand-maintained indexes of append-only logs
  always rot; this derives the index from the headings themselves.

WHAT IT DOES:
  Parses every `## ADR-NNN` heading in docs/DECISIONS.md, extracts title + date +
  status from each record body (both body styles supported: the classic
  `**Date:** / **Status:**` block and the newer prose style with the date in the
  heading), and rewrites the table between the ADR-INDEX markers:

      <!-- ADR-INDEX:START (generated by scripts/generate_adr_index.py — do not hand-edit) -->
      ...
      <!-- ADR-INDEX:END -->

USAGE:
  python3 scripts/generate_adr_index.py            # dry run (prints what would change)
  python3 scripts/generate_adr_index.py --apply    # rewrite the index in place
  python3 scripts/generate_adr_index.py --check    # CI gate: exit 1 if index is stale

Run after adding an ADR (the wrap skill's doc-impact sweep covers this).
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "docs" / "DECISIONS.md"

START_MARKER = "<!-- ADR-INDEX:START (generated by scripts/generate_adr_index.py — do not hand-edit) -->"
END_MARKER = "<!-- ADR-INDEX:END -->"

_HEADING_RE = re.compile(r"^## ADR-(\d{3})\s*[:—–-]?\s*(.*)$", re.MULTILINE)
_DATE_BODY_RE = re.compile(r"\*\*Date:?\*\*:?\s*(\d{4}-\d{2}-\d{2})")
_DATE_ANY_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
_STATUS_BODY_RE = re.compile(r"\*\*Status:?\*\*:?\s*([^\n]+)")


def _records(src: str) -> list[dict]:
    matches = list(_HEADING_RE.finditer(src))
    records = []
    for i, m in enumerate(matches):
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[m.end() : body_end]
        title = m.group(2).strip() or "(untitled)"
        # Date: prefer an explicit **Date:** field, else a date literal in the heading, else the first in the body
        date_m = _DATE_BODY_RE.search(body) or _DATE_ANY_RE.search(m.group(2)) or _DATE_ANY_RE.search(body)
        status_m = _STATUS_BODY_RE.search(body)
        status = status_m.group(1).strip().rstrip(".") if status_m else "—"
        # Keep the column scannable: drop "· **Story:** #NNN (...)" suffixes and long tails —
        # cut at the first separator, then hard-cap at a word boundary (no unbalanced markdown).
        status = re.split(r"\s*[·;—]\s+", status)[0].strip()
        if len(status) > 40:
            status = status[:40].rsplit(" ", 1)[0].rstrip(" ,(") + "…"
        if status.count("**") % 2:
            status = status.replace("**", "")
        # Pipes in titles/status would break the markdown table
        records.append(
            {
                "num": m.group(1),
                "title": title.replace("|", "\\|"),
                "status": status.replace("|", "\\|")[:40],
                "date": date_m.group(1) if date_m else "—",
            }
        )
    return records


def _build_table(records: list[dict]) -> str:
    lines = [
        START_MARKER,
        "| # | Title | Status | Date |",
        "|---|-------|--------|------|",
    ]
    for r in records:
        lines.append(f"| ADR-{r['num']} | {r['title']} | {r['status']} | {r['date']} |")
    lines.append(END_MARKER)
    return "\n".join(lines)


def main():
    is_apply = "--apply" in sys.argv
    is_check = "--check" in sys.argv
    if is_apply and is_check:
        print("error: --check and --apply are mutually exclusive", file=sys.stderr)
        sys.exit(2)

    src = DECISIONS.read_text(encoding="utf-8")
    if START_MARKER not in src or END_MARKER not in src:
        print(f"error: ADR-INDEX markers not found in {DECISIONS} — add them around the index table", file=sys.stderr)
        sys.exit(2)

    records = _records(src)
    if len(records) < 50:  # sanity floor — a parse regression must not wipe the index
        print(f"error: only {len(records)} ADR headings parsed (< 50) — refusing to regenerate", file=sys.stderr)
        sys.exit(2)

    table = _build_table(records)
    pre, rest = src.split(START_MARKER, 1)
    _, post = rest.split(END_MARKER, 1)
    new_src = pre + table + post

    if new_src == src:
        print(f"✅ ADR index current ({len(records)} records, ADR-{records[0]['num']} → ADR-{records[-1]['num']}).")
        sys.exit(0)

    if is_check:
        print(f"❌ ADR index is STALE ({len(records)} records exist). Fix: python3 scripts/generate_adr_index.py --apply")
        sys.exit(1)
    if is_apply:
        DECISIONS.write_text(new_src, encoding="utf-8")
        print(f"✅ Regenerated ADR index: {len(records)} records (ADR-{records[0]['num']} → ADR-{records[-1]['num']}).")
    else:
        print(f"Would regenerate index with {len(records)} records (ADR-{records[0]['num']} → ADR-{records[-1]['num']}). Pass --apply.")


if __name__ == "__main__":
    main()
