#!/usr/bin/env python3
"""portrait_contact_sheet_1114.py — render the #1114 art-direction-v2 contact sheet.

Renders CURRENT signed portraits beside the three candidate directions (generated by
scripts/portrait_variants_1114.py) through the REAL renderer — site/assets/js/portraits.js
renderPortrait(), served over a local http.server and screenshotted with Playwright (the
render-qa pattern) — never a re-implementation, so what Matthew judges is what would ship.

Sheet contract (runbook §3 + #1114): every cell at 96/56/40 px, light AND dark theme
blocks, the CURRENT portrait first in each row for comparison, plus the mandatory
silhouette-litmus rows (solid single-colour shapes, no names — runbook §1).

Outputs:
    qa-screenshots/portrait_contact_sheet_1114.png          ONE composite (both themes)
    qa-screenshots/portrait_1114/<coach>__<col>__<theme>.png  individual cell shots

Usage:
    python3 scripts/portrait_variants_1114.py          # (re)generate candidates first
    python3 scripts/portrait_contact_sheet_1114.py
"""

import http.server
import json
import os
import socketserver
import sys
import threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scripts.portrait_variants_1114 import ART, VARIANTS  # noqa: E402

RECIPE_DIR = os.path.join(ROOT, "config", "portraits")
CAND_DIR = os.path.join(RECIPE_DIR, "candidates_1114")
OUT_DIR = os.path.join(ROOT, "qa-screenshots")
CELL_DIR = os.path.join(OUT_DIR, "portrait_1114")

COACHES = list(ART)  # elena_voss, eli_marsh, sarah_chen, lisa_park
COLUMNS = ("current",) + VARIANTS
COLUMN_LABELS = {
    "current": "CURRENT (shipped)",
    "v1_unframed": "V1 — unframed, soft ink",
    "v2_openarc": "V2 — open arc, soft ink",
    "v3_backdrop": "V3 — backdrop coin, soft ink",
}
SIZES = (96, 56, 40)

# Coach identity channel (--coach), from config/board_of_directors.json members.*.color.
COACH_COLOR = {}


def _load_colors():
    with open(os.path.join(ROOT, "config", "board_of_directors.json")) as f:
        members = json.load(f).get("members", {})
    for pid in COACHES:
        COACH_COLOR[pid] = members.get(pid, {}).get("color") or "#b45309"


def _load_recipes():
    data = {}
    names = {}
    for pid in COACHES:
        with open(os.path.join(RECIPE_DIR, f"{pid}.json")) as f:
            data[f"{pid}__current"] = json.load(f)
        names[pid] = pid.replace("_", " ").title()
        for variant in VARIANTS:
            with open(os.path.join(CAND_DIR, f"{pid}__{variant}.json")) as f:
                data[f"{pid}__{variant}"] = json.load(f)
    return data, names


PAGE_CSS = """
* { margin:0; padding:0; box-sizing:border-box; animation:none !important; transition:none !important; }
body { font: 13px/1.45 -apple-system, "Helvetica Neue", sans-serif; }
.theme { padding: 20px 26px 30px; }
.theme-light { background:#faf7f2; color:#1d1a14; }
.theme-dark  { background:#14120f; color:#ece3d2; }
h1 { font-size:17px; margin-bottom:2px; }
.sub { opacity:0.65; margin-bottom:14px; font-size:12px; }
table { border-collapse:collapse; }
th, td { padding: 8px 12px; text-align:left; vertical-align:bottom; }
th { font-size:11px; letter-spacing:0.04em; text-transform:uppercase; opacity:0.75; }
td.name { font-weight:600; font-size:12px; vertical-align:middle; white-space:nowrap; }
tr { border-top: 1px solid rgba(128,128,128,0.25); }
.cell { display:flex; align-items:flex-end; gap:10px; }
.pbox { display:flex; flex-direction:column; align-items:center; gap:3px; }
.pbox .px { font-size:9px; opacity:0.5; }
.pbox svg { display:block; }
/* proposed renderer knob demoed via CSS: variant columns soften ink 1.7 → 1.3 */
.soft .pt-stroke { stroke-width: 1.3px; }
/* silhouette litmus (runbook §1): solid single-colour shapes, nothing else */
.sil svg path, .sil svg line, .sil svg circle { fill: currentColor !important; stroke: currentColor !important; }
.sil-note { font-size:10px; opacity:0.55; }
"""

PAGE_JS = """
import { renderPortrait } from "/assets/js/portraits.js";
const DATA = JSON.parse(document.getElementById("sheet-data").textContent);
const { recipes, coaches, columns, columnLabels, sizes, colors, names } = DATA;

function cellHTML(pid, col, theme, sizesToUse, silhouette) {
  const recipe = recipes[`${pid}__${col}`];
  const boxes = sizesToUse.map((s) => {
    const svg = renderPortrait(recipe, { name: names[pid] }, { title: "", size: s });
    return `<div class="pbox"><span style="width:${s}px;height:${s * 1.2}px;display:block">${svg}</span>` +
      `<span class="px">${s}px</span></div>`;
  }).join("");
  const soft = col === "current" ? "" : " soft";
  const sil = silhouette ? " sil" : "";
  const id = `cell-${pid}--${col}--${theme}${silhouette ? "--sil" : ""}`;
  return `<div class="cell${soft}${sil}" id="${id}" style="--coach:${colors[pid]}">${boxes}</div>`;
}

function themeBlock(theme) {
  let h = `<section class="theme theme-${theme}" id="theme-${theme}">`;
  h += `<h1>#1114 portrait art direction v2 — contact sheet (${theme} theme)</h1>`;
  h += `<div class="sub">direction: "real future-AI characters, Pixar/cartoon energy, 3D feeling" · ` +
    `rendered by the real portraits.js renderPortrait() · variant columns demo the proposed 1.3px ink (CSS knob) · ` +
    `candidates are UNSIGNED (ADR-106 gate pending)</div>`;
  h += "<table><thead><tr><th></th>";
  for (const col of columns) h += `<th>${columnLabels[col]}</th>`;
  h += "</tr></thead><tbody>";
  for (const pid of coaches) {
    h += `<tr><td class="name">${names[pid]}</td>`;
    for (const col of columns) h += `<td>${cellHTML(pid, col, theme, sizes, false)}</td>`;
    h += "</tr>";
  }
  h += `<tr><td class="name">silhouette litmus<div class="sil-note">(runbook §1 — who is who?)</div></td>`;
  for (const col of columns) {
    h += "<td><div style='display:flex;gap:8px'>";
    for (const pid of coaches) h += cellHTML(pid, col, theme, [56], true);
    h += "</div></td>";
  }
  h += "</tr></tbody></table></section>";
  return h;
}

document.getElementById("sheet").innerHTML = themeBlock("light") + themeBlock("dark");
document.body.dataset.ready = "1";
"""


def build_page(recipes, names):
    data = {
        "recipes": recipes,
        "coaches": COACHES,
        "columns": list(COLUMNS),
        "columnLabels": COLUMN_LABELS,
        "sizes": list(SIZES),
        "colors": COACH_COLOR,
        "names": names,
    }
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<style>{PAGE_CSS}</style></head><body>"
        f"<script type='application/json' id='sheet-data'>{json.dumps(data)}</script>"
        "<div id='sheet'></div>"
        f"<script type='module'>{PAGE_JS}</script>"
        "</body></html>"
    )


def serve_and_shoot(page_html):
    from playwright.sync_api import sync_playwright

    # Serve a scratch root: the page at /, the REAL site assets via symlink.
    scratch = os.path.join(OUT_DIR, "_sheet_root_1114")
    os.makedirs(scratch, exist_ok=True)
    link = os.path.join(scratch, "assets")
    if not os.path.islink(link):
        os.symlink(os.path.join(ROOT, "site", "assets"), link)
    with open(os.path.join(scratch, "contact_sheet.html"), "w") as f:
        f.write(page_html)

    handler = type("H", (http.server.SimpleHTTPRequestHandler,), {"directory": scratch, "log_message": lambda *a: None})
    httpd = socketserver.TCPServer(("127.0.0.1", 0), lambda *a, **kw: handler(*a, directory=scratch, **kw))
    port = httpd.server_address[1]
    threading.Thread(target=httpd.serve_forever, daemon=True).start()

    os.makedirs(CELL_DIR, exist_ok=True)
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            page = browser.new_page(viewport={"width": 1780, "height": 1200}, device_scale_factor=2)
            page.goto(f"http://127.0.0.1:{port}/contact_sheet.html")
            page.wait_for_selector("body[data-ready='1']", timeout=15000)
            composite = os.path.join(OUT_DIR, "portrait_contact_sheet_1114.png")
            page.screenshot(path=composite, full_page=True)
            print(f"✅ composite → {os.path.relpath(composite, ROOT)}")
            for theme in ("light", "dark"):
                for pid in COACHES:
                    for col in COLUMNS:
                        sel = f"#cell-{pid}--{col}--{theme}"
                        shot = os.path.join(CELL_DIR, f"{pid}__{col}__{theme}.png")
                        page.locator(sel).screenshot(path=shot)
            print(f"✅ {len(COACHES) * len(COLUMNS) * 2} cell shots → {os.path.relpath(CELL_DIR, ROOT)}/")
            browser.close()
    finally:
        httpd.shutdown()


def main():
    _load_colors()
    recipes, names = _load_recipes()
    serve_and_shoot(build_page(recipes, names))
    return 0


if __name__ == "__main__":
    sys.exit(main())
