#!/usr/bin/env python3
"""v4_build_stack_manifest.py — generate site/data/stack.json, the public instrument manifest (#1401).

"Fork the architecture, not the data." This is the machine-readable description of the
INSTRUMENT — what measures, how it ingests, what protocols and supplements are under
measurement, and what it costs to own. It is NOT a description of the subject: no health
metrics, no weights, no lab values, no per-day records ever appear here.

EVERY FIELD IS DERIVED. Nothing in this file is a hand-typed restatement of a list that
lives somewhere else — that is the anti-pattern this repo has been bitten by seven times
("guard the SET, not the instance"). The derivation chain:

  sources      ← scripts/v4_build_data_sources.py::build()
                 which is itself lambdas/ingestion/source_registry.py::catalog_entries()
                 plus that generator's clinical/archive rows. Using the SAME entry point
                 as /data/data_sources.json means the `catalog: False` gate (sources
                 wired but not yet publicly advertised — #1669) applies here for free:
                 this manifest can never advertise a source the public catalogue doesn't.
  ingest facets← lambdas/ingestion/source_registry.py::SOURCE_REGISTRY (oauth / active_api
                 / behavioral / paused / raw_layout.scheme), read per source id.
  devices      ← scripts/v4_build_gear.py::GEAR (product + vendor + gear-vs-other), which
                 already carries its own coverage assert against catalog_entries().
  protocols    ← site/config/protocols.json (the file the site itself serves).
  supplements  ← site/config/supplement_registry.json (the PUBLISHED copy — deriving from
                 the served artifact rather than config/ structurally guarantees this
                 manifest cannot widen the public granularity by one item).
  cost         ← config/cost_of_ownership.json, the one honest, sourced cost ledger.

PRIVACY. Only fields already public on averagejoematt.com are projected. From the
supplement registry we take name / group / evidence grade / dose / timing / paused /
monthly cost — the exact columns /protocols/supplements/ already renders. From protocols
we take the definition fields (what the protocol IS) and deliberately NOT `key_finding`,
`signal_note`, `signal_status` or `adherence_target`: those are results about Matthew,
and this manifest describes the instrument.

Regenerated by deploy/sync_site_to_s3.sh next to v4_build_data_sources.py, and pinned by
tests/test_stack_manifest_drift.py — never hand-edit site/data/stack.json.

Run from repo root:  python3 scripts/v4_build_stack_manifest.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "lambdas"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

# The lambda modules below read config at import; give them the inert values the test
# suite uses so a build never touches a real account. Nothing here is deployed.
for _k, _v in (
    ("TABLE_NAME", "life-platform-build"),
    ("S3_BUCKET", "build-bucket"),
    ("USER_ID", "matthew"),
    ("AWS_DEFAULT_REGION", "us-west-2"),
):
    os.environ.setdefault(_k, _v)

from ingestion.source_registry import SOURCE_REGISTRY  # noqa: E402 — per-source ingest facets
from operational.cost_governor_lambda import (  # noqa: E402 — THE ceiling constants (ADR-063/133)
    MONTHLY_CEILING,
    SURGE_CEILING_USD,
    SURGE_UNIQUES_THRESHOLD,
)
from v4_build_data_sources import build as build_data_sources  # noqa: E402 — THE public source set
from v4_build_gear import GEAR  # noqa: E402 — consumer-product identity per source
from web.site_api_common import PLATFORM_STATS  # noqa: E402 — THE published run-rate (/method/cost/)

OUT = ROOT / "site" / "data" / "stack.json"
SCHEMA_URL = "/data/stack.schema.json"
SCHEMA_VERSION = "1.0.0"

# ── Ingest-pattern vocabulary. A CLOSED set: the schema enumerates it and the drift test
#    asserts every emitted pattern is a member, so a new source with an unrecognised
#    method string fails the build loudly instead of quietly becoming "manual_entry".
INGEST_PATTERNS = (
    "scheduled_credentialed_pull",  # scheduled API pull behind a credential that can expire or be rotated
    "scheduled_keyless_pull",  # scheduled API pull with no credential to expire
    "webhook_push",  # provider pushes to a Function URL, near-real-time
    "file_transport",  # a file lands in cloud storage and a poller picks it up
    "habit_bridge",  # projected out of another source's habit records
    "manual_entry",  # a human types it in (MCP tool, form, lab PDF)
    "frozen_archive",  # historical import, no live writer
)


def _ingest_pattern(source_id: str, method: str) -> str:
    """Classify how a source's data arrives. Registry facets first (they are structured
    truth); the method string only decides for rows that have no registry entry."""
    entry = SOURCE_REGISTRY.get(source_id)
    m = method.lower()
    if entry is not None:
        if entry.get("active_api"):
            return "scheduled_credentialed_pull" if entry.get("oauth") else "scheduled_keyless_pull"
        if "webhook" in m:
            return "webhook_push"
        if "dropbox" in m:
            return "file_transport"
        if "bridge" in m:
            return "habit_bridge"
        if "manual" in m or "log" in m:
            return "manual_entry"
    else:
        if "frozen archive" in m:
            return "frozen_archive"
        if "webhook" in m:
            return "webhook_push"
        if "manual" in m or "import" in m:
            return "manual_entry"
    raise SystemExit(f"v4_build_stack_manifest: no ingest pattern for source {source_id!r} (method={method!r}) — extend _ingest_pattern")


def _sources() -> list[dict[str, Any]]:
    rows = []
    for row in build_data_sources()["sources"]:
        sid = row["id"]
        entry = SOURCE_REGISTRY.get(sid, {})
        gear = GEAR.get(sid, {})
        out: dict[str, Any] = {
            "id": sid,
            "name": row["name"],
            "category": row["category"],
            "measures": row["metrics"],
            "method": row["method"],
            "posture": row["posture"],
            "ingest_pattern": _ingest_pattern(sid, row["method"]),
            # behavioral: a record exists only when a human DOES something, so a gap is a
            # logging lapse, not a broken pipe. The single most useful thing to copy from
            # this architecture — it decides what may page you at 3am.
            "behavioral": bool(entry.get("behavioral")),
            "paused": bool(entry.get("paused")),
        }
        layout = entry.get("raw_layout")
        if layout:
            # the SHAPE of the raw archive, never a concrete key or bucket name
            out["raw_scheme"] = layout["scheme"]
        if gear:
            out["device"] = {
                "product": gear["product"],
                "vendor": gear["vendor"],
                "purchasable": gear["kind"] == "gear",
            }
        rows.append(out)
    return rows


def _protocols() -> list[dict[str, Any]]:
    """Protocol DEFINITIONS from the catalogue the site serves. Results fields
    (key_finding / signal_note / signal_status / adherence_target) are deliberately
    dropped: they describe the subject, not the instrument."""
    raw = json.loads((ROOT / "site" / "config" / "protocols.json").read_text(encoding="utf-8"))
    rows = []
    for p in raw["protocols"]:
        rows.append(
            {
                "id": p["id"],
                "name": p["name"],
                "domain": p["domain"],
                "category": p["category"],
                "tier": p["tier"],
                "status": p["status"],
                "definition": p["description"],
                "mechanism": p["mechanism"],
                "tracked_by": p["tracked_by"],
                "key_metrics": p["key_metrics"],
            }
        )
    return sorted(rows, key=lambda r: (r["tier"], r["name"]))


def _supplements() -> list[dict[str, Any]]:
    """Projected from the PUBLISHED registry copy at the granularity
    /protocols/supplements/ already renders. Adding a field here widens what is public —
    don't, without an explicit privacy decision."""
    raw = json.loads((ROOT / "site" / "config" / "supplement_registry.json").read_text(encoding="utf-8"))
    rows = []
    for group_key, group in raw["groups"].items():
        for item in group["items"]:
            rows.append(
                {
                    "key": item["key"],
                    "name": item["name"],
                    "group": group_key,
                    "group_name": group["name"],
                    "dose": item["dose"],
                    "timing": item["timing"],
                    # evidence grade + the registry's own confidence percentage, verbatim
                    "evidence": {"grade": item["ev"], "confidence_pct": item["evPct"]},
                    "cost_monthly_usd": item["cost_monthly"],
                    "paused": bool(item.get("paused")),
                }
            )
    return sorted(rows, key=lambda r: (r["group"], r["name"]))


def _cost(supplements: list[dict[str, Any]], sources: list[dict[str, Any]]) -> dict[str, Any]:
    """The cost-of-ownership block. Every figure carries `basis` (how it was derived) and
    `confidence`; nothing here is a confident number without a source (ADR-104/105).

    Split by origin: `config/cost_of_ownership.json` supplies only what no code knows
    (the Cost Explorer actuals, the composition ranges, and the two dimensions this
    platform genuinely doesn't measure). Everything else is injected here from its real
    origin, so the manifest cannot say a different number than the live cost page does."""
    ledger = json.loads((ROOT / "config" / "cost_of_ownership.json").read_text(encoding="utf-8"))
    ledger.pop("_description", None)  # build-side provenance note; not for readers

    # ── AWS run-rate + ceilings, straight from the constants the site itself serves.
    #    `monthly_cost` is the same field /method/cost/ renders via /api/platform_stats,
    #    so the manifest and the cost page cannot disagree by construction.
    ledger["aws"]["monthly_usd_typical"] = PLATFORM_STATS["monthly_cost"]
    ledger["aws"]["monthly_usd_typical_basis"] = (
        "the run-rate published on /method/cost/, read from the same constant the "
        "/api/platform_stats endpoint serves — not a second opinion about it."
    )
    ledger["aws"]["ceiling_usd"] = MONTHLY_CEILING
    ledger["aws"]["surge_ceiling_usd"] = SURGE_CEILING_USD
    ledger["aws"]["surge_trigger_trailing_7d_uniques"] = SURGE_UNIQUES_THRESHOLD
    ledger["aws"]["ceiling_basis"] = (
        "a self-imposed hard limit (ADR-063/133), enforced in code rather than aspired to: a governor "
        "reprojects month-end spend every 8 hours and publishes a degradation tier, and each AI feature "
        "reads that tier before it runs. The limit floats to the surge value only while real reader "
        "traffic exceeds the trigger above."
    )

    # ── Supplements: computed from this manifest's own catalogue projection, so the total
    #    can never disagree with the per-item rows a reader can add up themselves.
    active = sum(s["cost_monthly_usd"] for s in supplements if not s["paused"])
    total = sum(s["cost_monthly_usd"] for s in supplements)
    ledger["supplements"] = {
        "active_monthly_usd": active,
        "including_paused_monthly_usd": total,
        "item_count": len(supplements),
        "paused_count": sum(1 for s in supplements if s["paused"]),
        "basis": "summed from this manifest's own supplements[].cost_monthly_usd — the published "
        "/protocols/supplements/ catalogue. The per-item inputs are the owner's typical retail "
        "spend at his chosen brands, not receipts, so treat the total as a shopping estimate.",
        "confidence": "arithmetic-exact over estimated inputs",
    }

    # ── Time: no hours figure exists, but the SHAPE of the recurring human burden is
    #    derivable from the source set, so publish that instead of a guess.
    ledger["time"]["recurring_manual_touchpoints"] = {
        "credentialed_sources_that_can_need_reauth": sum(
            1 for s in sources if s["ingest_pattern"] == "scheduled_credentialed_pull" and not s["paused"]
        ),
        "sources_whose_records_require_typing": sum(1 for s in sources if s["ingest_pattern"] == "manual_entry"),
        "basis": "counted from this manifest's own sources[]. These are the only two places a human "
        "recurrently has to act; everything else runs on a scheduler.",
    }
    return ledger


def build() -> dict[str, Any]:
    supplements = _supplements()
    sources = _sources()
    return {
        "$schema": SCHEMA_URL,
        "_meta": {
            "generated_by": "scripts/v4_build_stack_manifest.py — derived from source_registry.py + the public "
            "protocol/supplement catalogues (#1401); never hand-edit",
            "schema_version": SCHEMA_VERSION,
            "updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "framing": "Fork the architecture, not the data. This describes the instrument — what measures and "
            "how — and contains no health metrics, no personal records, and no account-specific identifiers.",
            "license": "The manifest is published for reuse. It is a description, not a guarantee.",
        },
        "architecture": _architecture(sources),
        "sources": sources,
        "protocols": _protocols(),
        "supplements": supplements,
        "cost_of_ownership": _cost(supplements, sources),
    }


def _architecture(sources: list[dict[str, Any]]) -> dict[str, Any]:
    """The shape of the pipeline, in vendor-neutral terms. Counts are derived; no ARNs, no
    account id, no bucket name, no function names."""
    patterns = sorted({r["ingest_pattern"] for r in sources})
    return {
        "shape": "ingest → store → serve",
        "cloud": "AWS, single region",
        "stages": [
            {
                "stage": "ingest",
                "what": "scheduled and webhook-driven functions pull each source, detect missing days, and fetch only the gap",
                "services": ["serverless functions", "cron scheduler", "managed secrets"],
            },
            {
                "stage": "store",
                "what": "raw provider JSON archived immutably to object storage; normalized daily metrics to a single-table key-value store",
                "services": ["object storage", "single-table NoSQL"],
            },
            {
                "stage": "serve",
                "what": "a read-only HTTP API over the store, a static site on a CDN, scheduled email, and an MCP server for conversational access",
                "services": ["serverless HTTP API", "CDN + static hosting", "transactional email", "MCP"],
            },
        ],
        "ingest_patterns": patterns,
        "key_choices": [
            "single-table NoSQL with a composite key (partition = user+source, sort = date) — every source shares one table",
            "raw archive is write-once and delete-protected; normalization is always re-derivable from it",
            "each source is classified behavioral vs infrastructure — only infrastructure staleness is allowed to page you",
            "one source registry is the single origin for freshness thresholds, QA tiers, alarms, and every public catalogue",
            "stdlib HTTP only for provider calls — no third-party HTTP dependency to keep patched",
        ],
    }


def main() -> None:
    payload = build()
    if OUT.exists():
        try:
            current = json.loads(OUT.read_text(encoding="utf-8"))
            stamp = current.get("_meta", {}).get("updated")
            probe = json.loads(json.dumps(payload))
            probe["_meta"]["updated"] = stamp
            if current == probe:
                print(f"stack.json unchanged ({len(payload['sources'])} sources)")
                return
        except (json.JSONDecodeError, OSError, KeyError):
            pass
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(
        f"stack.json regenerated: {len(payload['sources'])} sources, "
        f"{len(payload['protocols'])} protocols, {len(payload['supplements'])} supplements"
    )


if __name__ == "__main__":
    main()
