#!/usr/bin/env python3
"""Render the Permanence Contract's reader terms into the public page (#2574).

#1400 shipped the mechanism and wrote the contract down twice on purpose — as
prose in ``docs/PERMANENCE_CONTRACT.md`` and as data in
``lambdas/operational/permanence_terms.py`` — with
``tests/test_permanence_contract_1400.py`` asserting the two agree. This script
adds the third surface without adding a third source of truth: it *derives* the
public page's clause list from the marked block in the document, so a clause can
never be edited on the site without being edited in the contract.

The rule the whole file exists to enforce: **nobody hand-copies a clause.**
A hand-copied clause is a promise that drifts, and a promise that drifts is the
exact failure #1400 was designed against.

What is generated and what is not:

* generated — the clause list only, between the markers in
  ``site/privacy/index.html``. Nothing else on that page is touched.
* not generated — the section's introduction, the live-archive panel, and the
  script that fills it. Those describe *current* state, which is read from the
  published documents at page load, never baked in.

The version number is deliberately NOT rendered from the document. The issue's
own note: a stated version must be read from the published continuity document
rather than hard-coded, so the page shows the edition it was *built* from as a
data attribute and lets the page script reconcile it against the live one.

Usage::

    python3 scripts/v4_build_permanence_terms.py            # write
    python3 scripts/v4_build_permanence_terms.py --check    # verify, exit 1 on drift
"""

from __future__ import annotations

import argparse
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if os.path.join(ROOT, "lambdas") not in sys.path:
    sys.path.insert(0, os.path.join(ROOT, "lambdas"))

from operational import permanence_terms as terms  # noqa: E402

DOC_PATH = os.path.join(ROOT, "docs", "PERMANENCE_CONTRACT.md")
PAGE_PATH = os.path.join(ROOT, "site", "privacy", "index.html")

READER_START = "<!-- BEGIN READER TERMS -->"
READER_END = "<!-- END READER TERMS -->"

PAGE_START = "<!-- BEGIN PERMANENCE TERMS · generated by scripts/v4_build_permanence_terms.py -->"
PAGE_END = "<!-- END PERMANENCE TERMS -->"

# Mirrors tests/test_permanence_contract_1400.py::_INFRA_TELLS. The reader page
# inherits the same constraint the marked block carries: no bucket, service or
# module name reaches a reader.
INFRA_TELLS = (
    "matthew-life-platform",
    "arn:aws",
    ".amazonaws.com",
    "s3://",
    "dynamodb",
    "cloudfront",
    "boto3",
    "lambda_handler",
    "us-west-2",
    "generated/",
)

KIND_LABEL = {
    terms.POLICY: "policy",
    terms.MECHANISM: "mechanism",
    terms.LIMIT: "limit",
}


def read_reader_block(doc_text: str) -> str:
    """The marked, reader-facing half of the contract — the only copy this
    script is allowed to read."""
    start = doc_text.index(READER_START) + len(READER_START)
    end = doc_text.index(READER_END)
    return doc_text[start:end]


def parse_clauses(block: str) -> list[dict]:
    """Split the marked block into clauses.

    Deliberately strict: an unrecognised construct raises rather than being
    dropped silently, because a clause quietly missing from the page is the
    same defect as a clause quietly rewritten on it.
    """
    # Drop HTML comments (the block carries an explanatory one) and the
    # version line, which the page reads live instead of baking in.
    body = re.sub(r"<!--.*?-->", "", block, flags=re.S)

    parts = re.split(r"^### (P\d+) · (.+?)$", body, flags=re.M)
    preamble = parts[0]
    if re.search(r"^\s*[A-Za-z]", preamble.replace("**Version", ""), flags=re.M) and "Version" not in preamble:
        raise ValueError(f"unexpected prose before the first clause heading: {preamble.strip()[:120]!r}")

    clauses: list[dict] = []
    for i in range(1, len(parts), 3):
        clause_id, title, raw = parts[i], parts[i + 1], parts[i + 2]
        paragraphs = [re.sub(r"\s+", " ", p).strip() for p in raw.strip().split("\n\n")]
        paragraphs = [p for p in paragraphs if p]
        if not paragraphs:
            raise ValueError(f"{clause_id}: no body text under the heading")
        clauses.append({"id": clause_id, "title": title.strip(), "paragraphs": paragraphs})

    if not clauses:
        raise ValueError("no clauses found in the reader-terms block")
    return clauses


def reconcile(parsed: list[dict]) -> list[dict]:
    """Fold in the kind (policy / mechanism / limit) from the coded contract and
    assert the two sources still describe the same clause set.

    The kind is not in the prose, so it comes from ``CLAUSES``; the *text* never
    does, so a divergence here means the document and the code have drifted and
    the page must not be written from either.
    """
    coded = {c["id"]: c for c in terms.CLAUSES}
    if {c["id"] for c in parsed} != set(coded):
        raise ValueError(
            f"the document and the coded contract disagree — document: {sorted(c['id'] for c in parsed)}, code: {sorted(coded)}"
        )
    out = []
    for clause in parsed:
        code_clause = coded[clause["id"]]
        if clause["title"] != code_clause["title"]:
            raise ValueError(f"{clause['id']}: title differs — document {clause['title']!r}, code {code_clause['title']!r}")
        out.append(dict(clause, kind=code_clause["kind"]))
    return out


def render(clauses: list[dict]) -> str:
    """The clause list as HTML. Text is escaped, never interpreted — the source
    of truth is prose, and prose that happens to contain a bracket must not
    become markup."""
    # The built-from edition rides on the list, generated from the coded
    # contract. The page never *states* it — the script reconciles it against
    # the edition in the published continuity document and speaks up only if
    # the two have diverged, which is the honest version of a version number.
    lines = [PAGE_START, f'    <ol class="perm-clauses" data-built-version="{html.escape(terms.TERMS_VERSION)}">']
    for clause in clauses:
        lines.append(f'      <li class="perm-clause" id="clause-{html.escape(clause["id"])}">')
        lines.append(
            '        <p class="pc-head"><span class="pc-id">'
            + html.escape(clause["id"])
            + '</span><span class="pc-title">'
            + html.escape(clause["title"])
            + '</span><span class="pc-kind">'
            + html.escape(KIND_LABEL[clause["kind"]])
            + "</span></p>"
        )
        for paragraph in clause["paragraphs"]:
            lines.append("        <p>" + html.escape(paragraph) + "</p>")
        lines.append("      </li>")
    lines.append("    </ol>")
    lines.append("    " + PAGE_END)
    return "\n".join(lines)


def splice(page_text: str, rendered: str) -> str:
    if PAGE_START not in page_text or PAGE_END not in page_text:
        raise ValueError(f"{PAGE_PATH} carries no generated-terms markers — add {PAGE_START} / {PAGE_END} first")
    start = page_text.index(PAGE_START)
    end = page_text.index(PAGE_END) + len(PAGE_END)
    return page_text[:start] + rendered.strip() + page_text[end:]


def build() -> str:
    with open(DOC_PATH, encoding="utf-8") as fh:
        doc_text = fh.read()
    clauses = reconcile(parse_clauses(read_reader_block(doc_text)))
    rendered = render(clauses)

    lowered = rendered.lower()
    leaks = [tell for tell in INFRA_TELLS if tell in lowered]
    if leaks:
        raise ValueError(f"the rendered public terms leak infrastructure detail: {leaks}")

    with open(PAGE_PATH, encoding="utf-8") as fh:
        page_text = fh.read()
    return splice(page_text, rendered)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify the page matches the contract; exit 1 on drift")
    args = ap.parse_args()

    wanted = build()
    with open(PAGE_PATH, encoding="utf-8") as fh:
        current = fh.read()

    if current == wanted:
        print(f"permanence terms: {os.path.relpath(PAGE_PATH, ROOT)} matches the contract ({len(terms.CLAUSES)} clauses)")
        return 0
    if args.check:
        print(f"DRIFT: {os.path.relpath(PAGE_PATH, ROOT)} no longer matches docs/PERMANENCE_CONTRACT.md", file=sys.stderr)
        print("       run: python3 scripts/v4_build_permanence_terms.py", file=sys.stderr)
        return 1
    with open(PAGE_PATH, "w", encoding="utf-8") as fh:
        fh.write(wanted)
    print(f"permanence terms: wrote {len(terms.CLAUSES)} clauses into {os.path.relpath(PAGE_PATH, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
