#!/usr/bin/env python3
"""
v4_vendor_fonts.py — self-host the v4 fonts (CSP-safe).

The distribution's CSP is `style-src 'self'; font-src 'self' data:`, so the
Google Fonts CDN is blocked. This downloads the Fraunces / Instrument Sans /
IBM Plex Mono woff2 files Google serves and writes a local @font-face sheet, so
every font loads from 'self'. No CSP change needed.

Outputs:
  site/assets/fonts/v4/*.woff2
  site/assets/css/fonts.css   (the @font-face sheet, local src)

Run from repo root:  python3 scripts/v4_vendor_fonts.py
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

CSS2 = ("https://fonts.googleapis.com/css2?"
        "family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;1,9..144,400;1,9..144,500"
        "&family=IBM+Plex+Mono:wght@400;500"
        "&family=Instrument+Sans:wght@400;500&display=swap")
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

FONTS_DIR = Path("site/assets/fonts/v4")
CSS_OUT = Path("site/assets/css/fonts.css")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS2).decode("utf-8")
    urls = re.findall(r"https://fonts\.gstatic\.com/[^)]+\.woff2", css)
    uniq = sorted(set(urls))
    print(f"fetched css2 ({len(css)} bytes), {len(uniq)} unique woff2")

    mapping: dict[str, str] = {}
    for u in uniq:
        name = u.rsplit("/", 1)[-1]
        dest = FONTS_DIR / name
        if not dest.exists():
            dest.write_bytes(fetch(u))
        mapping[u] = f"/assets/fonts/v4/{name}"

    out = css
    for u, local in mapping.items():
        out = out.replace(u, local)
    header = ("/* fonts.css — self-hosted v4 type triad (CSP-safe; font-src 'self').\n"
              "   Generated by scripts/v4_vendor_fonts.py from Google Fonts. */\n")
    CSS_OUT.write_text(header + out, encoding="utf-8")
    total_kb = sum(f.stat().st_size for f in FONTS_DIR.glob("*.woff2")) // 1024
    print(f"wrote {CSS_OUT} + {len(uniq)} woff2 ({total_kb} KB) under {FONTS_DIR}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
