#!/usr/bin/env python3
"""
v4_vendor_fonts.py — self-host the v4 fonts (CSP-safe).

The distribution's CSP is `style-src 'self'; font-src 'self' data:`, so the
Google Fonts CDN is blocked. This downloads the Fraunces / Instrument Sans /
IBM Plex Mono woff2 files Google serves and writes a local @font-face sheet, so
every font loads from 'self'. No CSP change needed.

Latin-only subsetting (#580): Google's css2 response ships one @font-face block
per (weight, style, unicode-range subset) — e.g. Fraunces normal/400 gets a
`latin`, a `latin-ext`, a `vietnamese`, ... block, each pointing at a distinct
woff2. A browser only ever *fetches* the subset overlapping the page's actual
text (that's what unicode-range is for), so an English-only site's non-latin
blocks are dead weight: extra @font-face rules bloating fonts.css and extra
woff2 files vendored into the repo/deploy that no visitor's browser will ever
request. `_keep_latin_only` drops every subset but `latin` before download —
verified against actual usage in tokens.css/*.css: the triad is used at
weight 400/500 only (--weight-reg/--weight-med, no other numeric weight is a
CSS custom property), with italic used only for Fraunces (the "human voice"
token, ADR-071) — so all four Fraunces (normal/italic x 400/500) + both mono/
sans (normal x 400/500) latin blocks are genuinely referenced; nothing on the
weight/style axis is unused. The cut is real (18 files -> 5 files, 456KB ->
~194KB vendored) and it is purely a build/deploy-hygiene + fonts.css-payload
win — see docs/DESIGN_SYSTEM_V5.md "Performance budget".

Outputs:
  site/assets/fonts/v4/*.woff2   (latin subset only)
  site/assets/css/fonts.css      (the @font-face sheet, local src, latin only)

Run from repo root:  python3 scripts/v4_vendor_fonts.py
"""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

CSS2 = (
    "https://fonts.googleapis.com/css2?"
    "family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;1,9..144,400;1,9..144,500"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&family=Instrument+Sans:wght@400;500&display=swap"
)
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"

FONTS_DIR = Path("site/assets/fonts/v4")
CSS_OUT = Path("site/assets/css/fonts.css")

_SUBSET_COMMENT_RE = re.compile(r"/\* ([\w-]+) \*/")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def _keep_latin_only(css: str) -> str:
    """Drop every Google Fonts subset block except `latin` (see module docstring)."""
    parts = re.split(r"(/\* [\w-]+ \*/)", css)
    kept, keep_next = [], False
    for part in parts:
        m = _SUBSET_COMMENT_RE.match(part)
        if m:
            keep_next = m.group(1) == "latin"
            if keep_next:
                kept.append(part)
            continue
        if keep_next:
            kept.append(part)
    return "".join(kept)


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(CSS2).decode("utf-8")
    css = _keep_latin_only(css)
    urls = re.findall(r"https://fonts\.gstatic\.com/[^)]+\.woff2", css)
    uniq = sorted(set(urls))
    print(f"fetched css2, kept latin subset only ({len(css)} bytes), {len(uniq)} unique woff2")

    mapping: dict[str, str] = {}
    for u in uniq:
        name = u.rsplit("/", 1)[-1]
        dest = FONTS_DIR / name
        if not dest.exists():
            dest.write_bytes(fetch(u))
        mapping[u] = f"/assets/fonts/v4/{name}"

    out = css
    for u, local in mapping.items():
        out = out.replace(u, local)
    header = (
        "/* fonts.css — self-hosted v4 type triad (CSP-safe; font-src 'self').\n"
        "   Latin subset only (#580) — see module docstring for why.\n"
        "   Generated by scripts/v4_vendor_fonts.py from Google Fonts. */\n"
    )
    CSS_OUT.write_text(header + out, encoding="utf-8")

    # Prune previously-vendored files this run no longer references (e.g. a
    # re-run after this latin-only cut, or a future weight/style trim) so the
    # fonts dir never silently accumulates orphaned woff2s.
    keep_names = {u.rsplit("/", 1)[-1] for u in uniq}
    pruned = 0
    for f in FONTS_DIR.glob("*.woff2"):
        if f.name not in keep_names:
            f.unlink()
            pruned += 1

    total_kb = sum(f.stat().st_size for f in FONTS_DIR.glob("*.woff2")) // 1024
    print(
        f"wrote {CSS_OUT} + {len(uniq)} woff2 ({total_kb} KB) under {FONTS_DIR}/"
        + (f", pruned {pruned} orphaned file(s)" if pruned else "")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
