#!/usr/bin/env python3
"""v8_build_appendix.py — generate /next/v8/appendix/ from scripts/v8_appendix_pages.json (#4586).

The appendix is one plain list at the foot of the preview: every live page that is off the
usual path, so that nothing is deleted and nothing has to sit in a menu. It is a reference
list, never a second navigation: rows are grouped by what a page IS (at most four kinds, a
small label each) and sorted by title inside a kind.

The page is a kit page (docs/design/v8/README.md): `site/assets/css/clean.css` only, `ck-`
classes only, no page-scoped style and no script beyond the theme boot. Each row is the
kit's two-line row — a name, then one soft line — because a title beside a sentence does
not fit a phone column.

The data file is the source. Change a row there, then run this; never edit the HTML.
`tests/test_v8_appendix_4586.py` fails a hand edit, a row whose page does not exist, a held
page that slipped in, and a sitemap address that is in neither list.

Run from repo root:  python3 scripts/v8_build_appendix.py          (write)
                     python3 scripts/v8_build_appendix.py --check  (exit 1 if stale)
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = Path(__file__).resolve().parent / "v8_appendix_pages.json"
OUT = ROOT / "site" / "next" / "v8" / "appendix" / "index.html"

MAX_KINDS = 4
TITLE = "Appendix — Average Joe Matt"
DESCRIPTION = "Everything else on the site, in one list."
INTRO = "Everything else on the site, in one list. These pages are older or more detailed than the ones you came from."
EARLIER_DESIGN = "These pages still use the site’s earlier design."


def esc(s: str) -> str:
    return html.escape(str(s), quote=True)


def load(path: Path = DATA) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def problems(data: dict) -> list[str]:
    """Everything wrong with the data file's own shape. [] when it can be rendered."""
    out = []
    kinds = [k["key"] for k in data.get("kinds", [])]
    if not 1 <= len(kinds) <= MAX_KINDS:
        out.append(f"{len(kinds)} kinds — the appendix groups by at most {MAX_KINDS}")
    seen = set()
    for row in data.get("pages", []):
        url = row.get("url", "")
        for field in ("url", "title", "line", "kind"):
            if not str(row.get(field, "")).strip():
                out.append(f"{url or row!r}: no `{field}`")
        if row.get("kind") not in kinds:
            out.append(f"{url}: kind {row.get('kind')!r} is not one of {kinds}")
        if not (url.startswith("/") and url.endswith("/")):
            out.append(f"{url}: a row's url is a site path that starts and ends with a slash")
        if url in seen:
            out.append(f"{url}: listed twice")
        seen.add(url)
    return out


def grouped(data: dict) -> list[tuple[str, list[dict]]]:
    """[(label, rows sorted by title)] in the file's kind order; an empty kind is dropped."""
    out = []
    for kind in data["kinds"]:
        rows = sorted((r for r in data["pages"] if r["kind"] == kind["key"]), key=lambda r: r["title"].lower())
        if rows:
            out.append((kind["label"], rows))
    return out


def _row(row: dict) -> str:
    return (
        f'        <li><a class="ck-coach__name ck-link" href="{esc(row["url"])}">{esc(row["title"])}</a>'
        f'<span class="ck-coach__job">{esc(row["line"])}</span></li>'
    )


def _group(label: str, rows: list[dict]) -> str:
    items = "\n".join(_row(r) for r in rows)
    return f"""    <section class="ck-section ck-section--tight">
      <p class="ck-label">{esc(label)}</p>
      <ul class="ck-coach">
{items}
      </ul>
    </section>"""


def render(data: dict) -> str:
    groups = "\n\n".join(_group(label, rows) for label, rows in grouped(data))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
  <title>{esc(TITLE)}</title>
  <meta name="description" content="{esc(DESCRIPTION)}">
  <meta name="robots" content="noindex,nofollow">
  <link rel="canonical" href="https://averagejoematt.com/next/v8/appendix/">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#FFFFFF">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#0D0F10">
  <link rel="icon" href="/favicon.ico">
  <link rel="preload" href="/assets/fonts/clean/geist-latin.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="/assets/css/clean.css">
  <script src="/assets/js/boot_theme.js"></script>
</head>
<!-- GENERATED by scripts/v8_build_appendix.py from scripts/v8_appendix_pages.json. Do not edit by hand. -->
<body data-ck-page="appendix" data-ck-base="/next/v8/" data-ck-ready="1">
<div class="ck-page">
  <header class="ck-header">
    <a class="ck-header__back" id="ck-back" href="/next/v8/">← Average Joe Matt</a>
  </header>

  <main class="ck-main" id="main">
    <section class="ck-section ck-section--tight">
      <h1>Appendix</h1>
      <p class="ck-soft">{esc(INTRO)}</p>
      <p class="ck-soft">{esc(EARLIER_DESIGN)}</p>
    </section>

{groups}

    <section class="ck-section ck-section--tight">
      <p><a class="ck-link" href="/next/v8/">Back</a></p>
    </section>
  </main>

  <footer class="ck-footer">
    <a href="/next/v8/start/">Start here</a>
    <a href="/next/v8/story/">The story</a>
    <a href="/next/v8/coaches/">The AI coaches</a>
    <a href="https://github.com/averagejoematt/life-platform" rel="noopener">The code</a>
  </footer>
  <p class="ck-small">Preview.</p>
</div>
</body>
</html>
"""


def main(argv: list[str]) -> int:
    data = load()
    bad = problems(data)
    if bad:
        print("v8_build_appendix: the data file cannot be rendered:")
        for b in bad:
            print(f"  - {b}")
        return 1
    page = render(data)
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != page:
            print(f"v8_build_appendix: {OUT.relative_to(ROOT)} is stale — run python3 scripts/v8_build_appendix.py")
            return 1
        print("v8_build_appendix: up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(page, encoding="utf-8")
    print(f"v8_build_appendix: wrote {OUT.relative_to(ROOT)} ({len(data['pages'])} pages in {len(grouped(data))} kinds)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
